// Generated by scripts/generate-data-layer.cjs. Do not edit by hand.
import * as firebaseProvider from "../rtdatabase/AdminProfile"
import * as supabaseProvider from "../providers/supabase/AdminProfile"
import { getModuleProvider } from "./providerRegistry"

type ProviderModule = typeof firebaseProvider
type ProviderFn<T extends keyof ProviderModule> = ProviderModule[T] extends (...args: infer Args) => infer Result
  ? (...args: Args) => Result
  : never

const resolveImplementation = <T extends keyof ProviderModule>(name: T): ProviderFn<T> => {
  const provider = getModuleProvider("AdminProfile")
  const source = provider === "supabase" ? (supabaseProvider as ProviderModule) : (firebaseProvider as ProviderModule)
  const implementation = source[name]
  if (typeof implementation !== "function") {
    throw new Error(`[data-provider] ${String(name)} is not implemented for provider "${provider}" in module "AdminProfile".`)
  }
  return implementation as ProviderFn<T>
}

export const getAdminProfile: typeof firebaseProvider.getAdminProfile = ((...args: Parameters<typeof firebaseProvider.getAdminProfile>) =>
  resolveImplementation("getAdminProfile")(...args)) as typeof firebaseProvider.getAdminProfile

export const setAdminProfile: typeof firebaseProvider.setAdminProfile = ((...args: Parameters<typeof firebaseProvider.setAdminProfile>) =>
  resolveImplementation("setAdminProfile")(...args)) as typeof firebaseProvider.setAdminProfile

export const updateAdminProfile: typeof firebaseProvider.updateAdminProfile = ((...args: Parameters<typeof firebaseProvider.updateAdminProfile>) =>
  resolveImplementation("updateAdminProfile")(...args)) as typeof firebaseProvider.updateAdminProfile

export const deleteAdminProfile: typeof firebaseProvider.deleteAdminProfile = ((...args: Parameters<typeof firebaseProvider.deleteAdminProfile>) =>
  resolveImplementation("deleteAdminProfile")(...args)) as typeof firebaseProvider.deleteAdminProfile
