// Generated by scripts/generate-data-layer.cjs. Do not edit by hand.
import * as firebaseProvider from "../rtdatabase/Analytics"
import * as supabaseProvider from "../providers/supabase/Analytics"
import { getModuleProvider } from "./providerRegistry"

type ProviderModule = typeof firebaseProvider
type ProviderFn<T extends keyof ProviderModule> = ProviderModule[T] extends (...args: infer Args) => infer Result
  ? (...args: Args) => Result
  : never

const resolveImplementation = <T extends keyof ProviderModule>(name: T): ProviderFn<T> => {
  const provider = getModuleProvider("Analytics")
  const source = provider === "supabase" ? (supabaseProvider as ProviderModule) : (firebaseProvider as ProviderModule)
  const implementation = source[name]
  if (typeof implementation !== "function") {
    throw new Error(`[data-provider] ${String(name)} is not implemented for provider "${provider}" in module "Analytics".`)
  }
  return implementation as ProviderFn<T>
}

export const getAnalyticsData: typeof firebaseProvider.getAnalyticsData = ((...args: Parameters<typeof firebaseProvider.getAnalyticsData>) =>
  resolveImplementation("getAnalyticsData")(...args)) as typeof firebaseProvider.getAnalyticsData
