// Generated by scripts/generate-data-layer.cjs. Do not edit by hand.
import * as firebaseProvider from "../rtdatabase/Content"
import * as supabaseProvider from "../providers/supabase/Content"
import { getModuleProvider } from "./providerRegistry"

type ProviderModule = typeof firebaseProvider
type ProviderFn<T extends keyof ProviderModule> = ProviderModule[T] extends (...args: infer Args) => infer Result
  ? (...args: Args) => Result
  : never

const resolveImplementation = <T extends keyof ProviderModule>(name: T): ProviderFn<T> => {
  const provider = getModuleProvider("Content")
  const source = provider === "supabase" ? (supabaseProvider as ProviderModule) : (firebaseProvider as ProviderModule)
  const implementation = source[name]
  if (typeof implementation !== "function") {
    throw new Error(`[data-provider] ${String(name)} is not implemented for provider "${provider}" in module "Content".`)
  }
  return implementation as ProviderFn<T>
}

export const getContentSchedule: typeof firebaseProvider.getContentSchedule = ((...args: Parameters<typeof firebaseProvider.getContentSchedule>) =>
  resolveImplementation("getContentSchedule")(...args)) as typeof firebaseProvider.getContentSchedule

export const addContentPost: typeof firebaseProvider.addContentPost = ((...args: Parameters<typeof firebaseProvider.addContentPost>) =>
  resolveImplementation("addContentPost")(...args)) as typeof firebaseProvider.addContentPost

export const updateContentPost: typeof firebaseProvider.updateContentPost = ((...args: Parameters<typeof firebaseProvider.updateContentPost>) =>
  resolveImplementation("updateContentPost")(...args)) as typeof firebaseProvider.updateContentPost

export const publishContentPost: typeof firebaseProvider.publishContentPost = ((...args: Parameters<typeof firebaseProvider.publishContentPost>) =>
  resolveImplementation("publishContentPost")(...args)) as typeof firebaseProvider.publishContentPost

export const deleteContentPost: typeof firebaseProvider.deleteContentPost = ((...args: Parameters<typeof firebaseProvider.deleteContentPost>) =>
  resolveImplementation("deleteContentPost")(...args)) as typeof firebaseProvider.deleteContentPost

export const getPlatformSettings: typeof firebaseProvider.getPlatformSettings = ((...args: Parameters<typeof firebaseProvider.getPlatformSettings>) =>
  resolveImplementation("getPlatformSettings")(...args)) as typeof firebaseProvider.getPlatformSettings

export const addPlatformSettings: typeof firebaseProvider.addPlatformSettings = ((...args: Parameters<typeof firebaseProvider.addPlatformSettings>) =>
  resolveImplementation("addPlatformSettings")(...args)) as typeof firebaseProvider.addPlatformSettings

export const updatePlatformSettings: typeof firebaseProvider.updatePlatformSettings = ((...args: Parameters<typeof firebaseProvider.updatePlatformSettings>) =>
  resolveImplementation("updatePlatformSettings")(...args)) as typeof firebaseProvider.updatePlatformSettings
