// Generated by scripts/generate-data-layer.cjs. Do not edit by hand.
import * as firebaseProvider from "../rtdatabase/Marketing"
import * as supabaseProvider from "../providers/supabase/Marketing"
import { getModuleProvider } from "./providerRegistry"

type ProviderModule = typeof firebaseProvider
type ProviderFn<T extends keyof ProviderModule> = ProviderModule[T] extends (...args: infer Args) => infer Result
  ? (...args: Args) => Result
  : never

const resolveImplementation = <T extends keyof ProviderModule>(name: T): ProviderFn<T> => {
  const provider = getModuleProvider("Marketing")
  const source = provider === "supabase" ? (supabaseProvider as ProviderModule) : (firebaseProvider as ProviderModule)
  const implementation = source[name]
  if (typeof implementation !== "function") {
    throw new Error(`[data-provider] ${String(name)} is not implemented for provider "${provider}" in module "Marketing".`)
  }
  return implementation as ProviderFn<T>
}

export const getMarketingEvents: typeof firebaseProvider.getMarketingEvents = ((...args: Parameters<typeof firebaseProvider.getMarketingEvents>) =>
  resolveImplementation("getMarketingEvents")(...args)) as typeof firebaseProvider.getMarketingEvents

export const addMarketingEvent: typeof firebaseProvider.addMarketingEvent = ((...args: Parameters<typeof firebaseProvider.addMarketingEvent>) =>
  resolveImplementation("addMarketingEvent")(...args)) as typeof firebaseProvider.addMarketingEvent

export const updateMarketingEvent: typeof firebaseProvider.updateMarketingEvent = ((...args: Parameters<typeof firebaseProvider.updateMarketingEvent>) =>
  resolveImplementation("updateMarketingEvent")(...args)) as typeof firebaseProvider.updateMarketingEvent

export const deleteMarketingEvent: typeof firebaseProvider.deleteMarketingEvent = ((...args: Parameters<typeof firebaseProvider.deleteMarketingEvent>) =>
  resolveImplementation("deleteMarketingEvent")(...args)) as typeof firebaseProvider.deleteMarketingEvent
