// Generated by scripts/generate-data-layer.cjs. Do not edit by hand.
import * as firebaseProvider from "../rtdatabase/Notes"
import * as supabaseProvider from "../providers/supabase/Notes"
import { getModuleProvider } from "./providerRegistry"

type ProviderModule = typeof firebaseProvider
type ProviderFn<T extends keyof ProviderModule> = ProviderModule[T] extends (...args: infer Args) => infer Result
  ? (...args: Args) => Result
  : never

const resolveImplementation = <T extends keyof ProviderModule>(name: T): ProviderFn<T> => {
  const provider = getModuleProvider("Notes")
  const source = provider === "supabase" ? (supabaseProvider as ProviderModule) : (firebaseProvider as ProviderModule)
  const implementation = source[name]
  if (typeof implementation !== "function") {
    throw new Error(`[data-provider] ${String(name)} is not implemented for provider "${provider}" in module "Notes".`)
  }
  return implementation as ProviderFn<T>
}

export const getNotes: typeof firebaseProvider.getNotes = ((...args: Parameters<typeof firebaseProvider.getNotes>) =>
  resolveImplementation("getNotes")(...args)) as typeof firebaseProvider.getNotes

export const addNote: typeof firebaseProvider.addNote = ((...args: Parameters<typeof firebaseProvider.addNote>) =>
  resolveImplementation("addNote")(...args)) as typeof firebaseProvider.addNote

export const updateNote: typeof firebaseProvider.updateNote = ((...args: Parameters<typeof firebaseProvider.updateNote>) =>
  resolveImplementation("updateNote")(...args)) as typeof firebaseProvider.updateNote

export const deleteNote: typeof firebaseProvider.deleteNote = ((...args: Parameters<typeof firebaseProvider.deleteNote>) =>
  resolveImplementation("deleteNote")(...args)) as typeof firebaseProvider.deleteNote
