// Generated by scripts/generate-data-layer.cjs. Do not edit by hand.
import * as firebaseProvider from "../rtdatabase/QR"
import * as supabaseProvider from "../providers/supabase/QR"
import { getModuleProvider } from "./providerRegistry"

type ProviderModule = typeof firebaseProvider
type ProviderFn<T extends keyof ProviderModule> = ProviderModule[T] extends (...args: infer Args) => infer Result
  ? (...args: Args) => Result
  : never

const resolveImplementation = <T extends keyof ProviderModule>(name: T): ProviderFn<T> => {
  const provider = getModuleProvider("QR")
  const source = provider === "supabase" ? (supabaseProvider as ProviderModule) : (firebaseProvider as ProviderModule)
  const implementation = source[name]
  if (typeof implementation !== "function") {
    throw new Error(`[data-provider] ${String(name)} is not implemented for provider "${provider}" in module "QR".`)
  }
  return implementation as ProviderFn<T>
}

export const addPersonalQR: typeof firebaseProvider.addPersonalQR = ((...args: Parameters<typeof firebaseProvider.addPersonalQR>) =>
  resolveImplementation("addPersonalQR")(...args)) as typeof firebaseProvider.addPersonalQR

export const getPersonalQRs: typeof firebaseProvider.getPersonalQRs = ((...args: Parameters<typeof firebaseProvider.getPersonalQRs>) =>
  resolveImplementation("getPersonalQRs")(...args)) as typeof firebaseProvider.getPersonalQRs

export const getPersonalQRByUrl: typeof firebaseProvider.getPersonalQRByUrl = ((...args: Parameters<typeof firebaseProvider.getPersonalQRByUrl>) =>
  resolveImplementation("getPersonalQRByUrl")(...args)) as typeof firebaseProvider.getPersonalQRByUrl

export const updatePersonalQR: typeof firebaseProvider.updatePersonalQR = ((...args: Parameters<typeof firebaseProvider.updatePersonalQR>) =>
  resolveImplementation("updatePersonalQR")(...args)) as typeof firebaseProvider.updatePersonalQR

export const incrementQRScans: typeof firebaseProvider.incrementQRScans = ((...args: Parameters<typeof firebaseProvider.incrementQRScans>) =>
  resolveImplementation("incrementQRScans")(...args)) as typeof firebaseProvider.incrementQRScans

export const addGenericQR: typeof firebaseProvider.addGenericQR = ((...args: Parameters<typeof firebaseProvider.addGenericQR>) =>
  resolveImplementation("addGenericQR")(...args)) as typeof firebaseProvider.addGenericQR

export const getGenericQRs: typeof firebaseProvider.getGenericQRs = ((...args: Parameters<typeof firebaseProvider.getGenericQRs>) =>
  resolveImplementation("getGenericQRs")(...args)) as typeof firebaseProvider.getGenericQRs

export const addLead: typeof firebaseProvider.addLead = ((...args: Parameters<typeof firebaseProvider.addLead>) =>
  resolveImplementation("addLead")(...args)) as typeof firebaseProvider.addLead

export const getLeads: typeof firebaseProvider.getLeads = ((...args: Parameters<typeof firebaseProvider.getLeads>) =>
  resolveImplementation("getLeads")(...args)) as typeof firebaseProvider.getLeads
