// Generated by scripts/generate-data-layer.cjs. Do not edit by hand.
import * as firebaseProvider from "../rtdatabase/Settings"
import * as supabaseProvider from "../providers/supabase/Settings"
import { getModuleProvider } from "./providerRegistry"

type ProviderModule = typeof firebaseProvider
type ProviderFn<T extends keyof ProviderModule> = ProviderModule[T] extends (...args: infer Args) => infer Result
  ? (...args: Args) => Result
  : never

const resolveImplementation = <T extends keyof ProviderModule>(name: T): ProviderFn<T> => {
  const provider = getModuleProvider("Settings")
  const source = provider === "supabase" ? (supabaseProvider as ProviderModule) : (firebaseProvider as ProviderModule)
  const implementation = source[name]
  if (typeof implementation !== "function") {
    throw new Error(`[data-provider] ${String(name)} is not implemented for provider "${provider}" in module "Settings".`)
  }
  return implementation as ProviderFn<T>
}

export const getSettings: typeof firebaseProvider.getSettings = ((...args: Parameters<typeof firebaseProvider.getSettings>) =>
  resolveImplementation("getSettings")(...args)) as typeof firebaseProvider.getSettings
