// Generated by scripts/generate-data-layer.cjs. Do not edit by hand.
import * as firebaseProvider from "../rtdatabase/Accounting"
import * as supabaseProvider from "../providers/supabase/Accounting"
import { getModuleProvider } from "./providerRegistry"

type ProviderModule = typeof firebaseProvider
type ProviderFn<T extends keyof ProviderModule> = ProviderModule[T] extends (...args: infer Args) => infer Result
  ? (...args: Args) => Result
  : never

const resolveImplementation = <T extends keyof ProviderModule>(name: T): ProviderFn<T> => {
  const provider = getModuleProvider("Accounting")
  const source = provider === "supabase" ? (supabaseProvider as ProviderModule) : (firebaseProvider as ProviderModule)
  const implementation = source[name]
  if (typeof implementation !== "function") {
    throw new Error(`[data-provider] ${String(name)} is not implemented for provider "${provider}" in module "Accounting".`)
  }
  return implementation as ProviderFn<T>
}

export const fetchJournals: typeof firebaseProvider.fetchJournals = ((...args: Parameters<typeof firebaseProvider.fetchJournals>) =>
  resolveImplementation("fetchJournals")(...args)) as typeof firebaseProvider.fetchJournals

export const createJournal: typeof firebaseProvider.createJournal = ((...args: Parameters<typeof firebaseProvider.createJournal>) =>
  resolveImplementation("createJournal")(...args)) as typeof firebaseProvider.createJournal

export const updateJournal: typeof firebaseProvider.updateJournal = ((...args: Parameters<typeof firebaseProvider.updateJournal>) =>
  resolveImplementation("updateJournal")(...args)) as typeof firebaseProvider.updateJournal

export const deleteJournal: typeof firebaseProvider.deleteJournal = ((...args: Parameters<typeof firebaseProvider.deleteJournal>) =>
  resolveImplementation("deleteJournal")(...args)) as typeof firebaseProvider.deleteJournal

export const approveJournal: typeof firebaseProvider.approveJournal = ((...args: Parameters<typeof firebaseProvider.approveJournal>) =>
  resolveImplementation("approveJournal")(...args)) as typeof firebaseProvider.approveJournal

export const postJournal: typeof firebaseProvider.postJournal = ((...args: Parameters<typeof firebaseProvider.postJournal>) =>
  resolveImplementation("postJournal")(...args)) as typeof firebaseProvider.postJournal

export const reverseJournal: typeof firebaseProvider.reverseJournal = ((...args: Parameters<typeof firebaseProvider.reverseJournal>) =>
  resolveImplementation("reverseJournal")(...args)) as typeof firebaseProvider.reverseJournal

export const fetchDimensions: typeof firebaseProvider.fetchDimensions = ((...args: Parameters<typeof firebaseProvider.fetchDimensions>) =>
  resolveImplementation("fetchDimensions")(...args)) as typeof firebaseProvider.fetchDimensions

export const createDimension: typeof firebaseProvider.createDimension = ((...args: Parameters<typeof firebaseProvider.createDimension>) =>
  resolveImplementation("createDimension")(...args)) as typeof firebaseProvider.createDimension

export const updateDimension: typeof firebaseProvider.updateDimension = ((...args: Parameters<typeof firebaseProvider.updateDimension>) =>
  resolveImplementation("updateDimension")(...args)) as typeof firebaseProvider.updateDimension

export const deleteDimension: typeof firebaseProvider.deleteDimension = ((...args: Parameters<typeof firebaseProvider.deleteDimension>) =>
  resolveImplementation("deleteDimension")(...args)) as typeof firebaseProvider.deleteDimension

export const fetchPeriodLocks: typeof firebaseProvider.fetchPeriodLocks = ((...args: Parameters<typeof firebaseProvider.fetchPeriodLocks>) =>
  resolveImplementation("fetchPeriodLocks")(...args)) as typeof firebaseProvider.fetchPeriodLocks

export const createPeriodLock: typeof firebaseProvider.createPeriodLock = ((...args: Parameters<typeof firebaseProvider.createPeriodLock>) =>
  resolveImplementation("createPeriodLock")(...args)) as typeof firebaseProvider.createPeriodLock

export const updatePeriodLock: typeof firebaseProvider.updatePeriodLock = ((...args: Parameters<typeof firebaseProvider.updatePeriodLock>) =>
  resolveImplementation("updatePeriodLock")(...args)) as typeof firebaseProvider.updatePeriodLock

export const lockPeriod: typeof firebaseProvider.lockPeriod = ((...args: Parameters<typeof firebaseProvider.lockPeriod>) =>
  resolveImplementation("lockPeriod")(...args)) as typeof firebaseProvider.lockPeriod

export const unlockPeriod: typeof firebaseProvider.unlockPeriod = ((...args: Parameters<typeof firebaseProvider.unlockPeriod>) =>
  resolveImplementation("unlockPeriod")(...args)) as typeof firebaseProvider.unlockPeriod

export const fetchOpeningBalances: typeof firebaseProvider.fetchOpeningBalances = ((...args: Parameters<typeof firebaseProvider.fetchOpeningBalances>) =>
  resolveImplementation("fetchOpeningBalances")(...args)) as typeof firebaseProvider.fetchOpeningBalances

export const createOpeningBalance: typeof firebaseProvider.createOpeningBalance = ((...args: Parameters<typeof firebaseProvider.createOpeningBalance>) =>
  resolveImplementation("createOpeningBalance")(...args)) as typeof firebaseProvider.createOpeningBalance

export const updateOpeningBalance: typeof firebaseProvider.updateOpeningBalance = ((...args: Parameters<typeof firebaseProvider.updateOpeningBalance>) =>
  resolveImplementation("updateOpeningBalance")(...args)) as typeof firebaseProvider.updateOpeningBalance

export const deleteOpeningBalance: typeof firebaseProvider.deleteOpeningBalance = ((...args: Parameters<typeof firebaseProvider.deleteOpeningBalance>) =>
  resolveImplementation("deleteOpeningBalance")(...args)) as typeof firebaseProvider.deleteOpeningBalance
