// Generated by scripts/generate-data-layer.cjs. Do not edit by hand.
import * as firebaseProvider from "../rtdatabase/Bookings"
import * as supabaseProvider from "../providers/supabase/Bookings"
import { getModuleProvider } from "./providerRegistry"

type ProviderModule = typeof firebaseProvider
type ProviderFn<T extends keyof ProviderModule> = ProviderModule[T] extends (...args: infer Args) => infer Result
  ? (...args: Args) => Result
  : never

const resolveImplementation = <T extends keyof ProviderModule>(name: T): ProviderFn<T> => {
  const provider = getModuleProvider("Bookings")
  const source = provider === "supabase" ? (supabaseProvider as ProviderModule) : (firebaseProvider as ProviderModule)
  const implementation = source[name]
  if (typeof implementation !== "function") {
    throw new Error(`[data-provider] ${String(name)} is not implemented for provider "${provider}" in module "Bookings".`)
  }
  return implementation as ProviderFn<T>
}

export const fetchBookings: typeof firebaseProvider.fetchBookings = ((...args: Parameters<typeof firebaseProvider.fetchBookings>) =>
  resolveImplementation("fetchBookings")(...args)) as typeof firebaseProvider.fetchBookings

export const getBookingById: typeof firebaseProvider.getBookingById = ((...args: Parameters<typeof firebaseProvider.getBookingById>) =>
  resolveImplementation("getBookingById")(...args)) as typeof firebaseProvider.getBookingById

export const submitPreorderResponses: typeof firebaseProvider.submitPreorderResponses = ((...args: Parameters<typeof firebaseProvider.submitPreorderResponses>) =>
  resolveImplementation("submitPreorderResponses")(...args)) as typeof firebaseProvider.submitPreorderResponses

export const fetchLocations: typeof firebaseProvider.fetchLocations = ((...args: Parameters<typeof firebaseProvider.fetchLocations>) =>
  resolveImplementation("fetchLocations")(...args)) as typeof firebaseProvider.fetchLocations

export const createLocation: typeof firebaseProvider.createLocation = ((...args: Parameters<typeof firebaseProvider.createLocation>) =>
  resolveImplementation("createLocation")(...args)) as typeof firebaseProvider.createLocation

export const updateLocation: typeof firebaseProvider.updateLocation = ((...args: Parameters<typeof firebaseProvider.updateLocation>) =>
  resolveImplementation("updateLocation")(...args)) as typeof firebaseProvider.updateLocation

export const deleteLocation: typeof firebaseProvider.deleteLocation = ((...args: Parameters<typeof firebaseProvider.deleteLocation>) =>
  resolveImplementation("deleteLocation")(...args)) as typeof firebaseProvider.deleteLocation

export const fetchBookingsByDate: typeof firebaseProvider.fetchBookingsByDate = ((...args: Parameters<typeof firebaseProvider.fetchBookingsByDate>) =>
  resolveImplementation("fetchBookingsByDate")(...args)) as typeof firebaseProvider.fetchBookingsByDate

export const createBooking: typeof firebaseProvider.createBooking = ((...args: Parameters<typeof firebaseProvider.createBooking>) =>
  resolveImplementation("createBooking")(...args)) as typeof firebaseProvider.createBooking

export const updateBooking: typeof firebaseProvider.updateBooking = ((...args: Parameters<typeof firebaseProvider.updateBooking>) =>
  resolveImplementation("updateBooking")(...args)) as typeof firebaseProvider.updateBooking

export const deleteBooking: typeof firebaseProvider.deleteBooking = ((...args: Parameters<typeof firebaseProvider.deleteBooking>) =>
  resolveImplementation("deleteBooking")(...args)) as typeof firebaseProvider.deleteBooking

export const fetchTables: typeof firebaseProvider.fetchTables = ((...args: Parameters<typeof firebaseProvider.fetchTables>) =>
  resolveImplementation("fetchTables")(...args)) as typeof firebaseProvider.fetchTables

export const createTable: typeof firebaseProvider.createTable = ((...args: Parameters<typeof firebaseProvider.createTable>) =>
  resolveImplementation("createTable")(...args)) as typeof firebaseProvider.createTable

export const updateTable: typeof firebaseProvider.updateTable = ((...args: Parameters<typeof firebaseProvider.updateTable>) =>
  resolveImplementation("updateTable")(...args)) as typeof firebaseProvider.updateTable

export const deleteTable: typeof firebaseProvider.deleteTable = ((...args: Parameters<typeof firebaseProvider.deleteTable>) =>
  resolveImplementation("deleteTable")(...args)) as typeof firebaseProvider.deleteTable

export const fetchTableTypes: typeof firebaseProvider.fetchTableTypes = ((...args: Parameters<typeof firebaseProvider.fetchTableTypes>) =>
  resolveImplementation("fetchTableTypes")(...args)) as typeof firebaseProvider.fetchTableTypes

export const createTableType: typeof firebaseProvider.createTableType = ((...args: Parameters<typeof firebaseProvider.createTableType>) =>
  resolveImplementation("createTableType")(...args)) as typeof firebaseProvider.createTableType

export const updateTableType: typeof firebaseProvider.updateTableType = ((...args: Parameters<typeof firebaseProvider.updateTableType>) =>
  resolveImplementation("updateTableType")(...args)) as typeof firebaseProvider.updateTableType

export const deleteTableType: typeof firebaseProvider.deleteTableType = ((...args: Parameters<typeof firebaseProvider.deleteTableType>) =>
  resolveImplementation("deleteTableType")(...args)) as typeof firebaseProvider.deleteTableType

export const fetchBookingTypes: typeof firebaseProvider.fetchBookingTypes = ((...args: Parameters<typeof firebaseProvider.fetchBookingTypes>) =>
  resolveImplementation("fetchBookingTypes")(...args)) as typeof firebaseProvider.fetchBookingTypes

export const createBookingType: typeof firebaseProvider.createBookingType = ((...args: Parameters<typeof firebaseProvider.createBookingType>) =>
  resolveImplementation("createBookingType")(...args)) as typeof firebaseProvider.createBookingType

export const updateBookingType: typeof firebaseProvider.updateBookingType = ((...args: Parameters<typeof firebaseProvider.updateBookingType>) =>
  resolveImplementation("updateBookingType")(...args)) as typeof firebaseProvider.updateBookingType

export const deleteBookingType: typeof firebaseProvider.deleteBookingType = ((...args: Parameters<typeof firebaseProvider.deleteBookingType>) =>
  resolveImplementation("deleteBookingType")(...args)) as typeof firebaseProvider.deleteBookingType

export const fetchBookingStatuses: typeof firebaseProvider.fetchBookingStatuses = ((...args: Parameters<typeof firebaseProvider.fetchBookingStatuses>) =>
  resolveImplementation("fetchBookingStatuses")(...args)) as typeof firebaseProvider.fetchBookingStatuses

export const createBookingStatus: typeof firebaseProvider.createBookingStatus = ((...args: Parameters<typeof firebaseProvider.createBookingStatus>) =>
  resolveImplementation("createBookingStatus")(...args)) as typeof firebaseProvider.createBookingStatus

export const updateBookingStatus: typeof firebaseProvider.updateBookingStatus = ((...args: Parameters<typeof firebaseProvider.updateBookingStatus>) =>
  resolveImplementation("updateBookingStatus")(...args)) as typeof firebaseProvider.updateBookingStatus

export const deleteBookingStatus: typeof firebaseProvider.deleteBookingStatus = ((...args: Parameters<typeof firebaseProvider.deleteBookingStatus>) =>
  resolveImplementation("deleteBookingStatus")(...args)) as typeof firebaseProvider.deleteBookingStatus

export const fetchPreorderProfiles: typeof firebaseProvider.fetchPreorderProfiles = ((...args: Parameters<typeof firebaseProvider.fetchPreorderProfiles>) =>
  resolveImplementation("fetchPreorderProfiles")(...args)) as typeof firebaseProvider.fetchPreorderProfiles

export const savePreorderProfile: typeof firebaseProvider.savePreorderProfile = ((...args: Parameters<typeof firebaseProvider.savePreorderProfile>) =>
  resolveImplementation("savePreorderProfile")(...args)) as typeof firebaseProvider.savePreorderProfile

export const deletePreorderProfile: typeof firebaseProvider.deletePreorderProfile = ((...args: Parameters<typeof firebaseProvider.deletePreorderProfile>) =>
  resolveImplementation("deletePreorderProfile")(...args)) as typeof firebaseProvider.deletePreorderProfile

export const appendBookingMessage: typeof firebaseProvider.appendBookingMessage = ((...args: Parameters<typeof firebaseProvider.appendBookingMessage>) =>
  resolveImplementation("appendBookingMessage")(...args)) as typeof firebaseProvider.appendBookingMessage

export const fetchWaitlist: typeof firebaseProvider.fetchWaitlist = ((...args: Parameters<typeof firebaseProvider.fetchWaitlist>) =>
  resolveImplementation("fetchWaitlist")(...args)) as typeof firebaseProvider.fetchWaitlist

export const addToWaitlist: typeof firebaseProvider.addToWaitlist = ((...args: Parameters<typeof firebaseProvider.addToWaitlist>) =>
  resolveImplementation("addToWaitlist")(...args)) as typeof firebaseProvider.addToWaitlist

export const updateWaitlistEntry: typeof firebaseProvider.updateWaitlistEntry = ((...args: Parameters<typeof firebaseProvider.updateWaitlistEntry>) =>
  resolveImplementation("updateWaitlistEntry")(...args)) as typeof firebaseProvider.updateWaitlistEntry

export const removeFromWaitlist: typeof firebaseProvider.removeFromWaitlist = ((...args: Parameters<typeof firebaseProvider.removeFromWaitlist>) =>
  resolveImplementation("removeFromWaitlist")(...args)) as typeof firebaseProvider.removeFromWaitlist

export const fetchCustomers: typeof firebaseProvider.fetchCustomers = ((...args: Parameters<typeof firebaseProvider.fetchCustomers>) =>
  resolveImplementation("fetchCustomers")(...args)) as typeof firebaseProvider.fetchCustomers

export const saveCustomer: typeof firebaseProvider.saveCustomer = ((...args: Parameters<typeof firebaseProvider.saveCustomer>) =>
  resolveImplementation("saveCustomer")(...args)) as typeof firebaseProvider.saveCustomer

export const deleteCustomer: typeof firebaseProvider.deleteCustomer = ((...args: Parameters<typeof firebaseProvider.deleteCustomer>) =>
  resolveImplementation("deleteCustomer")(...args)) as typeof firebaseProvider.deleteCustomer

export const fetchBookingSettings: typeof firebaseProvider.fetchBookingSettings = ((...args: Parameters<typeof firebaseProvider.fetchBookingSettings>) =>
  resolveImplementation("fetchBookingSettings")(...args)) as typeof firebaseProvider.fetchBookingSettings

export const saveBookingSettings: typeof firebaseProvider.saveBookingSettings = ((...args: Parameters<typeof firebaseProvider.saveBookingSettings>) =>
  resolveImplementation("saveBookingSettings")(...args)) as typeof firebaseProvider.saveBookingSettings

export const fetchFloorPlans: typeof firebaseProvider.fetchFloorPlans = ((...args: Parameters<typeof firebaseProvider.fetchFloorPlans>) =>
  resolveImplementation("fetchFloorPlans")(...args)) as typeof firebaseProvider.fetchFloorPlans

export const fetchBookingStats: typeof firebaseProvider.fetchBookingStats = ((...args: Parameters<typeof firebaseProvider.fetchBookingStats>) =>
  resolveImplementation("fetchBookingStats")(...args)) as typeof firebaseProvider.fetchBookingStats

export const saveFloorPlan: typeof firebaseProvider.saveFloorPlan = ((...args: Parameters<typeof firebaseProvider.saveFloorPlan>) =>
  resolveImplementation("saveFloorPlan")(...args)) as typeof firebaseProvider.saveFloorPlan

export const deleteFloorPlan: typeof firebaseProvider.deleteFloorPlan = ((...args: Parameters<typeof firebaseProvider.deleteFloorPlan>) =>
  resolveImplementation("deleteFloorPlan")(...args)) as typeof firebaseProvider.deleteFloorPlan

export const calculateBookingStats: typeof firebaseProvider.calculateBookingStats = ((...args: Parameters<typeof firebaseProvider.calculateBookingStats>) =>
  resolveImplementation("calculateBookingStats")(...args)) as typeof firebaseProvider.calculateBookingStats

export const useBookings: typeof firebaseProvider.useBookings = ((...args: Parameters<typeof firebaseProvider.useBookings>) =>
  resolveImplementation("useBookings")(...args)) as typeof firebaseProvider.useBookings

export const useTables: typeof firebaseProvider.useTables = ((...args: Parameters<typeof firebaseProvider.useTables>) =>
  resolveImplementation("useTables")(...args)) as typeof firebaseProvider.useTables

export const useWaitlist: typeof firebaseProvider.useWaitlist = ((...args: Parameters<typeof firebaseProvider.useWaitlist>) =>
  resolveImplementation("useWaitlist")(...args)) as typeof firebaseProvider.useWaitlist

export const fetchBookingTags: typeof firebaseProvider.fetchBookingTags = ((...args: Parameters<typeof firebaseProvider.fetchBookingTags>) =>
  resolveImplementation("fetchBookingTags")(...args)) as typeof firebaseProvider.fetchBookingTags

export const createBookingTag: typeof firebaseProvider.createBookingTag = ((...args: Parameters<typeof firebaseProvider.createBookingTag>) =>
  resolveImplementation("createBookingTag")(...args)) as typeof firebaseProvider.createBookingTag

export const updateBookingTag: typeof firebaseProvider.updateBookingTag = ((...args: Parameters<typeof firebaseProvider.updateBookingTag>) =>
  resolveImplementation("updateBookingTag")(...args)) as typeof firebaseProvider.updateBookingTag

export const deleteBookingTag: typeof firebaseProvider.deleteBookingTag = ((...args: Parameters<typeof firebaseProvider.deleteBookingTag>) =>
  resolveImplementation("deleteBookingTag")(...args)) as typeof firebaseProvider.deleteBookingTag

export const fetchStockCourses: typeof firebaseProvider.fetchStockCourses = ((...args: Parameters<typeof firebaseProvider.fetchStockCourses>) =>
  resolveImplementation("fetchStockCourses")(...args)) as typeof firebaseProvider.fetchStockCourses

export const fetchStockProducts: typeof firebaseProvider.fetchStockProducts = ((...args: Parameters<typeof firebaseProvider.fetchStockProducts>) =>
  resolveImplementation("fetchStockProducts")(...args)) as typeof firebaseProvider.fetchStockProducts

export const createFloorPlan: typeof firebaseProvider.createFloorPlan = ((...args: Parameters<typeof firebaseProvider.createFloorPlan>) =>
  resolveImplementation("createFloorPlan")(...args)) as typeof firebaseProvider.createFloorPlan

export const updateFloorPlan: typeof firebaseProvider.updateFloorPlan = ((...args: Parameters<typeof firebaseProvider.updateFloorPlan>) =>
  resolveImplementation("updateFloorPlan")(...args)) as typeof firebaseProvider.updateFloorPlan

export const updateTableElement: typeof firebaseProvider.updateTableElement = ((...args: Parameters<typeof firebaseProvider.updateTableElement>) =>
  resolveImplementation("updateTableElement")(...args)) as typeof firebaseProvider.updateTableElement

export const addTableToFloorPlan: typeof firebaseProvider.addTableToFloorPlan = ((...args: Parameters<typeof firebaseProvider.addTableToFloorPlan>) =>
  resolveImplementation("addTableToFloorPlan")(...args)) as typeof firebaseProvider.addTableToFloorPlan

export const removeTableFromFloorPlan: typeof firebaseProvider.removeTableFromFloorPlan = ((...args: Parameters<typeof firebaseProvider.removeTableFromFloorPlan>) =>
  resolveImplementation("removeTableFromFloorPlan")(...args)) as typeof firebaseProvider.removeTableFromFloorPlan
