// Generated by scripts/generate-data-layer.cjs. Do not edit by hand.
import * as firebaseProvider from "../rtdatabase/Company"
import * as supabaseProvider from "../providers/supabase/Company"
import { getModuleProvider } from "./providerRegistry"

type ProviderModule = typeof firebaseProvider
type ProviderFn<T extends keyof ProviderModule> = ProviderModule[T] extends (...args: infer Args) => infer Result
  ? (...args: Args) => Result
  : never

const resolveImplementation = <T extends keyof ProviderModule>(name: T): ProviderFn<T> => {
  const provider = getModuleProvider("Company")
  const source = provider === "supabase" ? (supabaseProvider as ProviderModule) : (firebaseProvider as ProviderModule)
  const implementation = source[name]
  if (typeof implementation !== "function") {
    throw new Error(`[data-provider] ${String(name)} is not implemented for provider "${provider}" in module "Company".`)
  }
  return implementation as ProviderFn<T>
}

export const fetchCompanyReports: typeof firebaseProvider.fetchCompanyReports = ((...args: Parameters<typeof firebaseProvider.fetchCompanyReports>) =>
  resolveImplementation("fetchCompanyReports")(...args)) as typeof firebaseProvider.fetchCompanyReports

export const fetchCompanyReport: typeof firebaseProvider.fetchCompanyReport = ((...args: Parameters<typeof firebaseProvider.fetchCompanyReport>) =>
  resolveImplementation("fetchCompanyReport")(...args)) as typeof firebaseProvider.fetchCompanyReport

export const saveCompanyReport: typeof firebaseProvider.saveCompanyReport = ((...args: Parameters<typeof firebaseProvider.saveCompanyReport>) =>
  resolveImplementation("saveCompanyReport")(...args)) as typeof firebaseProvider.saveCompanyReport

export const deleteCompanyReport: typeof firebaseProvider.deleteCompanyReport = ((...args: Parameters<typeof firebaseProvider.deleteCompanyReport>) =>
  resolveImplementation("deleteCompanyReport")(...args)) as typeof firebaseProvider.deleteCompanyReport

export const fetchCompanySectionSettings: typeof firebaseProvider.fetchCompanySectionSettings = ((...args: Parameters<typeof firebaseProvider.fetchCompanySectionSettings>) =>
  resolveImplementation("fetchCompanySectionSettings")(...args)) as typeof firebaseProvider.fetchCompanySectionSettings

export const saveCompanySectionSettings: typeof firebaseProvider.saveCompanySectionSettings = ((...args: Parameters<typeof firebaseProvider.saveCompanySectionSettings>) =>
  resolveImplementation("saveCompanySectionSettings")(...args)) as typeof firebaseProvider.saveCompanySectionSettings

export const fetchDataConfiguration: typeof firebaseProvider.fetchDataConfiguration = ((...args: Parameters<typeof firebaseProvider.fetchDataConfiguration>) =>
  resolveImplementation("fetchDataConfiguration")(...args)) as typeof firebaseProvider.fetchDataConfiguration

export const saveDataConfiguration: typeof firebaseProvider.saveDataConfiguration = ((...args: Parameters<typeof firebaseProvider.saveDataConfiguration>) =>
  resolveImplementation("saveDataConfiguration")(...args)) as typeof firebaseProvider.saveDataConfiguration

export const saveSiteDataConfiguration: typeof firebaseProvider.saveSiteDataConfiguration = ((...args: Parameters<typeof firebaseProvider.saveSiteDataConfiguration>) =>
  resolveImplementation("saveSiteDataConfiguration")(...args)) as typeof firebaseProvider.saveSiteDataConfiguration

export const getUserCompanyAssociation: typeof firebaseProvider.getUserCompanyAssociation = ((...args: Parameters<typeof firebaseProvider.getUserCompanyAssociation>) =>
  resolveImplementation("getUserCompanyAssociation")(...args)) as typeof firebaseProvider.getUserCompanyAssociation

export const getUserCompaniesRaw: typeof firebaseProvider.getUserCompaniesRaw = ((...args: Parameters<typeof firebaseProvider.getUserCompaniesRaw>) =>
  resolveImplementation("getUserCompaniesRaw")(...args)) as typeof firebaseProvider.getUserCompaniesRaw

export const createCompanyInDb: typeof firebaseProvider.createCompanyInDb = ((...args: Parameters<typeof firebaseProvider.createCompanyInDb>) =>
  resolveImplementation("createCompanyInDb")(...args)) as typeof firebaseProvider.createCompanyInDb

export const updateCompanyInDb: typeof firebaseProvider.updateCompanyInDb = ((...args: Parameters<typeof firebaseProvider.updateCompanyInDb>) =>
  resolveImplementation("updateCompanyInDb")(...args)) as typeof firebaseProvider.updateCompanyInDb

export const getCompanyFromDb: typeof firebaseProvider.getCompanyFromDb = ((...args: Parameters<typeof firebaseProvider.getCompanyFromDb>) =>
  resolveImplementation("getCompanyFromDb")(...args)) as typeof firebaseProvider.getCompanyFromDb

export const deleteCompanyFromDb: typeof firebaseProvider.deleteCompanyFromDb = ((...args: Parameters<typeof firebaseProvider.deleteCompanyFromDb>) =>
  resolveImplementation("deleteCompanyFromDb")(...args)) as typeof firebaseProvider.deleteCompanyFromDb

export const initializePermissionsInDb: typeof firebaseProvider.initializePermissionsInDb = ((...args: Parameters<typeof firebaseProvider.initializePermissionsInDb>) =>
  resolveImplementation("initializePermissionsInDb")(...args)) as typeof firebaseProvider.initializePermissionsInDb

export const updateRolePermissionsInDb: typeof firebaseProvider.updateRolePermissionsInDb = ((...args: Parameters<typeof firebaseProvider.updateRolePermissionsInDb>) =>
  resolveImplementation("updateRolePermissionsInDb")(...args)) as typeof firebaseProvider.updateRolePermissionsInDb

export const updateDepartmentPermissionsInDb: typeof firebaseProvider.updateDepartmentPermissionsInDb = ((...args: Parameters<typeof firebaseProvider.updateDepartmentPermissionsInDb>) =>
  resolveImplementation("updateDepartmentPermissionsInDb")(...args)) as typeof firebaseProvider.updateDepartmentPermissionsInDb

export const updateUserPermissionsInDb: typeof firebaseProvider.updateUserPermissionsInDb = ((...args: Parameters<typeof firebaseProvider.updateUserPermissionsInDb>) =>
  resolveImplementation("updateUserPermissionsInDb")(...args)) as typeof firebaseProvider.updateUserPermissionsInDb

export const updateEmployeePermissionsInDb: typeof firebaseProvider.updateEmployeePermissionsInDb = ((...args: Parameters<typeof firebaseProvider.updateEmployeePermissionsInDb>) =>
  resolveImplementation("updateEmployeePermissionsInDb")(...args)) as typeof firebaseProvider.updateEmployeePermissionsInDb

export const getPermissionsFromDb: typeof firebaseProvider.getPermissionsFromDb = ((...args: Parameters<typeof firebaseProvider.getPermissionsFromDb>) =>
  resolveImplementation("getPermissionsFromDb")(...args)) as typeof firebaseProvider.getPermissionsFromDb

export const updateDefaultRoleInDb: typeof firebaseProvider.updateDefaultRoleInDb = ((...args: Parameters<typeof firebaseProvider.updateDefaultRoleInDb>) =>
  resolveImplementation("updateDefaultRoleInDb")(...args)) as typeof firebaseProvider.updateDefaultRoleInDb

export const updateDefaultDepartmentInDb: typeof firebaseProvider.updateDefaultDepartmentInDb = ((...args: Parameters<typeof firebaseProvider.updateDefaultDepartmentInDb>) =>
  resolveImplementation("updateDefaultDepartmentInDb")(...args)) as typeof firebaseProvider.updateDefaultDepartmentInDb

export const updateDefaultPermissionsInDb: typeof firebaseProvider.updateDefaultPermissionsInDb = ((...args: Parameters<typeof firebaseProvider.updateDefaultPermissionsInDb>) =>
  resolveImplementation("updateDefaultPermissionsInDb")(...args)) as typeof firebaseProvider.updateDefaultPermissionsInDb

export const updateDepartmentPermissionsActiveInDb: typeof firebaseProvider.updateDepartmentPermissionsActiveInDb = ((...args: Parameters<typeof firebaseProvider.updateDepartmentPermissionsActiveInDb>) =>
  resolveImplementation("updateDepartmentPermissionsActiveInDb")(...args)) as typeof firebaseProvider.updateDepartmentPermissionsActiveInDb

export const updateRolePermissionsActiveInDb: typeof firebaseProvider.updateRolePermissionsActiveInDb = ((...args: Parameters<typeof firebaseProvider.updateRolePermissionsActiveInDb>) =>
  resolveImplementation("updateRolePermissionsActiveInDb")(...args)) as typeof firebaseProvider.updateRolePermissionsActiveInDb

export const updateUserPermissionsActiveInDb: typeof firebaseProvider.updateUserPermissionsActiveInDb = ((...args: Parameters<typeof firebaseProvider.updateUserPermissionsActiveInDb>) =>
  resolveImplementation("updateUserPermissionsActiveInDb")(...args)) as typeof firebaseProvider.updateUserPermissionsActiveInDb

export const updateEmployeePermissionsActiveInDb: typeof firebaseProvider.updateEmployeePermissionsActiveInDb = ((...args: Parameters<typeof firebaseProvider.updateEmployeePermissionsActiveInDb>) =>
  resolveImplementation("updateEmployeePermissionsActiveInDb")(...args)) as typeof firebaseProvider.updateEmployeePermissionsActiveInDb

export const initializeConfigInDb: typeof firebaseProvider.initializeConfigInDb = ((...args: Parameters<typeof firebaseProvider.initializeConfigInDb>) =>
  resolveImplementation("initializeConfigInDb")(...args)) as typeof firebaseProvider.initializeConfigInDb

export const updateCompanyConfigInDb: typeof firebaseProvider.updateCompanyConfigInDb = ((...args: Parameters<typeof firebaseProvider.updateCompanyConfigInDb>) =>
  resolveImplementation("updateCompanyConfigInDb")(...args)) as typeof firebaseProvider.updateCompanyConfigInDb

export const updateSiteConfigInDb: typeof firebaseProvider.updateSiteConfigInDb = ((...args: Parameters<typeof firebaseProvider.updateSiteConfigInDb>) =>
  resolveImplementation("updateSiteConfigInDb")(...args)) as typeof firebaseProvider.updateSiteConfigInDb

export const updateSubsiteConfigInDb: typeof firebaseProvider.updateSubsiteConfigInDb = ((...args: Parameters<typeof firebaseProvider.updateSubsiteConfigInDb>) =>
  resolveImplementation("updateSubsiteConfigInDb")(...args)) as typeof firebaseProvider.updateSubsiteConfigInDb

export const getConfigFromDb: typeof firebaseProvider.getConfigFromDb = ((...args: Parameters<typeof firebaseProvider.getConfigFromDb>) =>
  resolveImplementation("getConfigFromDb")(...args)) as typeof firebaseProvider.getConfigFromDb

export const createSiteInDb: typeof firebaseProvider.createSiteInDb = ((...args: Parameters<typeof firebaseProvider.createSiteInDb>) =>
  resolveImplementation("createSiteInDb")(...args)) as typeof firebaseProvider.createSiteInDb

export const updateSiteInDb: typeof firebaseProvider.updateSiteInDb = ((...args: Parameters<typeof firebaseProvider.updateSiteInDb>) =>
  resolveImplementation("updateSiteInDb")(...args)) as typeof firebaseProvider.updateSiteInDb

export const deleteSiteFromDb: typeof firebaseProvider.deleteSiteFromDb = ((...args: Parameters<typeof firebaseProvider.deleteSiteFromDb>) =>
  resolveImplementation("deleteSiteFromDb")(...args)) as typeof firebaseProvider.deleteSiteFromDb

export const invalidateSitesCache: typeof firebaseProvider.invalidateSitesCache = ((...args: Parameters<typeof firebaseProvider.invalidateSitesCache>) =>
  resolveImplementation("invalidateSitesCache")(...args)) as typeof firebaseProvider.invalidateSitesCache

export const getSitesFromDb: typeof firebaseProvider.getSitesFromDb = ((...args: Parameters<typeof firebaseProvider.getSitesFromDb>) =>
  resolveImplementation("getSitesFromDb")(...args)) as typeof firebaseProvider.getSitesFromDb

export const createSubsiteInDb: typeof firebaseProvider.createSubsiteInDb = ((...args: Parameters<typeof firebaseProvider.createSubsiteInDb>) =>
  resolveImplementation("createSubsiteInDb")(...args)) as typeof firebaseProvider.createSubsiteInDb

export const updateSubsiteInDb: typeof firebaseProvider.updateSubsiteInDb = ((...args: Parameters<typeof firebaseProvider.updateSubsiteInDb>) =>
  resolveImplementation("updateSubsiteInDb")(...args)) as typeof firebaseProvider.updateSubsiteInDb

export const getSubsiteFromDb: typeof firebaseProvider.getSubsiteFromDb = ((...args: Parameters<typeof firebaseProvider.getSubsiteFromDb>) =>
  resolveImplementation("getSubsiteFromDb")(...args)) as typeof firebaseProvider.getSubsiteFromDb

export const deleteSubsiteFromDb: typeof firebaseProvider.deleteSubsiteFromDb = ((...args: Parameters<typeof firebaseProvider.deleteSubsiteFromDb>) =>
  resolveImplementation("deleteSubsiteFromDb")(...args)) as typeof firebaseProvider.deleteSubsiteFromDb

export const fetchChecklistsFromDb: typeof firebaseProvider.fetchChecklistsFromDb = ((...args: Parameters<typeof firebaseProvider.fetchChecklistsFromDb>) =>
  resolveImplementation("fetchChecklistsFromDb")(...args)) as typeof firebaseProvider.fetchChecklistsFromDb

export const createChecklistInDb: typeof firebaseProvider.createChecklistInDb = ((...args: Parameters<typeof firebaseProvider.createChecklistInDb>) =>
  resolveImplementation("createChecklistInDb")(...args)) as typeof firebaseProvider.createChecklistInDb

export const updateChecklistInDb: typeof firebaseProvider.updateChecklistInDb = ((...args: Parameters<typeof firebaseProvider.updateChecklistInDb>) =>
  resolveImplementation("updateChecklistInDb")(...args)) as typeof firebaseProvider.updateChecklistInDb

export const deleteChecklistFromDb: typeof firebaseProvider.deleteChecklistFromDb = ((...args: Parameters<typeof firebaseProvider.deleteChecklistFromDb>) =>
  resolveImplementation("deleteChecklistFromDb")(...args)) as typeof firebaseProvider.deleteChecklistFromDb

export const fetchChecklistCompletionsFromDb: typeof firebaseProvider.fetchChecklistCompletionsFromDb = ((...args: Parameters<typeof firebaseProvider.fetchChecklistCompletionsFromDb>) =>
  resolveImplementation("fetchChecklistCompletionsFromDb")(...args)) as typeof firebaseProvider.fetchChecklistCompletionsFromDb

export const createChecklistCompletionInDb: typeof firebaseProvider.createChecklistCompletionInDb = ((...args: Parameters<typeof firebaseProvider.createChecklistCompletionInDb>) =>
  resolveImplementation("createChecklistCompletionInDb")(...args)) as typeof firebaseProvider.createChecklistCompletionInDb

export const deleteChecklistCompletionFromDb: typeof firebaseProvider.deleteChecklistCompletionFromDb = ((...args: Parameters<typeof firebaseProvider.deleteChecklistCompletionFromDb>) =>
  resolveImplementation("deleteChecklistCompletionFromDb")(...args)) as typeof firebaseProvider.deleteChecklistCompletionFromDb

export const fetchCompanySetupFromDb: typeof firebaseProvider.fetchCompanySetupFromDb = ((...args: Parameters<typeof firebaseProvider.fetchCompanySetupFromDb>) =>
  resolveImplementation("fetchCompanySetupFromDb")(...args)) as typeof firebaseProvider.fetchCompanySetupFromDb

export const saveCompanySetupToDb: typeof firebaseProvider.saveCompanySetupToDb = ((...args: Parameters<typeof firebaseProvider.saveCompanySetupToDb>) =>
  resolveImplementation("saveCompanySetupToDb")(...args)) as typeof firebaseProvider.saveCompanySetupToDb

export const fetchUserProfileFromDb: typeof firebaseProvider.fetchUserProfileFromDb = ((...args: Parameters<typeof firebaseProvider.fetchUserProfileFromDb>) =>
  resolveImplementation("fetchUserProfileFromDb")(...args)) as typeof firebaseProvider.fetchUserProfileFromDb

export const updateUserProfileInDb: typeof firebaseProvider.updateUserProfileInDb = ((...args: Parameters<typeof firebaseProvider.updateUserProfileInDb>) =>
  resolveImplementation("updateUserProfileInDb")(...args)) as typeof firebaseProvider.updateUserProfileInDb

export const fetchCompanyMessagesFromDb: typeof firebaseProvider.fetchCompanyMessagesFromDb = ((...args: Parameters<typeof firebaseProvider.fetchCompanyMessagesFromDb>) =>
  resolveImplementation("fetchCompanyMessagesFromDb")(...args)) as typeof firebaseProvider.fetchCompanyMessagesFromDb

export const createCompanyMessageInDb: typeof firebaseProvider.createCompanyMessageInDb = ((...args: Parameters<typeof firebaseProvider.createCompanyMessageInDb>) =>
  resolveImplementation("createCompanyMessageInDb")(...args)) as typeof firebaseProvider.createCompanyMessageInDb

export const createSiteInviteInDb: typeof firebaseProvider.createSiteInviteInDb = ((...args: Parameters<typeof firebaseProvider.createSiteInviteInDb>) =>
  resolveImplementation("createSiteInviteInDb")(...args)) as typeof firebaseProvider.createSiteInviteInDb

export const getSiteInvitesFromDb: typeof firebaseProvider.getSiteInvitesFromDb = ((...args: Parameters<typeof firebaseProvider.getSiteInvitesFromDb>) =>
  resolveImplementation("getSiteInvitesFromDb")(...args)) as typeof firebaseProvider.getSiteInvitesFromDb

export const getSiteInviteByCodeFromDb: typeof firebaseProvider.getSiteInviteByCodeFromDb = ((...args: Parameters<typeof firebaseProvider.getSiteInviteByCodeFromDb>) =>
  resolveImplementation("getSiteInviteByCodeFromDb")(...args)) as typeof firebaseProvider.getSiteInviteByCodeFromDb

export const updateSiteInviteInDb: typeof firebaseProvider.updateSiteInviteInDb = ((...args: Parameters<typeof firebaseProvider.updateSiteInviteInDb>) =>
  resolveImplementation("updateSiteInviteInDb")(...args)) as typeof firebaseProvider.updateSiteInviteInDb

export const createCompanyInviteInDb: typeof firebaseProvider.createCompanyInviteInDb = ((...args: Parameters<typeof firebaseProvider.createCompanyInviteInDb>) =>
  resolveImplementation("createCompanyInviteInDb")(...args)) as typeof firebaseProvider.createCompanyInviteInDb

export const getCompanyInviteByCodeFromDb: typeof firebaseProvider.getCompanyInviteByCodeFromDb = ((...args: Parameters<typeof firebaseProvider.getCompanyInviteByCodeFromDb>) =>
  resolveImplementation("getCompanyInviteByCodeFromDb")(...args)) as typeof firebaseProvider.getCompanyInviteByCodeFromDb

export const updateCompanyInviteInDb: typeof firebaseProvider.updateCompanyInviteInDb = ((...args: Parameters<typeof firebaseProvider.updateCompanyInviteInDb>) =>
  resolveImplementation("updateCompanyInviteInDb")(...args)) as typeof firebaseProvider.updateCompanyInviteInDb

export const getCompanyUserFromDb: typeof firebaseProvider.getCompanyUserFromDb = ((...args: Parameters<typeof firebaseProvider.getCompanyUserFromDb>) =>
  resolveImplementation("getCompanyUserFromDb")(...args)) as typeof firebaseProvider.getCompanyUserFromDb

export const updateCompanyUserInDb: typeof firebaseProvider.updateCompanyUserInDb = ((...args: Parameters<typeof firebaseProvider.updateCompanyUserInDb>) =>
  resolveImplementation("updateCompanyUserInDb")(...args)) as typeof firebaseProvider.updateCompanyUserInDb

export const getUserCompanyFromDb: typeof firebaseProvider.getUserCompanyFromDb = ((...args: Parameters<typeof firebaseProvider.getUserCompanyFromDb>) =>
  resolveImplementation("getUserCompanyFromDb")(...args)) as typeof firebaseProvider.getUserCompanyFromDb

export const updateUserCompanyInDb: typeof firebaseProvider.updateUserCompanyInDb = ((...args: Parameters<typeof firebaseProvider.updateUserCompanyInDb>) =>
  resolveImplementation("updateUserCompanyInDb")(...args)) as typeof firebaseProvider.updateUserCompanyInDb

export const addUserToCompanyInDb: typeof firebaseProvider.addUserToCompanyInDb = ((...args: Parameters<typeof firebaseProvider.addUserToCompanyInDb>) =>
  resolveImplementation("addUserToCompanyInDb")(...args)) as typeof firebaseProvider.addUserToCompanyInDb

export const setCompanyUserInDb: typeof firebaseProvider.setCompanyUserInDb = ((...args: Parameters<typeof firebaseProvider.setCompanyUserInDb>) =>
  resolveImplementation("setCompanyUserInDb")(...args)) as typeof firebaseProvider.setCompanyUserInDb

export const createEmployeeJoinCodeInDb: typeof firebaseProvider.createEmployeeJoinCodeInDb = ((...args: Parameters<typeof firebaseProvider.createEmployeeJoinCodeInDb>) =>
  resolveImplementation("createEmployeeJoinCodeInDb")(...args)) as typeof firebaseProvider.createEmployeeJoinCodeInDb

export const getEmployeeJoinCodesFromDb: typeof firebaseProvider.getEmployeeJoinCodesFromDb = ((...args: Parameters<typeof firebaseProvider.getEmployeeJoinCodesFromDb>) =>
  resolveImplementation("getEmployeeJoinCodesFromDb")(...args)) as typeof firebaseProvider.getEmployeeJoinCodesFromDb

export const getEmployeeJoinCodeByCodeFromDb: typeof firebaseProvider.getEmployeeJoinCodeByCodeFromDb = ((...args: Parameters<typeof firebaseProvider.getEmployeeJoinCodeByCodeFromDb>) =>
  resolveImplementation("getEmployeeJoinCodeByCodeFromDb")(...args)) as typeof firebaseProvider.getEmployeeJoinCodeByCodeFromDb

export const revokeEmployeeJoinCodeInDb: typeof firebaseProvider.revokeEmployeeJoinCodeInDb = ((...args: Parameters<typeof firebaseProvider.revokeEmployeeJoinCodeInDb>) =>
  resolveImplementation("revokeEmployeeJoinCodeInDb")(...args)) as typeof firebaseProvider.revokeEmployeeJoinCodeInDb

export const getCompanyUsersFromDb: typeof firebaseProvider.getCompanyUsersFromDb = ((...args: Parameters<typeof firebaseProvider.getCompanyUsersFromDb>) =>
  resolveImplementation("getCompanyUsersFromDb")(...args)) as typeof firebaseProvider.getCompanyUsersFromDb

export const removeUserCompanyFromDb: typeof firebaseProvider.removeUserCompanyFromDb = ((...args: Parameters<typeof firebaseProvider.removeUserCompanyFromDb>) =>
  resolveImplementation("removeUserCompanyFromDb")(...args)) as typeof firebaseProvider.removeUserCompanyFromDb

export const removeCompanyUserFromDb: typeof firebaseProvider.removeCompanyUserFromDb = ((...args: Parameters<typeof firebaseProvider.removeCompanyUserFromDb>) =>
  resolveImplementation("removeCompanyUserFromDb")(...args)) as typeof firebaseProvider.removeCompanyUserFromDb

export const fetchChecklistSettings: typeof firebaseProvider.fetchChecklistSettings = ((...args: Parameters<typeof firebaseProvider.fetchChecklistSettings>) =>
  resolveImplementation("fetchChecklistSettings")(...args)) as typeof firebaseProvider.fetchChecklistSettings

export const fetchContractTemplates: typeof firebaseProvider.fetchContractTemplates = ((...args: Parameters<typeof firebaseProvider.fetchContractTemplates>) =>
  resolveImplementation("fetchContractTemplates")(...args)) as typeof firebaseProvider.fetchContractTemplates

export const saveContractTemplate: typeof firebaseProvider.saveContractTemplate = ((...args: Parameters<typeof firebaseProvider.saveContractTemplate>) =>
  resolveImplementation("saveContractTemplate")(...args)) as typeof firebaseProvider.saveContractTemplate

export const deleteContractTemplate: typeof firebaseProvider.deleteContractTemplate = ((...args: Parameters<typeof firebaseProvider.deleteContractTemplate>) =>
  resolveImplementation("deleteContractTemplate")(...args)) as typeof firebaseProvider.deleteContractTemplate

export const fetchContracts: typeof firebaseProvider.fetchContracts = ((...args: Parameters<typeof firebaseProvider.fetchContracts>) =>
  resolveImplementation("fetchContracts")(...args)) as typeof firebaseProvider.fetchContracts

export const saveContract: typeof firebaseProvider.saveContract = ((...args: Parameters<typeof firebaseProvider.saveContract>) =>
  resolveImplementation("saveContract")(...args)) as typeof firebaseProvider.saveContract

export const updateContractField: typeof firebaseProvider.updateContractField = ((...args: Parameters<typeof firebaseProvider.updateContractField>) =>
  resolveImplementation("updateContractField")(...args)) as typeof firebaseProvider.updateContractField

export const getUserCompaniesFromDb: typeof firebaseProvider.getUserCompaniesFromDb = ((...args: Parameters<typeof firebaseProvider.getUserCompaniesFromDb>) =>
  resolveImplementation("getUserCompaniesFromDb")(...args)) as typeof firebaseProvider.getUserCompaniesFromDb
