// Generated by scripts/generate-data-layer.cjs. Do not edit by hand.
import * as firebaseProvider from "../rtdatabase/Finance"
import * as supabaseProvider from "../providers/supabase/Finance"
import { getModuleProvider } from "./providerRegistry"

type ProviderModule = typeof firebaseProvider
type ProviderFn<T extends keyof ProviderModule> = ProviderModule[T] extends (...args: infer Args) => infer Result
  ? (...args: Args) => Result
  : never

const resolveImplementation = <T extends keyof ProviderModule>(name: T): ProviderFn<T> => {
  const provider = getModuleProvider("Finance")
  const source = provider === "supabase" ? (supabaseProvider as ProviderModule) : (firebaseProvider as ProviderModule)
  const implementation = source[name]
  if (typeof implementation !== "function") {
    throw new Error(`[data-provider] ${String(name)} is not implemented for provider "${provider}" in module "Finance".`)
  }
  return implementation as ProviderFn<T>
}

export const fetchFinanceSettings: typeof firebaseProvider.fetchFinanceSettings = ((...args: Parameters<typeof firebaseProvider.fetchFinanceSettings>) =>
  resolveImplementation("fetchFinanceSettings")(...args)) as typeof firebaseProvider.fetchFinanceSettings

export const saveFinanceSettings: typeof firebaseProvider.saveFinanceSettings = ((...args: Parameters<typeof firebaseProvider.saveFinanceSettings>) =>
  resolveImplementation("saveFinanceSettings")(...args)) as typeof firebaseProvider.saveFinanceSettings

export const fetchFinanceIntegrations: typeof firebaseProvider.fetchFinanceIntegrations = ((...args: Parameters<typeof firebaseProvider.fetchFinanceIntegrations>) =>
  resolveImplementation("fetchFinanceIntegrations")(...args)) as typeof firebaseProvider.fetchFinanceIntegrations

export const saveFinanceIntegration: typeof firebaseProvider.saveFinanceIntegration = ((...args: Parameters<typeof firebaseProvider.saveFinanceIntegration>) =>
  resolveImplementation("saveFinanceIntegration")(...args)) as typeof firebaseProvider.saveFinanceIntegration

export const fetchAccounts: typeof firebaseProvider.fetchAccounts = ((...args: Parameters<typeof firebaseProvider.fetchAccounts>) =>
  resolveImplementation("fetchAccounts")(...args)) as typeof firebaseProvider.fetchAccounts

export const createAccount: typeof firebaseProvider.createAccount = ((...args: Parameters<typeof firebaseProvider.createAccount>) =>
  resolveImplementation("createAccount")(...args)) as typeof firebaseProvider.createAccount

export const updateAccount: typeof firebaseProvider.updateAccount = ((...args: Parameters<typeof firebaseProvider.updateAccount>) =>
  resolveImplementation("updateAccount")(...args)) as typeof firebaseProvider.updateAccount

export const deleteAccount: typeof firebaseProvider.deleteAccount = ((...args: Parameters<typeof firebaseProvider.deleteAccount>) =>
  resolveImplementation("deleteAccount")(...args)) as typeof firebaseProvider.deleteAccount

export const fetchTransactions: typeof firebaseProvider.fetchTransactions = ((...args: Parameters<typeof firebaseProvider.fetchTransactions>) =>
  resolveImplementation("fetchTransactions")(...args)) as typeof firebaseProvider.fetchTransactions

export const createTransaction: typeof firebaseProvider.createTransaction = ((...args: Parameters<typeof firebaseProvider.createTransaction>) =>
  resolveImplementation("createTransaction")(...args)) as typeof firebaseProvider.createTransaction

export const fetchBills: typeof firebaseProvider.fetchBills = ((...args: Parameters<typeof firebaseProvider.fetchBills>) =>
  resolveImplementation("fetchBills")(...args)) as typeof firebaseProvider.fetchBills

export const createBill: typeof firebaseProvider.createBill = ((...args: Parameters<typeof firebaseProvider.createBill>) =>
  resolveImplementation("createBill")(...args)) as typeof firebaseProvider.createBill

export const fetchContacts: typeof firebaseProvider.fetchContacts = ((...args: Parameters<typeof firebaseProvider.fetchContacts>) =>
  resolveImplementation("fetchContacts")(...args)) as typeof firebaseProvider.fetchContacts

export const fetchBankAccounts: typeof firebaseProvider.fetchBankAccounts = ((...args: Parameters<typeof firebaseProvider.fetchBankAccounts>) =>
  resolveImplementation("fetchBankAccounts")(...args)) as typeof firebaseProvider.fetchBankAccounts

export const fetchBudgets: typeof firebaseProvider.fetchBudgets = ((...args: Parameters<typeof firebaseProvider.fetchBudgets>) =>
  resolveImplementation("fetchBudgets")(...args)) as typeof firebaseProvider.fetchBudgets

export const createBudget: typeof firebaseProvider.createBudget = ((...args: Parameters<typeof firebaseProvider.createBudget>) =>
  resolveImplementation("createBudget")(...args)) as typeof firebaseProvider.createBudget

export const updateBudget: typeof firebaseProvider.updateBudget = ((...args: Parameters<typeof firebaseProvider.updateBudget>) =>
  resolveImplementation("updateBudget")(...args)) as typeof firebaseProvider.updateBudget

export const deleteBudget: typeof firebaseProvider.deleteBudget = ((...args: Parameters<typeof firebaseProvider.deleteBudget>) =>
  resolveImplementation("deleteBudget")(...args)) as typeof firebaseProvider.deleteBudget

export const fetchDailyForecasts: typeof firebaseProvider.fetchDailyForecasts = ((...args: Parameters<typeof firebaseProvider.fetchDailyForecasts>) =>
  resolveImplementation("fetchDailyForecasts")(...args)) as typeof firebaseProvider.fetchDailyForecasts

export const upsertDailyForecast: typeof firebaseProvider.upsertDailyForecast = ((...args: Parameters<typeof firebaseProvider.upsertDailyForecast>) =>
  resolveImplementation("upsertDailyForecast")(...args)) as typeof firebaseProvider.upsertDailyForecast

export const deleteDailyForecast: typeof firebaseProvider.deleteDailyForecast = ((...args: Parameters<typeof firebaseProvider.deleteDailyForecast>) =>
  resolveImplementation("deleteDailyForecast")(...args)) as typeof firebaseProvider.deleteDailyForecast

export const fetchExpenses: typeof firebaseProvider.fetchExpenses = ((...args: Parameters<typeof firebaseProvider.fetchExpenses>) =>
  resolveImplementation("fetchExpenses")(...args)) as typeof firebaseProvider.fetchExpenses

export const createExpense: typeof firebaseProvider.createExpense = ((...args: Parameters<typeof firebaseProvider.createExpense>) =>
  resolveImplementation("createExpense")(...args)) as typeof firebaseProvider.createExpense

export const updateExpense: typeof firebaseProvider.updateExpense = ((...args: Parameters<typeof firebaseProvider.updateExpense>) =>
  resolveImplementation("updateExpense")(...args)) as typeof firebaseProvider.updateExpense

export const deleteExpense: typeof firebaseProvider.deleteExpense = ((...args: Parameters<typeof firebaseProvider.deleteExpense>) =>
  resolveImplementation("deleteExpense")(...args)) as typeof firebaseProvider.deleteExpense

export const fetchInvoices: typeof firebaseProvider.fetchInvoices = ((...args: Parameters<typeof firebaseProvider.fetchInvoices>) =>
  resolveImplementation("fetchInvoices")(...args)) as typeof firebaseProvider.fetchInvoices

export const fetchQuotes: typeof firebaseProvider.fetchQuotes = ((...args: Parameters<typeof firebaseProvider.fetchQuotes>) =>
  resolveImplementation("fetchQuotes")(...args)) as typeof firebaseProvider.fetchQuotes

export const createQuote: typeof firebaseProvider.createQuote = ((...args: Parameters<typeof firebaseProvider.createQuote>) =>
  resolveImplementation("createQuote")(...args)) as typeof firebaseProvider.createQuote

export const updateQuote: typeof firebaseProvider.updateQuote = ((...args: Parameters<typeof firebaseProvider.updateQuote>) =>
  resolveImplementation("updateQuote")(...args)) as typeof firebaseProvider.updateQuote

export const deleteQuote: typeof firebaseProvider.deleteQuote = ((...args: Parameters<typeof firebaseProvider.deleteQuote>) =>
  resolveImplementation("deleteQuote")(...args)) as typeof firebaseProvider.deleteQuote

export const createInvoice: typeof firebaseProvider.createInvoice = ((...args: Parameters<typeof firebaseProvider.createInvoice>) =>
  resolveImplementation("createInvoice")(...args)) as typeof firebaseProvider.createInvoice

export const updateInvoice: typeof firebaseProvider.updateInvoice = ((...args: Parameters<typeof firebaseProvider.updateInvoice>) =>
  resolveImplementation("updateInvoice")(...args)) as typeof firebaseProvider.updateInvoice

export const updateBill: typeof firebaseProvider.updateBill = ((...args: Parameters<typeof firebaseProvider.updateBill>) =>
  resolveImplementation("updateBill")(...args)) as typeof firebaseProvider.updateBill

export const deleteBill: typeof firebaseProvider.deleteBill = ((...args: Parameters<typeof firebaseProvider.deleteBill>) =>
  resolveImplementation("deleteBill")(...args)) as typeof firebaseProvider.deleteBill

export const createContact: typeof firebaseProvider.createContact = ((...args: Parameters<typeof firebaseProvider.createContact>) =>
  resolveImplementation("createContact")(...args)) as typeof firebaseProvider.createContact

export const updateContact: typeof firebaseProvider.updateContact = ((...args: Parameters<typeof firebaseProvider.updateContact>) =>
  resolveImplementation("updateContact")(...args)) as typeof firebaseProvider.updateContact

export const deleteContact: typeof firebaseProvider.deleteContact = ((...args: Parameters<typeof firebaseProvider.deleteContact>) =>
  resolveImplementation("deleteContact")(...args)) as typeof firebaseProvider.deleteContact

export const createBankAccount: typeof firebaseProvider.createBankAccount = ((...args: Parameters<typeof firebaseProvider.createBankAccount>) =>
  resolveImplementation("createBankAccount")(...args)) as typeof firebaseProvider.createBankAccount

export const updateBankAccount: typeof firebaseProvider.updateBankAccount = ((...args: Parameters<typeof firebaseProvider.updateBankAccount>) =>
  resolveImplementation("updateBankAccount")(...args)) as typeof firebaseProvider.updateBankAccount

export const deleteBankAccount: typeof firebaseProvider.deleteBankAccount = ((...args: Parameters<typeof firebaseProvider.deleteBankAccount>) =>
  resolveImplementation("deleteBankAccount")(...args)) as typeof firebaseProvider.deleteBankAccount

export const fetchBankStatements: typeof firebaseProvider.fetchBankStatements = ((...args: Parameters<typeof firebaseProvider.fetchBankStatements>) =>
  resolveImplementation("fetchBankStatements")(...args)) as typeof firebaseProvider.fetchBankStatements

export const createBankStatement: typeof firebaseProvider.createBankStatement = ((...args: Parameters<typeof firebaseProvider.createBankStatement>) =>
  resolveImplementation("createBankStatement")(...args)) as typeof firebaseProvider.createBankStatement

export const updateBankStatement: typeof firebaseProvider.updateBankStatement = ((...args: Parameters<typeof firebaseProvider.updateBankStatement>) =>
  resolveImplementation("updateBankStatement")(...args)) as typeof firebaseProvider.updateBankStatement

export const fetchBankRules: typeof firebaseProvider.fetchBankRules = ((...args: Parameters<typeof firebaseProvider.fetchBankRules>) =>
  resolveImplementation("fetchBankRules")(...args)) as typeof firebaseProvider.fetchBankRules

export const createBankRule: typeof firebaseProvider.createBankRule = ((...args: Parameters<typeof firebaseProvider.createBankRule>) =>
  resolveImplementation("createBankRule")(...args)) as typeof firebaseProvider.createBankRule

export const updateBankRule: typeof firebaseProvider.updateBankRule = ((...args: Parameters<typeof firebaseProvider.updateBankRule>) =>
  resolveImplementation("updateBankRule")(...args)) as typeof firebaseProvider.updateBankRule

export const deleteBankRule: typeof firebaseProvider.deleteBankRule = ((...args: Parameters<typeof firebaseProvider.deleteBankRule>) =>
  resolveImplementation("deleteBankRule")(...args)) as typeof firebaseProvider.deleteBankRule

export const fetchBankTransfers: typeof firebaseProvider.fetchBankTransfers = ((...args: Parameters<typeof firebaseProvider.fetchBankTransfers>) =>
  resolveImplementation("fetchBankTransfers")(...args)) as typeof firebaseProvider.fetchBankTransfers

export const createBankTransfer: typeof firebaseProvider.createBankTransfer = ((...args: Parameters<typeof firebaseProvider.createBankTransfer>) =>
  resolveImplementation("createBankTransfer")(...args)) as typeof firebaseProvider.createBankTransfer

export const updateBankTransfer: typeof firebaseProvider.updateBankTransfer = ((...args: Parameters<typeof firebaseProvider.updateBankTransfer>) =>
  resolveImplementation("updateBankTransfer")(...args)) as typeof firebaseProvider.updateBankTransfer

export const deleteBankTransfer: typeof firebaseProvider.deleteBankTransfer = ((...args: Parameters<typeof firebaseProvider.deleteBankTransfer>) =>
  resolveImplementation("deleteBankTransfer")(...args)) as typeof firebaseProvider.deleteBankTransfer

export const fetchClearingAccounts: typeof firebaseProvider.fetchClearingAccounts = ((...args: Parameters<typeof firebaseProvider.fetchClearingAccounts>) =>
  resolveImplementation("fetchClearingAccounts")(...args)) as typeof firebaseProvider.fetchClearingAccounts

export const createClearingAccount: typeof firebaseProvider.createClearingAccount = ((...args: Parameters<typeof firebaseProvider.createClearingAccount>) =>
  resolveImplementation("createClearingAccount")(...args)) as typeof firebaseProvider.createClearingAccount

export const updateClearingAccount: typeof firebaseProvider.updateClearingAccount = ((...args: Parameters<typeof firebaseProvider.updateClearingAccount>) =>
  resolveImplementation("updateClearingAccount")(...args)) as typeof firebaseProvider.updateClearingAccount

export const deleteClearingAccount: typeof firebaseProvider.deleteClearingAccount = ((...args: Parameters<typeof firebaseProvider.deleteClearingAccount>) =>
  resolveImplementation("deleteClearingAccount")(...args)) as typeof firebaseProvider.deleteClearingAccount

export const fetchFXRevaluations: typeof firebaseProvider.fetchFXRevaluations = ((...args: Parameters<typeof firebaseProvider.fetchFXRevaluations>) =>
  resolveImplementation("fetchFXRevaluations")(...args)) as typeof firebaseProvider.fetchFXRevaluations

export const createFXRevaluation: typeof firebaseProvider.createFXRevaluation = ((...args: Parameters<typeof firebaseProvider.createFXRevaluation>) =>
  resolveImplementation("createFXRevaluation")(...args)) as typeof firebaseProvider.createFXRevaluation

export const updateFXRevaluation: typeof firebaseProvider.updateFXRevaluation = ((...args: Parameters<typeof firebaseProvider.updateFXRevaluation>) =>
  resolveImplementation("updateFXRevaluation")(...args)) as typeof firebaseProvider.updateFXRevaluation

export const fetchJournals: typeof firebaseProvider.fetchJournals = ((...args: Parameters<typeof firebaseProvider.fetchJournals>) =>
  resolveImplementation("fetchJournals")(...args)) as typeof firebaseProvider.fetchJournals

export const createJournal: typeof firebaseProvider.createJournal = ((...args: Parameters<typeof firebaseProvider.createJournal>) =>
  resolveImplementation("createJournal")(...args)) as typeof firebaseProvider.createJournal

export const updateJournal: typeof firebaseProvider.updateJournal = ((...args: Parameters<typeof firebaseProvider.updateJournal>) =>
  resolveImplementation("updateJournal")(...args)) as typeof firebaseProvider.updateJournal

export const deleteJournal: typeof firebaseProvider.deleteJournal = ((...args: Parameters<typeof firebaseProvider.deleteJournal>) =>
  resolveImplementation("deleteJournal")(...args)) as typeof firebaseProvider.deleteJournal

export const approveJournal: typeof firebaseProvider.approveJournal = ((...args: Parameters<typeof firebaseProvider.approveJournal>) =>
  resolveImplementation("approveJournal")(...args)) as typeof firebaseProvider.approveJournal

export const postJournal: typeof firebaseProvider.postJournal = ((...args: Parameters<typeof firebaseProvider.postJournal>) =>
  resolveImplementation("postJournal")(...args)) as typeof firebaseProvider.postJournal

export const reverseJournal: typeof firebaseProvider.reverseJournal = ((...args: Parameters<typeof firebaseProvider.reverseJournal>) =>
  resolveImplementation("reverseJournal")(...args)) as typeof firebaseProvider.reverseJournal

export const fetchPeriodLocks: typeof firebaseProvider.fetchPeriodLocks = ((...args: Parameters<typeof firebaseProvider.fetchPeriodLocks>) =>
  resolveImplementation("fetchPeriodLocks")(...args)) as typeof firebaseProvider.fetchPeriodLocks

export const createPeriodLock: typeof firebaseProvider.createPeriodLock = ((...args: Parameters<typeof firebaseProvider.createPeriodLock>) =>
  resolveImplementation("createPeriodLock")(...args)) as typeof firebaseProvider.createPeriodLock

export const updatePeriodLock: typeof firebaseProvider.updatePeriodLock = ((...args: Parameters<typeof firebaseProvider.updatePeriodLock>) =>
  resolveImplementation("updatePeriodLock")(...args)) as typeof firebaseProvider.updatePeriodLock

export const deletePeriodLock: typeof firebaseProvider.deletePeriodLock = ((...args: Parameters<typeof firebaseProvider.deletePeriodLock>) =>
  resolveImplementation("deletePeriodLock")(...args)) as typeof firebaseProvider.deletePeriodLock

export const fetchDimensions: typeof firebaseProvider.fetchDimensions = ((...args: Parameters<typeof firebaseProvider.fetchDimensions>) =>
  resolveImplementation("fetchDimensions")(...args)) as typeof firebaseProvider.fetchDimensions

export const createDimension: typeof firebaseProvider.createDimension = ((...args: Parameters<typeof firebaseProvider.createDimension>) =>
  resolveImplementation("createDimension")(...args)) as typeof firebaseProvider.createDimension

export const updateDimension: typeof firebaseProvider.updateDimension = ((...args: Parameters<typeof firebaseProvider.updateDimension>) =>
  resolveImplementation("updateDimension")(...args)) as typeof firebaseProvider.updateDimension

export const deleteDimension: typeof firebaseProvider.deleteDimension = ((...args: Parameters<typeof firebaseProvider.deleteDimension>) =>
  resolveImplementation("deleteDimension")(...args)) as typeof firebaseProvider.deleteDimension

export const fetchReports: typeof firebaseProvider.fetchReports = ((...args: Parameters<typeof firebaseProvider.fetchReports>) =>
  resolveImplementation("fetchReports")(...args)) as typeof firebaseProvider.fetchReports

export const fetchCurrencies: typeof firebaseProvider.fetchCurrencies = ((...args: Parameters<typeof firebaseProvider.fetchCurrencies>) =>
  resolveImplementation("fetchCurrencies")(...args)) as typeof firebaseProvider.fetchCurrencies

export const createCurrency: typeof firebaseProvider.createCurrency = ((...args: Parameters<typeof firebaseProvider.createCurrency>) =>
  resolveImplementation("createCurrency")(...args)) as typeof firebaseProvider.createCurrency

export const updateCurrency: typeof firebaseProvider.updateCurrency = ((...args: Parameters<typeof firebaseProvider.updateCurrency>) =>
  resolveImplementation("updateCurrency")(...args)) as typeof firebaseProvider.updateCurrency

export const deleteCurrency: typeof firebaseProvider.deleteCurrency = ((...args: Parameters<typeof firebaseProvider.deleteCurrency>) =>
  resolveImplementation("deleteCurrency")(...args)) as typeof firebaseProvider.deleteCurrency

export const fetchExchangeRates: typeof firebaseProvider.fetchExchangeRates = ((...args: Parameters<typeof firebaseProvider.fetchExchangeRates>) =>
  resolveImplementation("fetchExchangeRates")(...args)) as typeof firebaseProvider.fetchExchangeRates

export const createExchangeRate: typeof firebaseProvider.createExchangeRate = ((...args: Parameters<typeof firebaseProvider.createExchangeRate>) =>
  resolveImplementation("createExchangeRate")(...args)) as typeof firebaseProvider.createExchangeRate

export const deleteExchangeRate: typeof firebaseProvider.deleteExchangeRate = ((...args: Parameters<typeof firebaseProvider.deleteExchangeRate>) =>
  resolveImplementation("deleteExchangeRate")(...args)) as typeof firebaseProvider.deleteExchangeRate

export const fetchPayments: typeof firebaseProvider.fetchPayments = ((...args: Parameters<typeof firebaseProvider.fetchPayments>) =>
  resolveImplementation("fetchPayments")(...args)) as typeof firebaseProvider.fetchPayments

export const createPayment: typeof firebaseProvider.createPayment = ((...args: Parameters<typeof firebaseProvider.createPayment>) =>
  resolveImplementation("createPayment")(...args)) as typeof firebaseProvider.createPayment

export const updatePayment: typeof firebaseProvider.updatePayment = ((...args: Parameters<typeof firebaseProvider.updatePayment>) =>
  resolveImplementation("updatePayment")(...args)) as typeof firebaseProvider.updatePayment

export const deletePayment: typeof firebaseProvider.deletePayment = ((...args: Parameters<typeof firebaseProvider.deletePayment>) =>
  resolveImplementation("deletePayment")(...args)) as typeof firebaseProvider.deletePayment

export const fetchCreditNotes: typeof firebaseProvider.fetchCreditNotes = ((...args: Parameters<typeof firebaseProvider.fetchCreditNotes>) =>
  resolveImplementation("fetchCreditNotes")(...args)) as typeof firebaseProvider.fetchCreditNotes

export const createCreditNote: typeof firebaseProvider.createCreditNote = ((...args: Parameters<typeof firebaseProvider.createCreditNote>) =>
  resolveImplementation("createCreditNote")(...args)) as typeof firebaseProvider.createCreditNote

export const updateCreditNote: typeof firebaseProvider.updateCreditNote = ((...args: Parameters<typeof firebaseProvider.updateCreditNote>) =>
  resolveImplementation("updateCreditNote")(...args)) as typeof firebaseProvider.updateCreditNote

export const deleteCreditNote: typeof firebaseProvider.deleteCreditNote = ((...args: Parameters<typeof firebaseProvider.deleteCreditNote>) =>
  resolveImplementation("deleteCreditNote")(...args)) as typeof firebaseProvider.deleteCreditNote

export const fetchPurchaseOrders: typeof firebaseProvider.fetchPurchaseOrders = ((...args: Parameters<typeof firebaseProvider.fetchPurchaseOrders>) =>
  resolveImplementation("fetchPurchaseOrders")(...args)) as typeof firebaseProvider.fetchPurchaseOrders

export const createPurchaseOrder: typeof firebaseProvider.createPurchaseOrder = ((...args: Parameters<typeof firebaseProvider.createPurchaseOrder>) =>
  resolveImplementation("createPurchaseOrder")(...args)) as typeof firebaseProvider.createPurchaseOrder

export const updatePurchaseOrder: typeof firebaseProvider.updatePurchaseOrder = ((...args: Parameters<typeof firebaseProvider.updatePurchaseOrder>) =>
  resolveImplementation("updatePurchaseOrder")(...args)) as typeof firebaseProvider.updatePurchaseOrder

export const deletePurchaseOrder: typeof firebaseProvider.deletePurchaseOrder = ((...args: Parameters<typeof firebaseProvider.deletePurchaseOrder>) =>
  resolveImplementation("deletePurchaseOrder")(...args)) as typeof firebaseProvider.deletePurchaseOrder

export const fetchTaxRates: typeof firebaseProvider.fetchTaxRates = ((...args: Parameters<typeof firebaseProvider.fetchTaxRates>) =>
  resolveImplementation("fetchTaxRates")(...args)) as typeof firebaseProvider.fetchTaxRates

export const createTaxRate: typeof firebaseProvider.createTaxRate = ((...args: Parameters<typeof firebaseProvider.createTaxRate>) =>
  resolveImplementation("createTaxRate")(...args)) as typeof firebaseProvider.createTaxRate

export const updateTaxRate: typeof firebaseProvider.updateTaxRate = ((...args: Parameters<typeof firebaseProvider.updateTaxRate>) =>
  resolveImplementation("updateTaxRate")(...args)) as typeof firebaseProvider.updateTaxRate

export const deleteTaxRate: typeof firebaseProvider.deleteTaxRate = ((...args: Parameters<typeof firebaseProvider.deleteTaxRate>) =>
  resolveImplementation("deleteTaxRate")(...args)) as typeof firebaseProvider.deleteTaxRate

export const fetchPaymentTerms: typeof firebaseProvider.fetchPaymentTerms = ((...args: Parameters<typeof firebaseProvider.fetchPaymentTerms>) =>
  resolveImplementation("fetchPaymentTerms")(...args)) as typeof firebaseProvider.fetchPaymentTerms

export const createPaymentTerm: typeof firebaseProvider.createPaymentTerm = ((...args: Parameters<typeof firebaseProvider.createPaymentTerm>) =>
  resolveImplementation("createPaymentTerm")(...args)) as typeof firebaseProvider.createPaymentTerm

export const fetchBankReconciliations: typeof firebaseProvider.fetchBankReconciliations = ((...args: Parameters<typeof firebaseProvider.fetchBankReconciliations>) =>
  resolveImplementation("fetchBankReconciliations")(...args)) as typeof firebaseProvider.fetchBankReconciliations

export const createBankReconciliation: typeof firebaseProvider.createBankReconciliation = ((...args: Parameters<typeof firebaseProvider.createBankReconciliation>) =>
  resolveImplementation("createBankReconciliation")(...args)) as typeof firebaseProvider.createBankReconciliation

export const updateBankReconciliation: typeof firebaseProvider.updateBankReconciliation = ((...args: Parameters<typeof firebaseProvider.updateBankReconciliation>) =>
  resolveImplementation("updateBankReconciliation")(...args)) as typeof firebaseProvider.updateBankReconciliation

export const fetchJournalEntries: typeof firebaseProvider.fetchJournalEntries = ((...args: Parameters<typeof firebaseProvider.fetchJournalEntries>) =>
  resolveImplementation("fetchJournalEntries")(...args)) as typeof firebaseProvider.fetchJournalEntries

export const createJournalEntry: typeof firebaseProvider.createJournalEntry = ((...args: Parameters<typeof firebaseProvider.createJournalEntry>) =>
  resolveImplementation("createJournalEntry")(...args)) as typeof firebaseProvider.createJournalEntry

export const updateJournalEntry: typeof firebaseProvider.updateJournalEntry = ((...args: Parameters<typeof firebaseProvider.updateJournalEntry>) =>
  resolveImplementation("updateJournalEntry")(...args)) as typeof firebaseProvider.updateJournalEntry

export const deleteJournalEntry: typeof firebaseProvider.deleteJournalEntry = ((...args: Parameters<typeof firebaseProvider.deleteJournalEntry>) =>
  resolveImplementation("deleteJournalEntry")(...args)) as typeof firebaseProvider.deleteJournalEntry

export const saveReport: typeof firebaseProvider.saveReport = ((...args: Parameters<typeof firebaseProvider.saveReport>) =>
  resolveImplementation("saveReport")(...args)) as typeof firebaseProvider.saveReport

export const deleteReport: typeof firebaseProvider.deleteReport = ((...args: Parameters<typeof firebaseProvider.deleteReport>) =>
  resolveImplementation("deleteReport")(...args)) as typeof firebaseProvider.deleteReport

export const deleteInvoice: typeof firebaseProvider.deleteInvoice = ((...args: Parameters<typeof firebaseProvider.deleteInvoice>) =>
  resolveImplementation("deleteInvoice")(...args)) as typeof firebaseProvider.deleteInvoice

export const fetchOpeningBalances: typeof firebaseProvider.fetchOpeningBalances = ((...args: Parameters<typeof firebaseProvider.fetchOpeningBalances>) =>
  resolveImplementation("fetchOpeningBalances")(...args)) as typeof firebaseProvider.fetchOpeningBalances

export const createOpeningBalance: typeof firebaseProvider.createOpeningBalance = ((...args: Parameters<typeof firebaseProvider.createOpeningBalance>) =>
  resolveImplementation("createOpeningBalance")(...args)) as typeof firebaseProvider.createOpeningBalance

export const updateOpeningBalance: typeof firebaseProvider.updateOpeningBalance = ((...args: Parameters<typeof firebaseProvider.updateOpeningBalance>) =>
  resolveImplementation("updateOpeningBalance")(...args)) as typeof firebaseProvider.updateOpeningBalance

export const deleteOpeningBalance: typeof firebaseProvider.deleteOpeningBalance = ((...args: Parameters<typeof firebaseProvider.deleteOpeningBalance>) =>
  resolveImplementation("deleteOpeningBalance")(...args)) as typeof firebaseProvider.deleteOpeningBalance
