// Generated by scripts/generate-data-layer.cjs. Do not edit by hand.
import * as firebaseProvider from "../rtdatabase/HRs"
import * as supabaseProvider from "../providers/supabase/HRs"
import { getModuleProvider } from "./providerRegistry"

type ProviderModule = typeof firebaseProvider
type ProviderFn<T extends keyof ProviderModule> = ProviderModule[T] extends (...args: infer Args) => infer Result
  ? (...args: Args) => Result
  : never

const resolveImplementation = <T extends keyof ProviderModule>(name: T): ProviderFn<T> => {
  const provider = getModuleProvider("HRs")
  const source = provider === "supabase" ? (supabaseProvider as ProviderModule) : (firebaseProvider as ProviderModule)
  const implementation = source[name]
  if (typeof implementation !== "function") {
    throw new Error(`[data-provider] ${String(name)} is not implemented for provider "${provider}" in module "HRs".`)
  }
  return implementation as ProviderFn<T>
}

export const fetchServiceChargeRules: typeof firebaseProvider.fetchServiceChargeRules = ((...args: Parameters<typeof firebaseProvider.fetchServiceChargeRules>) =>
  resolveImplementation("fetchServiceChargeRules")(...args)) as typeof firebaseProvider.fetchServiceChargeRules

export const saveServiceChargeRules: typeof firebaseProvider.saveServiceChargeRules = ((...args: Parameters<typeof firebaseProvider.saveServiceChargeRules>) =>
  resolveImplementation("saveServiceChargeRules")(...args)) as typeof firebaseProvider.saveServiceChargeRules

export const fetchPosBills: typeof firebaseProvider.fetchPosBills = ((...args: Parameters<typeof firebaseProvider.fetchPosBills>) =>
  resolveImplementation("fetchPosBills")(...args)) as typeof firebaseProvider.fetchPosBills

export const saveServiceChargeAllocation: typeof firebaseProvider.saveServiceChargeAllocation = ((...args: Parameters<typeof firebaseProvider.saveServiceChargeAllocation>) =>
  resolveImplementation("saveServiceChargeAllocation")(...args)) as typeof firebaseProvider.saveServiceChargeAllocation

export const saveServiceChargeEmployeeAllocation: typeof firebaseProvider.saveServiceChargeEmployeeAllocation = ((...args: Parameters<typeof firebaseProvider.saveServiceChargeEmployeeAllocation>) =>
  resolveImplementation("saveServiceChargeEmployeeAllocation")(...args)) as typeof firebaseProvider.saveServiceChargeEmployeeAllocation

export const fetchHrEmailConfig: typeof firebaseProvider.fetchHrEmailConfig = ((...args: Parameters<typeof firebaseProvider.fetchHrEmailConfig>) =>
  resolveImplementation("fetchHrEmailConfig")(...args)) as typeof firebaseProvider.fetchHrEmailConfig

export const saveHrEmailConfig: typeof firebaseProvider.saveHrEmailConfig = ((...args: Parameters<typeof firebaseProvider.saveHrEmailConfig>) =>
  resolveImplementation("saveHrEmailConfig")(...args)) as typeof firebaseProvider.saveHrEmailConfig

export const fetchHRCollection: typeof firebaseProvider.fetchHRCollection = ((...args: Parameters<typeof firebaseProvider.fetchHRCollection>) =>
  resolveImplementation("fetchHRCollection")(...args)) as typeof firebaseProvider.fetchHRCollection

export const fetchHRSettingsSection: typeof firebaseProvider.fetchHRSettingsSection = ((...args: Parameters<typeof firebaseProvider.fetchHRSettingsSection>) =>
  resolveImplementation("fetchHRSettingsSection")(...args)) as typeof firebaseProvider.fetchHRSettingsSection

export const saveHRSettingsSection: typeof firebaseProvider.saveHRSettingsSection = ((...args: Parameters<typeof firebaseProvider.saveHRSettingsSection>) =>
  resolveImplementation("saveHRSettingsSection")(...args)) as typeof firebaseProvider.saveHRSettingsSection

export const fetchHRIntegrations: typeof firebaseProvider.fetchHRIntegrations = ((...args: Parameters<typeof firebaseProvider.fetchHRIntegrations>) =>
  resolveImplementation("fetchHRIntegrations")(...args)) as typeof firebaseProvider.fetchHRIntegrations

export const saveHRIntegration: typeof firebaseProvider.saveHRIntegration = ((...args: Parameters<typeof firebaseProvider.saveHRIntegration>) =>
  resolveImplementation("saveHRIntegration")(...args)) as typeof firebaseProvider.saveHRIntegration

export const fetchHREmployeeDefaults: typeof firebaseProvider.fetchHREmployeeDefaults = ((...args: Parameters<typeof firebaseProvider.fetchHREmployeeDefaults>) =>
  resolveImplementation("fetchHREmployeeDefaults")(...args)) as typeof firebaseProvider.fetchHREmployeeDefaults

export const saveHREmployeeDefaults: typeof firebaseProvider.saveHREmployeeDefaults = ((...args: Parameters<typeof firebaseProvider.saveHREmployeeDefaults>) =>
  resolveImplementation("saveHREmployeeDefaults")(...args)) as typeof firebaseProvider.saveHREmployeeDefaults

export const fetchHRPayrollSettings: typeof firebaseProvider.fetchHRPayrollSettings = ((...args: Parameters<typeof firebaseProvider.fetchHRPayrollSettings>) =>
  resolveImplementation("fetchHRPayrollSettings")(...args)) as typeof firebaseProvider.fetchHRPayrollSettings

export const saveHRPayrollSettings: typeof firebaseProvider.saveHRPayrollSettings = ((...args: Parameters<typeof firebaseProvider.saveHRPayrollSettings>) =>
  resolveImplementation("saveHRPayrollSettings")(...args)) as typeof firebaseProvider.saveHRPayrollSettings

export const findHRSchedulePath: typeof firebaseProvider.findHRSchedulePath = ((...args: Parameters<typeof firebaseProvider.findHRSchedulePath>) =>
  resolveImplementation("findHRSchedulePath")(...args)) as typeof firebaseProvider.findHRSchedulePath

export const findHRReadPath: typeof firebaseProvider.findHRReadPath = ((...args: Parameters<typeof firebaseProvider.findHRReadPath>) =>
  resolveImplementation("findHRReadPath")(...args)) as typeof firebaseProvider.findHRReadPath

export const useHRData: typeof firebaseProvider.useHRData = ((...args: Parameters<typeof firebaseProvider.useHRData>) =>
  resolveImplementation("useHRData")(...args)) as typeof firebaseProvider.useHRData

export const updateHRAnalytics: typeof firebaseProvider.updateHRAnalytics = ((...args: Parameters<typeof firebaseProvider.updateHRAnalytics>) =>
  resolveImplementation("updateHRAnalytics")(...args)) as typeof firebaseProvider.updateHRAnalytics

export const fetchTrainings: typeof firebaseProvider.fetchTrainings = ((...args: Parameters<typeof firebaseProvider.fetchTrainings>) =>
  resolveImplementation("fetchTrainings")(...args)) as typeof firebaseProvider.fetchTrainings

export const createTraining: typeof firebaseProvider.createTraining = ((...args: Parameters<typeof firebaseProvider.createTraining>) =>
  resolveImplementation("createTraining")(...args)) as typeof firebaseProvider.createTraining

export const updateTraining: typeof firebaseProvider.updateTraining = ((...args: Parameters<typeof firebaseProvider.updateTraining>) =>
  resolveImplementation("updateTraining")(...args)) as typeof firebaseProvider.updateTraining

export const deleteTraining: typeof firebaseProvider.deleteTraining = ((...args: Parameters<typeof firebaseProvider.deleteTraining>) =>
  resolveImplementation("deleteTraining")(...args)) as typeof firebaseProvider.deleteTraining

export const fetchTimeOffs: typeof firebaseProvider.fetchTimeOffs = ((...args: Parameters<typeof firebaseProvider.fetchTimeOffs>) =>
  resolveImplementation("fetchTimeOffs")(...args)) as typeof firebaseProvider.fetchTimeOffs

export const createTimeOff: typeof firebaseProvider.createTimeOff = ((...args: Parameters<typeof firebaseProvider.createTimeOff>) =>
  resolveImplementation("createTimeOff")(...args)) as typeof firebaseProvider.createTimeOff

export const updateTimeOff: typeof firebaseProvider.updateTimeOff = ((...args: Parameters<typeof firebaseProvider.updateTimeOff>) =>
  resolveImplementation("updateTimeOff")(...args)) as typeof firebaseProvider.updateTimeOff

export const deleteTimeOff: typeof firebaseProvider.deleteTimeOff = ((...args: Parameters<typeof firebaseProvider.deleteTimeOff>) =>
  resolveImplementation("deleteTimeOff")(...args)) as typeof firebaseProvider.deleteTimeOff

export const fetchWarnings: typeof firebaseProvider.fetchWarnings = ((...args: Parameters<typeof firebaseProvider.fetchWarnings>) =>
  resolveImplementation("fetchWarnings")(...args)) as typeof firebaseProvider.fetchWarnings

export const createWarning: typeof firebaseProvider.createWarning = ((...args: Parameters<typeof firebaseProvider.createWarning>) =>
  resolveImplementation("createWarning")(...args)) as typeof firebaseProvider.createWarning

export const updateWarning: typeof firebaseProvider.updateWarning = ((...args: Parameters<typeof firebaseProvider.updateWarning>) =>
  resolveImplementation("updateWarning")(...args)) as typeof firebaseProvider.updateWarning

export const deleteWarning: typeof firebaseProvider.deleteWarning = ((...args: Parameters<typeof firebaseProvider.deleteWarning>) =>
  resolveImplementation("deleteWarning")(...args)) as typeof firebaseProvider.deleteWarning

export const fetchAttendances: typeof firebaseProvider.fetchAttendances = ((...args: Parameters<typeof firebaseProvider.fetchAttendances>) =>
  resolveImplementation("fetchAttendances")(...args)) as typeof firebaseProvider.fetchAttendances

export const createAttendance: typeof firebaseProvider.createAttendance = ((...args: Parameters<typeof firebaseProvider.createAttendance>) =>
  resolveImplementation("createAttendance")(...args)) as typeof firebaseProvider.createAttendance

export const updateAttendance: typeof firebaseProvider.updateAttendance = ((...args: Parameters<typeof firebaseProvider.updateAttendance>) =>
  resolveImplementation("updateAttendance")(...args)) as typeof firebaseProvider.updateAttendance

export const deleteAttendance: typeof firebaseProvider.deleteAttendance = ((...args: Parameters<typeof firebaseProvider.deleteAttendance>) =>
  resolveImplementation("deleteAttendance")(...args)) as typeof firebaseProvider.deleteAttendance

export const fetchJobs: typeof firebaseProvider.fetchJobs = ((...args: Parameters<typeof firebaseProvider.fetchJobs>) =>
  resolveImplementation("fetchJobs")(...args)) as typeof firebaseProvider.fetchJobs

export const createJob: typeof firebaseProvider.createJob = ((...args: Parameters<typeof firebaseProvider.createJob>) =>
  resolveImplementation("createJob")(...args)) as typeof firebaseProvider.createJob

export const updateJob: typeof firebaseProvider.updateJob = ((...args: Parameters<typeof firebaseProvider.updateJob>) =>
  resolveImplementation("updateJob")(...args)) as typeof firebaseProvider.updateJob

export const deleteJob: typeof firebaseProvider.deleteJob = ((...args: Parameters<typeof firebaseProvider.deleteJob>) =>
  resolveImplementation("deleteJob")(...args)) as typeof firebaseProvider.deleteJob

export const fetchCandidates: typeof firebaseProvider.fetchCandidates = ((...args: Parameters<typeof firebaseProvider.fetchCandidates>) =>
  resolveImplementation("fetchCandidates")(...args)) as typeof firebaseProvider.fetchCandidates

export const createCandidate: typeof firebaseProvider.createCandidate = ((...args: Parameters<typeof firebaseProvider.createCandidate>) =>
  resolveImplementation("createCandidate")(...args)) as typeof firebaseProvider.createCandidate

export const updateCandidate: typeof firebaseProvider.updateCandidate = ((...args: Parameters<typeof firebaseProvider.updateCandidate>) =>
  resolveImplementation("updateCandidate")(...args)) as typeof firebaseProvider.updateCandidate

export const deleteCandidate: typeof firebaseProvider.deleteCandidate = ((...args: Parameters<typeof firebaseProvider.deleteCandidate>) =>
  resolveImplementation("deleteCandidate")(...args)) as typeof firebaseProvider.deleteCandidate

export const createInterview: typeof firebaseProvider.createInterview = ((...args: Parameters<typeof firebaseProvider.createInterview>) =>
  resolveImplementation("createInterview")(...args)) as typeof firebaseProvider.createInterview

export const updateInterview: typeof firebaseProvider.updateInterview = ((...args: Parameters<typeof firebaseProvider.updateInterview>) =>
  resolveImplementation("updateInterview")(...args)) as typeof firebaseProvider.updateInterview

export const deleteInterview: typeof firebaseProvider.deleteInterview = ((...args: Parameters<typeof firebaseProvider.deleteInterview>) =>
  resolveImplementation("deleteInterview")(...args)) as typeof firebaseProvider.deleteInterview

export const fetchInterviews: typeof firebaseProvider.fetchInterviews = ((...args: Parameters<typeof firebaseProvider.fetchInterviews>) =>
  resolveImplementation("fetchInterviews")(...args)) as typeof firebaseProvider.fetchInterviews

export const fetchContracts: typeof firebaseProvider.fetchContracts = ((...args: Parameters<typeof firebaseProvider.fetchContracts>) =>
  resolveImplementation("fetchContracts")(...args)) as typeof firebaseProvider.fetchContracts

export const updateContract: typeof firebaseProvider.updateContract = ((...args: Parameters<typeof firebaseProvider.updateContract>) =>
  resolveImplementation("updateContract")(...args)) as typeof firebaseProvider.updateContract

export const fetchContractTemplates: typeof firebaseProvider.fetchContractTemplates = ((...args: Parameters<typeof firebaseProvider.fetchContractTemplates>) =>
  resolveImplementation("fetchContractTemplates")(...args)) as typeof firebaseProvider.fetchContractTemplates

export const createContract: typeof firebaseProvider.createContract = ((...args: Parameters<typeof firebaseProvider.createContract>) =>
  resolveImplementation("createContract")(...args)) as typeof firebaseProvider.createContract

export const createContractTemplate: typeof firebaseProvider.createContractTemplate = ((...args: Parameters<typeof firebaseProvider.createContractTemplate>) =>
  resolveImplementation("createContractTemplate")(...args)) as typeof firebaseProvider.createContractTemplate

export const updateContractTemplate: typeof firebaseProvider.updateContractTemplate = ((...args: Parameters<typeof firebaseProvider.updateContractTemplate>) =>
  resolveImplementation("updateContractTemplate")(...args)) as typeof firebaseProvider.updateContractTemplate

export const deleteContract: typeof firebaseProvider.deleteContract = ((...args: Parameters<typeof firebaseProvider.deleteContract>) =>
  resolveImplementation("deleteContract")(...args)) as typeof firebaseProvider.deleteContract

export const deleteContractTemplate: typeof firebaseProvider.deleteContractTemplate = ((...args: Parameters<typeof firebaseProvider.deleteContractTemplate>) =>
  resolveImplementation("deleteContractTemplate")(...args)) as typeof firebaseProvider.deleteContractTemplate

export const fetchAnnouncements: typeof firebaseProvider.fetchAnnouncements = ((...args: Parameters<typeof firebaseProvider.fetchAnnouncements>) =>
  resolveImplementation("fetchAnnouncements")(...args)) as typeof firebaseProvider.fetchAnnouncements

export const createAnnouncement: typeof firebaseProvider.createAnnouncement = ((...args: Parameters<typeof firebaseProvider.createAnnouncement>) =>
  resolveImplementation("createAnnouncement")(...args)) as typeof firebaseProvider.createAnnouncement

export const updateAnnouncement: typeof firebaseProvider.updateAnnouncement = ((...args: Parameters<typeof firebaseProvider.updateAnnouncement>) =>
  resolveImplementation("updateAnnouncement")(...args)) as typeof firebaseProvider.updateAnnouncement

export const deleteAnnouncement: typeof firebaseProvider.deleteAnnouncement = ((...args: Parameters<typeof firebaseProvider.deleteAnnouncement>) =>
  resolveImplementation("deleteAnnouncement")(...args)) as typeof firebaseProvider.deleteAnnouncement

export const fetchBenefits: typeof firebaseProvider.fetchBenefits = ((...args: Parameters<typeof firebaseProvider.fetchBenefits>) =>
  resolveImplementation("fetchBenefits")(...args)) as typeof firebaseProvider.fetchBenefits

export const fetchEmployees: typeof firebaseProvider.fetchEmployees = ((...args: Parameters<typeof firebaseProvider.fetchEmployees>) =>
  resolveImplementation("fetchEmployees")(...args)) as typeof firebaseProvider.fetchEmployees

export const createEmployee: typeof firebaseProvider.createEmployee = ((...args: Parameters<typeof firebaseProvider.createEmployee>) =>
  resolveImplementation("createEmployee")(...args)) as typeof firebaseProvider.createEmployee

export const updateEmployee: typeof firebaseProvider.updateEmployee = ((...args: Parameters<typeof firebaseProvider.updateEmployee>) =>
  resolveImplementation("updateEmployee")(...args)) as typeof firebaseProvider.updateEmployee

export const deleteEmployee: typeof firebaseProvider.deleteEmployee = ((...args: Parameters<typeof firebaseProvider.deleteEmployee>) =>
  resolveImplementation("deleteEmployee")(...args)) as typeof firebaseProvider.deleteEmployee

export const fetchRoles: typeof firebaseProvider.fetchRoles = ((...args: Parameters<typeof firebaseProvider.fetchRoles>) =>
  resolveImplementation("fetchRoles")(...args)) as typeof firebaseProvider.fetchRoles

export const fetchDepartments: typeof firebaseProvider.fetchDepartments = ((...args: Parameters<typeof firebaseProvider.fetchDepartments>) =>
  resolveImplementation("fetchDepartments")(...args)) as typeof firebaseProvider.fetchDepartments

export const fetchSchedules: typeof firebaseProvider.fetchSchedules = ((...args: Parameters<typeof firebaseProvider.fetchSchedules>) =>
  resolveImplementation("fetchSchedules")(...args)) as typeof firebaseProvider.fetchSchedules

export const createSchedule: typeof firebaseProvider.createSchedule = ((...args: Parameters<typeof firebaseProvider.createSchedule>) =>
  resolveImplementation("createSchedule")(...args)) as typeof firebaseProvider.createSchedule

export const updateSchedule: typeof firebaseProvider.updateSchedule = ((...args: Parameters<typeof firebaseProvider.updateSchedule>) =>
  resolveImplementation("updateSchedule")(...args)) as typeof firebaseProvider.updateSchedule

export const deleteSchedule: typeof firebaseProvider.deleteSchedule = ((...args: Parameters<typeof firebaseProvider.deleteSchedule>) =>
  resolveImplementation("deleteSchedule")(...args)) as typeof firebaseProvider.deleteSchedule

export const handleHRActionDB: typeof firebaseProvider.handleHRActionDB = ((...args: Parameters<typeof firebaseProvider.handleHRActionDB>) =>
  resolveImplementation("handleHRActionDB")(...args)) as typeof firebaseProvider.handleHRActionDB

export const createRole: typeof firebaseProvider.createRole = ((...args: Parameters<typeof firebaseProvider.createRole>) =>
  resolveImplementation("createRole")(...args)) as typeof firebaseProvider.createRole

export const updateRole: typeof firebaseProvider.updateRole = ((...args: Parameters<typeof firebaseProvider.updateRole>) =>
  resolveImplementation("updateRole")(...args)) as typeof firebaseProvider.updateRole

export const deleteRole: typeof firebaseProvider.deleteRole = ((...args: Parameters<typeof firebaseProvider.deleteRole>) =>
  resolveImplementation("deleteRole")(...args)) as typeof firebaseProvider.deleteRole

export const createDepartment: typeof firebaseProvider.createDepartment = ((...args: Parameters<typeof firebaseProvider.createDepartment>) =>
  resolveImplementation("createDepartment")(...args)) as typeof firebaseProvider.createDepartment

export const updateDepartment: typeof firebaseProvider.updateDepartment = ((...args: Parameters<typeof firebaseProvider.updateDepartment>) =>
  resolveImplementation("updateDepartment")(...args)) as typeof firebaseProvider.updateDepartment

export const deleteDepartment: typeof firebaseProvider.deleteDepartment = ((...args: Parameters<typeof firebaseProvider.deleteDepartment>) =>
  resolveImplementation("deleteDepartment")(...args)) as typeof firebaseProvider.deleteDepartment

export const fetchPayroll: typeof firebaseProvider.fetchPayroll = ((...args: Parameters<typeof firebaseProvider.fetchPayroll>) =>
  resolveImplementation("fetchPayroll")(...args)) as typeof firebaseProvider.fetchPayroll

export const fetchPerformanceReviews: typeof firebaseProvider.fetchPerformanceReviews = ((...args: Parameters<typeof firebaseProvider.fetchPerformanceReviews>) =>
  resolveImplementation("fetchPerformanceReviews")(...args)) as typeof firebaseProvider.fetchPerformanceReviews
