// Generated by scripts/generate-data-layer.cjs. Do not edit by hand.
import * as firebaseProvider from "../rtdatabase/Location"
import * as supabaseProvider from "../providers/supabase/Location"
import { getModuleProvider } from "./providerRegistry"

type ProviderModule = typeof firebaseProvider
type ProviderFn<T extends keyof ProviderModule> = ProviderModule[T] extends (...args: infer Args) => infer Result
  ? (...args: Args) => Result
  : never

const resolveImplementation = <T extends keyof ProviderModule>(name: T): ProviderFn<T> => {
  const provider = getModuleProvider("Location")
  const source = provider === "supabase" ? (supabaseProvider as ProviderModule) : (firebaseProvider as ProviderModule)
  const implementation = source[name]
  if (typeof implementation !== "function") {
    throw new Error(`[data-provider] ${String(name)} is not implemented for provider "${provider}" in module "Location".`)
  }
  return implementation as ProviderFn<T>
}

export const fetchLocations: typeof firebaseProvider.fetchLocations = ((...args: Parameters<typeof firebaseProvider.fetchLocations>) =>
  resolveImplementation("fetchLocations")(...args)) as typeof firebaseProvider.fetchLocations

export const createLocation: typeof firebaseProvider.createLocation = ((...args: Parameters<typeof firebaseProvider.createLocation>) =>
  resolveImplementation("createLocation")(...args)) as typeof firebaseProvider.createLocation

export const updateLocation: typeof firebaseProvider.updateLocation = ((...args: Parameters<typeof firebaseProvider.updateLocation>) =>
  resolveImplementation("updateLocation")(...args)) as typeof firebaseProvider.updateLocation

export const deleteLocation: typeof firebaseProvider.deleteLocation = ((...args: Parameters<typeof firebaseProvider.deleteLocation>) =>
  resolveImplementation("deleteLocation")(...args)) as typeof firebaseProvider.deleteLocation

export const getLocationsByType: typeof firebaseProvider.getLocationsByType = ((...args: Parameters<typeof firebaseProvider.getLocationsByType>) =>
  resolveImplementation("getLocationsByType")(...args)) as typeof firebaseProvider.getLocationsByType

export const getActiveLocations: typeof firebaseProvider.getActiveLocations = ((...args: Parameters<typeof firebaseProvider.getActiveLocations>) =>
  resolveImplementation("getActiveLocations")(...args)) as typeof firebaseProvider.getActiveLocations

export const searchLocations: typeof firebaseProvider.searchLocations = ((...args: Parameters<typeof firebaseProvider.searchLocations>) =>
  resolveImplementation("searchLocations")(...args)) as typeof firebaseProvider.searchLocations
