// Generated by scripts/generate-data-layer.cjs. Do not edit by hand.
import * as firebaseProvider from "../rtdatabase/Messenger"
import * as supabaseProvider from "../providers/supabase/Messenger"
import { getModuleProvider } from "./providerRegistry"

type ProviderModule = typeof firebaseProvider
type ProviderFn<T extends keyof ProviderModule> = ProviderModule[T] extends (...args: infer Args) => infer Result
  ? (...args: Args) => Result
  : never

const resolveImplementation = <T extends keyof ProviderModule>(name: T): ProviderFn<T> => {
  const provider = getModuleProvider("Messenger")
  const source = provider === "supabase" ? (supabaseProvider as ProviderModule) : (firebaseProvider as ProviderModule)
  const implementation = source[name]
  if (typeof implementation !== "function") {
    throw new Error(`[data-provider] ${String(name)} is not implemented for provider "${provider}" in module "Messenger".`)
  }
  return implementation as ProviderFn<T>
}

export const createChat: typeof firebaseProvider.createChat = ((...args: Parameters<typeof firebaseProvider.createChat>) =>
  resolveImplementation("createChat")(...args)) as typeof firebaseProvider.createChat

export const getChat: typeof firebaseProvider.getChat = ((...args: Parameters<typeof firebaseProvider.getChat>) =>
  resolveImplementation("getChat")(...args)) as typeof firebaseProvider.getChat

export const getUserChats: typeof firebaseProvider.getUserChats = ((...args: Parameters<typeof firebaseProvider.getUserChats>) =>
  resolveImplementation("getUserChats")(...args)) as typeof firebaseProvider.getUserChats

export const getCompanyChats: typeof firebaseProvider.getCompanyChats = ((...args: Parameters<typeof firebaseProvider.getCompanyChats>) =>
  resolveImplementation("getCompanyChats")(...args)) as typeof firebaseProvider.getCompanyChats

export const getSiteChats: typeof firebaseProvider.getSiteChats = ((...args: Parameters<typeof firebaseProvider.getSiteChats>) =>
  resolveImplementation("getSiteChats")(...args)) as typeof firebaseProvider.getSiteChats

export const getDepartmentChats: typeof firebaseProvider.getDepartmentChats = ((...args: Parameters<typeof firebaseProvider.getDepartmentChats>) =>
  resolveImplementation("getDepartmentChats")(...args)) as typeof firebaseProvider.getDepartmentChats

export const getRoleChats: typeof firebaseProvider.getRoleChats = ((...args: Parameters<typeof firebaseProvider.getRoleChats>) =>
  resolveImplementation("getRoleChats")(...args)) as typeof firebaseProvider.getRoleChats

export const updateChat: typeof firebaseProvider.updateChat = ((...args: Parameters<typeof firebaseProvider.updateChat>) =>
  resolveImplementation("updateChat")(...args)) as typeof firebaseProvider.updateChat

export const deleteChat: typeof firebaseProvider.deleteChat = ((...args: Parameters<typeof firebaseProvider.deleteChat>) =>
  resolveImplementation("deleteChat")(...args)) as typeof firebaseProvider.deleteChat

export const sendMessage: typeof firebaseProvider.sendMessage = ((...args: Parameters<typeof firebaseProvider.sendMessage>) =>
  resolveImplementation("sendMessage")(...args)) as typeof firebaseProvider.sendMessage

export const getMessages: typeof firebaseProvider.getMessages = ((...args: Parameters<typeof firebaseProvider.getMessages>) =>
  resolveImplementation("getMessages")(...args)) as typeof firebaseProvider.getMessages

export const subscribeToMessages: typeof firebaseProvider.subscribeToMessages = ((...args: Parameters<typeof firebaseProvider.subscribeToMessages>) =>
  resolveImplementation("subscribeToMessages")(...args)) as typeof firebaseProvider.subscribeToMessages

export const markMessageAsRead: typeof firebaseProvider.markMessageAsRead = ((...args: Parameters<typeof firebaseProvider.markMessageAsRead>) =>
  resolveImplementation("markMessageAsRead")(...args)) as typeof firebaseProvider.markMessageAsRead

export const addReactionToMessage: typeof firebaseProvider.addReactionToMessage = ((...args: Parameters<typeof firebaseProvider.addReactionToMessage>) =>
  resolveImplementation("addReactionToMessage")(...args)) as typeof firebaseProvider.addReactionToMessage

export const removeReactionFromMessage: typeof firebaseProvider.removeReactionFromMessage = ((...args: Parameters<typeof firebaseProvider.removeReactionFromMessage>) =>
  resolveImplementation("removeReactionFromMessage")(...args)) as typeof firebaseProvider.removeReactionFromMessage

export const editMessage: typeof firebaseProvider.editMessage = ((...args: Parameters<typeof firebaseProvider.editMessage>) =>
  resolveImplementation("editMessage")(...args)) as typeof firebaseProvider.editMessage

export const deleteMessage: typeof firebaseProvider.deleteMessage = ((...args: Parameters<typeof firebaseProvider.deleteMessage>) =>
  resolveImplementation("deleteMessage")(...args)) as typeof firebaseProvider.deleteMessage

export const pinMessage: typeof firebaseProvider.pinMessage = ((...args: Parameters<typeof firebaseProvider.pinMessage>) =>
  resolveImplementation("pinMessage")(...args)) as typeof firebaseProvider.pinMessage

export const unpinMessage: typeof firebaseProvider.unpinMessage = ((...args: Parameters<typeof firebaseProvider.unpinMessage>) =>
  resolveImplementation("unpinMessage")(...args)) as typeof firebaseProvider.unpinMessage

export const searchMessages: typeof firebaseProvider.searchMessages = ((...args: Parameters<typeof firebaseProvider.searchMessages>) =>
  resolveImplementation("searchMessages")(...args)) as typeof firebaseProvider.searchMessages

export const createCategory: typeof firebaseProvider.createCategory = ((...args: Parameters<typeof firebaseProvider.createCategory>) =>
  resolveImplementation("createCategory")(...args)) as typeof firebaseProvider.createCategory

export const getCategories: typeof firebaseProvider.getCategories = ((...args: Parameters<typeof firebaseProvider.getCategories>) =>
  resolveImplementation("getCategories")(...args)) as typeof firebaseProvider.getCategories

export const updateCategory: typeof firebaseProvider.updateCategory = ((...args: Parameters<typeof firebaseProvider.updateCategory>) =>
  resolveImplementation("updateCategory")(...args)) as typeof firebaseProvider.updateCategory

export const deleteCategory: typeof firebaseProvider.deleteCategory = ((...args: Parameters<typeof firebaseProvider.deleteCategory>) =>
  resolveImplementation("deleteCategory")(...args)) as typeof firebaseProvider.deleteCategory

export const updateUserStatus: typeof firebaseProvider.updateUserStatus = ((...args: Parameters<typeof firebaseProvider.updateUserStatus>) =>
  resolveImplementation("updateUserStatus")(...args)) as typeof firebaseProvider.updateUserStatus

export const getUserStatus: typeof firebaseProvider.getUserStatus = ((...args: Parameters<typeof firebaseProvider.getUserStatus>) =>
  resolveImplementation("getUserStatus")(...args)) as typeof firebaseProvider.getUserStatus

export const getUserDetails: typeof firebaseProvider.getUserDetails = ((...args: Parameters<typeof firebaseProvider.getUserDetails>) =>
  resolveImplementation("getUserDetails")(...args)) as typeof firebaseProvider.getUserDetails

export const getCompanyUsers: typeof firebaseProvider.getCompanyUsers = ((...args: Parameters<typeof firebaseProvider.getCompanyUsers>) =>
  resolveImplementation("getCompanyUsers")(...args)) as typeof firebaseProvider.getCompanyUsers

export const getChatSettings: typeof firebaseProvider.getChatSettings = ((...args: Parameters<typeof firebaseProvider.getChatSettings>) =>
  resolveImplementation("getChatSettings")(...args)) as typeof firebaseProvider.getChatSettings

export const updateChatSettings: typeof firebaseProvider.updateChatSettings = ((...args: Parameters<typeof firebaseProvider.updateChatSettings>) =>
  resolveImplementation("updateChatSettings")(...args)) as typeof firebaseProvider.updateChatSettings

export const saveDraftMessage: typeof firebaseProvider.saveDraftMessage = ((...args: Parameters<typeof firebaseProvider.saveDraftMessage>) =>
  resolveImplementation("saveDraftMessage")(...args)) as typeof firebaseProvider.saveDraftMessage

export const getDraftMessage: typeof firebaseProvider.getDraftMessage = ((...args: Parameters<typeof firebaseProvider.getDraftMessage>) =>
  resolveImplementation("getDraftMessage")(...args)) as typeof firebaseProvider.getDraftMessage

export const deleteDraftMessage: typeof firebaseProvider.deleteDraftMessage = ((...args: Parameters<typeof firebaseProvider.deleteDraftMessage>) =>
  resolveImplementation("deleteDraftMessage")(...args)) as typeof firebaseProvider.deleteDraftMessage

export const getUserNotifications: typeof firebaseProvider.getUserNotifications = ((...args: Parameters<typeof firebaseProvider.getUserNotifications>) =>
  resolveImplementation("getUserNotifications")(...args)) as typeof firebaseProvider.getUserNotifications

export const markNotificationAsRead: typeof firebaseProvider.markNotificationAsRead = ((...args: Parameters<typeof firebaseProvider.markNotificationAsRead>) =>
  resolveImplementation("markNotificationAsRead")(...args)) as typeof firebaseProvider.markNotificationAsRead

export const markAllNotificationsAsRead: typeof firebaseProvider.markAllNotificationsAsRead = ((...args: Parameters<typeof firebaseProvider.markAllNotificationsAsRead>) =>
  resolveImplementation("markAllNotificationsAsRead")(...args)) as typeof firebaseProvider.markAllNotificationsAsRead

export const subscribeToNotifications: typeof firebaseProvider.subscribeToNotifications = ((...args: Parameters<typeof firebaseProvider.subscribeToNotifications>) =>
  resolveImplementation("subscribeToNotifications")(...args)) as typeof firebaseProvider.subscribeToNotifications

export const uploadAttachment: typeof firebaseProvider.uploadAttachment = ((...args: Parameters<typeof firebaseProvider.uploadAttachment>) =>
  resolveImplementation("uploadAttachment")(...args)) as typeof firebaseProvider.uploadAttachment

export const fetchContacts: typeof firebaseProvider.fetchContacts = ((...args: Parameters<typeof firebaseProvider.fetchContacts>) =>
  resolveImplementation("fetchContacts")(...args)) as typeof firebaseProvider.fetchContacts

export const addContact: typeof firebaseProvider.addContact = ((...args: Parameters<typeof firebaseProvider.addContact>) =>
  resolveImplementation("addContact")(...args)) as typeof firebaseProvider.addContact

export const updateContact: typeof firebaseProvider.updateContact = ((...args: Parameters<typeof firebaseProvider.updateContact>) =>
  resolveImplementation("updateContact")(...args)) as typeof firebaseProvider.updateContact

export const deleteContact: typeof firebaseProvider.deleteContact = ((...args: Parameters<typeof firebaseProvider.deleteContact>) =>
  resolveImplementation("deleteContact")(...args)) as typeof firebaseProvider.deleteContact

export const subscribeToChats: typeof firebaseProvider.subscribeToChats = ((...args: Parameters<typeof firebaseProvider.subscribeToChats>) =>
  resolveImplementation("subscribeToChats")(...args)) as typeof firebaseProvider.subscribeToChats

export const subscribeToUserStatus: typeof firebaseProvider.subscribeToUserStatus = ((...args: Parameters<typeof firebaseProvider.subscribeToUserStatus>) =>
  resolveImplementation("subscribeToUserStatus")(...args)) as typeof firebaseProvider.subscribeToUserStatus
