// Generated by scripts/generate-data-layer.cjs. Do not edit by hand.
import * as firebaseProvider from "../rtdatabase/Notifications"
import * as supabaseProvider from "../providers/supabase/Notifications"
import { getModuleProvider } from "./providerRegistry"

type ProviderModule = typeof firebaseProvider
type ProviderFn<T extends keyof ProviderModule> = ProviderModule[T] extends (...args: infer Args) => infer Result
  ? (...args: Args) => Result
  : never

const resolveImplementation = <T extends keyof ProviderModule>(name: T): ProviderFn<T> => {
  const provider = getModuleProvider("Notifications")
  const source = provider === "supabase" ? (supabaseProvider as ProviderModule) : (firebaseProvider as ProviderModule)
  const implementation = source[name]
  if (typeof implementation !== "function") {
    throw new Error(`[data-provider] ${String(name)} is not implemented for provider "${provider}" in module "Notifications".`)
  }
  return implementation as ProviderFn<T>
}

export const createNotificationInDb: typeof firebaseProvider.createNotificationInDb = ((...args: Parameters<typeof firebaseProvider.createNotificationInDb>) =>
  resolveImplementation("createNotificationInDb")(...args)) as typeof firebaseProvider.createNotificationInDb

export const fetchNotificationsFromDb: typeof firebaseProvider.fetchNotificationsFromDb = ((...args: Parameters<typeof firebaseProvider.fetchNotificationsFromDb>) =>
  resolveImplementation("fetchNotificationsFromDb")(...args)) as typeof firebaseProvider.fetchNotificationsFromDb

export const fetchFilteredNotificationsFromDb: typeof firebaseProvider.fetchFilteredNotificationsFromDb = ((...args: Parameters<typeof firebaseProvider.fetchFilteredNotificationsFromDb>) =>
  resolveImplementation("fetchFilteredNotificationsFromDb")(...args)) as typeof firebaseProvider.fetchFilteredNotificationsFromDb

export const markNotificationAsReadInDb: typeof firebaseProvider.markNotificationAsReadInDb = ((...args: Parameters<typeof firebaseProvider.markNotificationAsReadInDb>) =>
  resolveImplementation("markNotificationAsReadInDb")(...args)) as typeof firebaseProvider.markNotificationAsReadInDb

export const markAllNotificationsAsReadInDb: typeof firebaseProvider.markAllNotificationsAsReadInDb = ((...args: Parameters<typeof firebaseProvider.markAllNotificationsAsReadInDb>) =>
  resolveImplementation("markAllNotificationsAsReadInDb")(...args)) as typeof firebaseProvider.markAllNotificationsAsReadInDb

export const deleteNotificationFromDb: typeof firebaseProvider.deleteNotificationFromDb = ((...args: Parameters<typeof firebaseProvider.deleteNotificationFromDb>) =>
  resolveImplementation("deleteNotificationFromDb")(...args)) as typeof firebaseProvider.deleteNotificationFromDb

export const deleteAllNotificationsFromDb: typeof firebaseProvider.deleteAllNotificationsFromDb = ((...args: Parameters<typeof firebaseProvider.deleteAllNotificationsFromDb>) =>
  resolveImplementation("deleteAllNotificationsFromDb")(...args)) as typeof firebaseProvider.deleteAllNotificationsFromDb

export const fetchNotificationSettingsFromDb: typeof firebaseProvider.fetchNotificationSettingsFromDb = ((...args: Parameters<typeof firebaseProvider.fetchNotificationSettingsFromDb>) =>
  resolveImplementation("fetchNotificationSettingsFromDb")(...args)) as typeof firebaseProvider.fetchNotificationSettingsFromDb

export const saveNotificationSettingsToDb: typeof firebaseProvider.saveNotificationSettingsToDb = ((...args: Parameters<typeof firebaseProvider.saveNotificationSettingsToDb>) =>
  resolveImplementation("saveNotificationSettingsToDb")(...args)) as typeof firebaseProvider.saveNotificationSettingsToDb

export const markNotificationAsReadForUserInDb: typeof firebaseProvider.markNotificationAsReadForUserInDb = ((...args: Parameters<typeof firebaseProvider.markNotificationAsReadForUserInDb>) =>
  resolveImplementation("markNotificationAsReadForUserInDb")(...args)) as typeof firebaseProvider.markNotificationAsReadForUserInDb

export const getUnreadCountForUserFromDb: typeof firebaseProvider.getUnreadCountForUserFromDb = ((...args: Parameters<typeof firebaseProvider.getUnreadCountForUserFromDb>) =>
  resolveImplementation("getUnreadCountForUserFromDb")(...args)) as typeof firebaseProvider.getUnreadCountForUserFromDb

export const getUserNotificationHistoryFromDb: typeof firebaseProvider.getUserNotificationHistoryFromDb = ((...args: Parameters<typeof firebaseProvider.getUserNotificationHistoryFromDb>) =>
  resolveImplementation("getUserNotificationHistoryFromDb")(...args)) as typeof firebaseProvider.getUserNotificationHistoryFromDb

export const getUnreadNotificationCountFromDb: typeof firebaseProvider.getUnreadNotificationCountFromDb = ((...args: Parameters<typeof firebaseProvider.getUnreadNotificationCountFromDb>) =>
  resolveImplementation("getUnreadNotificationCountFromDb")(...args)) as typeof firebaseProvider.getUnreadNotificationCountFromDb

export const cleanupOldNotificationsFromDb: typeof firebaseProvider.cleanupOldNotificationsFromDb = ((...args: Parameters<typeof firebaseProvider.cleanupOldNotificationsFromDb>) =>
  resolveImplementation("cleanupOldNotificationsFromDb")(...args)) as typeof firebaseProvider.cleanupOldNotificationsFromDb
