// Generated by scripts/generate-data-layer.cjs. Do not edit by hand.
import * as firebaseProvider from "../rtdatabase/POS"
import * as supabaseProvider from "../providers/supabase/POS"
import { getModuleProvider } from "./providerRegistry"

type ProviderModule = typeof firebaseProvider
type ProviderFn<T extends keyof ProviderModule> = ProviderModule[T] extends (...args: infer Args) => infer Result
  ? (...args: Args) => Result
  : never

const resolveImplementation = <T extends keyof ProviderModule>(name: T): ProviderFn<T> => {
  const provider = getModuleProvider("POS")
  const source = provider === "supabase" ? (supabaseProvider as ProviderModule) : (firebaseProvider as ProviderModule)
  const implementation = source[name]
  if (typeof implementation !== "function") {
    throw new Error(`[data-provider] ${String(name)} is not implemented for provider "${provider}" in module "POS".`)
  }
  return implementation as ProviderFn<T>
}

export const fetchPOSSettings: typeof firebaseProvider.fetchPOSSettings = ((...args: Parameters<typeof firebaseProvider.fetchPOSSettings>) =>
  resolveImplementation("fetchPOSSettings")(...args)) as typeof firebaseProvider.fetchPOSSettings

export const savePOSSettings: typeof firebaseProvider.savePOSSettings = ((...args: Parameters<typeof firebaseProvider.savePOSSettings>) =>
  resolveImplementation("savePOSSettings")(...args)) as typeof firebaseProvider.savePOSSettings

export const fetchPOSIntegrations: typeof firebaseProvider.fetchPOSIntegrations = ((...args: Parameters<typeof firebaseProvider.fetchPOSIntegrations>) =>
  resolveImplementation("fetchPOSIntegrations")(...args)) as typeof firebaseProvider.fetchPOSIntegrations

export const savePOSIntegration: typeof firebaseProvider.savePOSIntegration = ((...args: Parameters<typeof firebaseProvider.savePOSIntegration>) =>
  resolveImplementation("savePOSIntegration")(...args)) as typeof firebaseProvider.savePOSIntegration

export const fetchBills: typeof firebaseProvider.fetchBills = ((...args: Parameters<typeof firebaseProvider.fetchBills>) =>
  resolveImplementation("fetchBills")(...args)) as typeof firebaseProvider.fetchBills

export const fetchOpenBills: typeof firebaseProvider.fetchOpenBills = ((...args: Parameters<typeof firebaseProvider.fetchOpenBills>) =>
  resolveImplementation("fetchOpenBills")(...args)) as typeof firebaseProvider.fetchOpenBills

export const fetchClosedBills: typeof firebaseProvider.fetchClosedBills = ((...args: Parameters<typeof firebaseProvider.fetchClosedBills>) =>
  resolveImplementation("fetchClosedBills")(...args)) as typeof firebaseProvider.fetchClosedBills

export const fetchTransactions: typeof firebaseProvider.fetchTransactions = ((...args: Parameters<typeof firebaseProvider.fetchTransactions>) =>
  resolveImplementation("fetchTransactions")(...args)) as typeof firebaseProvider.fetchTransactions

export const createBill: typeof firebaseProvider.createBill = ((...args: Parameters<typeof firebaseProvider.createBill>) =>
  resolveImplementation("createBill")(...args)) as typeof firebaseProvider.createBill

export const updateBill: typeof firebaseProvider.updateBill = ((...args: Parameters<typeof firebaseProvider.updateBill>) =>
  resolveImplementation("updateBill")(...args)) as typeof firebaseProvider.updateBill

export const deleteBill: typeof firebaseProvider.deleteBill = ((...args: Parameters<typeof firebaseProvider.deleteBill>) =>
  resolveImplementation("deleteBill")(...args)) as typeof firebaseProvider.deleteBill

export const fetchTillScreens: typeof firebaseProvider.fetchTillScreens = ((...args: Parameters<typeof firebaseProvider.fetchTillScreens>) =>
  resolveImplementation("fetchTillScreens")(...args)) as typeof firebaseProvider.fetchTillScreens

export const createTillScreen: typeof firebaseProvider.createTillScreen = ((...args: Parameters<typeof firebaseProvider.createTillScreen>) =>
  resolveImplementation("createTillScreen")(...args)) as typeof firebaseProvider.createTillScreen

export const updateTillScreen: typeof firebaseProvider.updateTillScreen = ((...args: Parameters<typeof firebaseProvider.updateTillScreen>) =>
  resolveImplementation("updateTillScreen")(...args)) as typeof firebaseProvider.updateTillScreen

export const deleteTillScreen: typeof firebaseProvider.deleteTillScreen = ((...args: Parameters<typeof firebaseProvider.deleteTillScreen>) =>
  resolveImplementation("deleteTillScreen")(...args)) as typeof firebaseProvider.deleteTillScreen

export const fetchPaymentTypes: typeof firebaseProvider.fetchPaymentTypes = ((...args: Parameters<typeof firebaseProvider.fetchPaymentTypes>) =>
  resolveImplementation("fetchPaymentTypes")(...args)) as typeof firebaseProvider.fetchPaymentTypes

export const createPaymentType: typeof firebaseProvider.createPaymentType = ((...args: Parameters<typeof firebaseProvider.createPaymentType>) =>
  resolveImplementation("createPaymentType")(...args)) as typeof firebaseProvider.createPaymentType

export const updatePaymentType: typeof firebaseProvider.updatePaymentType = ((...args: Parameters<typeof firebaseProvider.updatePaymentType>) =>
  resolveImplementation("updatePaymentType")(...args)) as typeof firebaseProvider.updatePaymentType

export const deletePaymentType: typeof firebaseProvider.deletePaymentType = ((...args: Parameters<typeof firebaseProvider.deletePaymentType>) =>
  resolveImplementation("deletePaymentType")(...args)) as typeof firebaseProvider.deletePaymentType

export const fetchFloorPlans: typeof firebaseProvider.fetchFloorPlans = ((...args: Parameters<typeof firebaseProvider.fetchFloorPlans>) =>
  resolveImplementation("fetchFloorPlans")(...args)) as typeof firebaseProvider.fetchFloorPlans

export const createFloorPlan: typeof firebaseProvider.createFloorPlan = ((...args: Parameters<typeof firebaseProvider.createFloorPlan>) =>
  resolveImplementation("createFloorPlan")(...args)) as typeof firebaseProvider.createFloorPlan

export const updateFloorPlan: typeof firebaseProvider.updateFloorPlan = ((...args: Parameters<typeof firebaseProvider.updateFloorPlan>) =>
  resolveImplementation("updateFloorPlan")(...args)) as typeof firebaseProvider.updateFloorPlan

export const deleteFloorPlan: typeof firebaseProvider.deleteFloorPlan = ((...args: Parameters<typeof firebaseProvider.deleteFloorPlan>) =>
  resolveImplementation("deleteFloorPlan")(...args)) as typeof firebaseProvider.deleteFloorPlan

export const fetchTables: typeof firebaseProvider.fetchTables = ((...args: Parameters<typeof firebaseProvider.fetchTables>) =>
  resolveImplementation("fetchTables")(...args)) as typeof firebaseProvider.fetchTables

export const createTable: typeof firebaseProvider.createTable = ((...args: Parameters<typeof firebaseProvider.createTable>) =>
  resolveImplementation("createTable")(...args)) as typeof firebaseProvider.createTable

export const updateTable: typeof firebaseProvider.updateTable = ((...args: Parameters<typeof firebaseProvider.updateTable>) =>
  resolveImplementation("updateTable")(...args)) as typeof firebaseProvider.updateTable

export const deleteTable: typeof firebaseProvider.deleteTable = ((...args: Parameters<typeof firebaseProvider.deleteTable>) =>
  resolveImplementation("deleteTable")(...args)) as typeof firebaseProvider.deleteTable

export const fetchDiscounts: typeof firebaseProvider.fetchDiscounts = ((...args: Parameters<typeof firebaseProvider.fetchDiscounts>) =>
  resolveImplementation("fetchDiscounts")(...args)) as typeof firebaseProvider.fetchDiscounts

export const createDiscount: typeof firebaseProvider.createDiscount = ((...args: Parameters<typeof firebaseProvider.createDiscount>) =>
  resolveImplementation("createDiscount")(...args)) as typeof firebaseProvider.createDiscount

export const updateDiscount: typeof firebaseProvider.updateDiscount = ((...args: Parameters<typeof firebaseProvider.updateDiscount>) =>
  resolveImplementation("updateDiscount")(...args)) as typeof firebaseProvider.updateDiscount

export const deleteDiscount: typeof firebaseProvider.deleteDiscount = ((...args: Parameters<typeof firebaseProvider.deleteDiscount>) =>
  resolveImplementation("deleteDiscount")(...args)) as typeof firebaseProvider.deleteDiscount

export const fetchPromotions: typeof firebaseProvider.fetchPromotions = ((...args: Parameters<typeof firebaseProvider.fetchPromotions>) =>
  resolveImplementation("fetchPromotions")(...args)) as typeof firebaseProvider.fetchPromotions

export const createPromotion: typeof firebaseProvider.createPromotion = ((...args: Parameters<typeof firebaseProvider.createPromotion>) =>
  resolveImplementation("createPromotion")(...args)) as typeof firebaseProvider.createPromotion

export const updatePromotion: typeof firebaseProvider.updatePromotion = ((...args: Parameters<typeof firebaseProvider.updatePromotion>) =>
  resolveImplementation("updatePromotion")(...args)) as typeof firebaseProvider.updatePromotion

export const deletePromotion: typeof firebaseProvider.deletePromotion = ((...args: Parameters<typeof firebaseProvider.deletePromotion>) =>
  resolveImplementation("deletePromotion")(...args)) as typeof firebaseProvider.deletePromotion

export const fetchCorrections: typeof firebaseProvider.fetchCorrections = ((...args: Parameters<typeof firebaseProvider.fetchCorrections>) =>
  resolveImplementation("fetchCorrections")(...args)) as typeof firebaseProvider.fetchCorrections

export const createCorrection: typeof firebaseProvider.createCorrection = ((...args: Parameters<typeof firebaseProvider.createCorrection>) =>
  resolveImplementation("createCorrection")(...args)) as typeof firebaseProvider.createCorrection

export const updateCorrection: typeof firebaseProvider.updateCorrection = ((...args: Parameters<typeof firebaseProvider.updateCorrection>) =>
  resolveImplementation("updateCorrection")(...args)) as typeof firebaseProvider.updateCorrection

export const deleteCorrection: typeof firebaseProvider.deleteCorrection = ((...args: Parameters<typeof firebaseProvider.deleteCorrection>) =>
  resolveImplementation("deleteCorrection")(...args)) as typeof firebaseProvider.deleteCorrection

export const fetchBagCheckItems: typeof firebaseProvider.fetchBagCheckItems = ((...args: Parameters<typeof firebaseProvider.fetchBagCheckItems>) =>
  resolveImplementation("fetchBagCheckItems")(...args)) as typeof firebaseProvider.fetchBagCheckItems

export const createBagCheckItem: typeof firebaseProvider.createBagCheckItem = ((...args: Parameters<typeof firebaseProvider.createBagCheckItem>) =>
  resolveImplementation("createBagCheckItem")(...args)) as typeof firebaseProvider.createBagCheckItem

export const updateBagCheckItem: typeof firebaseProvider.updateBagCheckItem = ((...args: Parameters<typeof firebaseProvider.updateBagCheckItem>) =>
  resolveImplementation("updateBagCheckItem")(...args)) as typeof firebaseProvider.updateBagCheckItem

export const deleteBagCheckItem: typeof firebaseProvider.deleteBagCheckItem = ((...args: Parameters<typeof firebaseProvider.deleteBagCheckItem>) =>
  resolveImplementation("deleteBagCheckItem")(...args)) as typeof firebaseProvider.deleteBagCheckItem

export const fetchBagCheckConfig: typeof firebaseProvider.fetchBagCheckConfig = ((...args: Parameters<typeof firebaseProvider.fetchBagCheckConfig>) =>
  resolveImplementation("fetchBagCheckConfig")(...args)) as typeof firebaseProvider.fetchBagCheckConfig

export const updateBagCheckConfig: typeof firebaseProvider.updateBagCheckConfig = ((...args: Parameters<typeof firebaseProvider.updateBagCheckConfig>) =>
  resolveImplementation("updateBagCheckConfig")(...args)) as typeof firebaseProvider.updateBagCheckConfig

export const fetchLocations: typeof firebaseProvider.fetchLocations = ((...args: Parameters<typeof firebaseProvider.fetchLocations>) =>
  resolveImplementation("fetchLocations")(...args)) as typeof firebaseProvider.fetchLocations

export const createLocation: typeof firebaseProvider.createLocation = ((...args: Parameters<typeof firebaseProvider.createLocation>) =>
  resolveImplementation("createLocation")(...args)) as typeof firebaseProvider.createLocation

export const updateLocation: typeof firebaseProvider.updateLocation = ((...args: Parameters<typeof firebaseProvider.updateLocation>) =>
  resolveImplementation("updateLocation")(...args)) as typeof firebaseProvider.updateLocation

export const deleteLocation: typeof firebaseProvider.deleteLocation = ((...args: Parameters<typeof firebaseProvider.deleteLocation>) =>
  resolveImplementation("deleteLocation")(...args)) as typeof firebaseProvider.deleteLocation

export const fetchDevices: typeof firebaseProvider.fetchDevices = ((...args: Parameters<typeof firebaseProvider.fetchDevices>) =>
  resolveImplementation("fetchDevices")(...args)) as typeof firebaseProvider.fetchDevices

export const createDevice: typeof firebaseProvider.createDevice = ((...args: Parameters<typeof firebaseProvider.createDevice>) =>
  resolveImplementation("createDevice")(...args)) as typeof firebaseProvider.createDevice

export const updateDevice: typeof firebaseProvider.updateDevice = ((...args: Parameters<typeof firebaseProvider.updateDevice>) =>
  resolveImplementation("updateDevice")(...args)) as typeof firebaseProvider.updateDevice

export const deleteDevice: typeof firebaseProvider.deleteDevice = ((...args: Parameters<typeof firebaseProvider.deleteDevice>) =>
  resolveImplementation("deleteDevice")(...args)) as typeof firebaseProvider.deleteDevice

export const fetchPaymentIntegrations: typeof firebaseProvider.fetchPaymentIntegrations = ((...args: Parameters<typeof firebaseProvider.fetchPaymentIntegrations>) =>
  resolveImplementation("fetchPaymentIntegrations")(...args)) as typeof firebaseProvider.fetchPaymentIntegrations

export const createPaymentIntegration: typeof firebaseProvider.createPaymentIntegration = ((...args: Parameters<typeof firebaseProvider.createPaymentIntegration>) =>
  resolveImplementation("createPaymentIntegration")(...args)) as typeof firebaseProvider.createPaymentIntegration

export const updatePaymentIntegration: typeof firebaseProvider.updatePaymentIntegration = ((...args: Parameters<typeof firebaseProvider.updatePaymentIntegration>) =>
  resolveImplementation("updatePaymentIntegration")(...args)) as typeof firebaseProvider.updatePaymentIntegration

export const deletePaymentIntegration: typeof firebaseProvider.deletePaymentIntegration = ((...args: Parameters<typeof firebaseProvider.deletePaymentIntegration>) =>
  resolveImplementation("deletePaymentIntegration")(...args)) as typeof firebaseProvider.deletePaymentIntegration

export const fetchTickets: typeof firebaseProvider.fetchTickets = ((...args: Parameters<typeof firebaseProvider.fetchTickets>) =>
  resolveImplementation("fetchTickets")(...args)) as typeof firebaseProvider.fetchTickets

export const createTicket: typeof firebaseProvider.createTicket = ((...args: Parameters<typeof firebaseProvider.createTicket>) =>
  resolveImplementation("createTicket")(...args)) as typeof firebaseProvider.createTicket

export const updateTicket: typeof firebaseProvider.updateTicket = ((...args: Parameters<typeof firebaseProvider.updateTicket>) =>
  resolveImplementation("updateTicket")(...args)) as typeof firebaseProvider.updateTicket

export const deleteTicket: typeof firebaseProvider.deleteTicket = ((...args: Parameters<typeof firebaseProvider.deleteTicket>) =>
  resolveImplementation("deleteTicket")(...args)) as typeof firebaseProvider.deleteTicket

export const fetchTicketSales: typeof firebaseProvider.fetchTicketSales = ((...args: Parameters<typeof firebaseProvider.fetchTicketSales>) =>
  resolveImplementation("fetchTicketSales")(...args)) as typeof firebaseProvider.fetchTicketSales

export const createTicketSale: typeof firebaseProvider.createTicketSale = ((...args: Parameters<typeof firebaseProvider.createTicketSale>) =>
  resolveImplementation("createTicketSale")(...args)) as typeof firebaseProvider.createTicketSale

export const updateTicketSale: typeof firebaseProvider.updateTicketSale = ((...args: Parameters<typeof firebaseProvider.updateTicketSale>) =>
  resolveImplementation("updateTicketSale")(...args)) as typeof firebaseProvider.updateTicketSale

export const deleteTicketSale: typeof firebaseProvider.deleteTicketSale = ((...args: Parameters<typeof firebaseProvider.deleteTicketSale>) =>
  resolveImplementation("deleteTicketSale")(...args)) as typeof firebaseProvider.deleteTicketSale

export const fetchPaymentTransactions: typeof firebaseProvider.fetchPaymentTransactions = ((...args: Parameters<typeof firebaseProvider.fetchPaymentTransactions>) =>
  resolveImplementation("fetchPaymentTransactions")(...args)) as typeof firebaseProvider.fetchPaymentTransactions

export const fetchPaymentTransactionsByBill: typeof firebaseProvider.fetchPaymentTransactionsByBill = ((...args: Parameters<typeof firebaseProvider.fetchPaymentTransactionsByBill>) =>
  resolveImplementation("fetchPaymentTransactionsByBill")(...args)) as typeof firebaseProvider.fetchPaymentTransactionsByBill

export const createPaymentTransaction: typeof firebaseProvider.createPaymentTransaction = ((...args: Parameters<typeof firebaseProvider.createPaymentTransaction>) =>
  resolveImplementation("createPaymentTransaction")(...args)) as typeof firebaseProvider.createPaymentTransaction

export const updatePaymentTransaction: typeof firebaseProvider.updatePaymentTransaction = ((...args: Parameters<typeof firebaseProvider.updatePaymentTransaction>) =>
  resolveImplementation("updatePaymentTransaction")(...args)) as typeof firebaseProvider.updatePaymentTransaction

export const deletePaymentTransaction: typeof firebaseProvider.deletePaymentTransaction = ((...args: Parameters<typeof firebaseProvider.deletePaymentTransaction>) =>
  resolveImplementation("deletePaymentTransaction")(...args)) as typeof firebaseProvider.deletePaymentTransaction

export const fetchSales: typeof firebaseProvider.fetchSales = ((...args: Parameters<typeof firebaseProvider.fetchSales>) =>
  resolveImplementation("fetchSales")(...args)) as typeof firebaseProvider.fetchSales

export const createSale: typeof firebaseProvider.createSale = ((...args: Parameters<typeof firebaseProvider.createSale>) =>
  resolveImplementation("createSale")(...args)) as typeof firebaseProvider.createSale

export const fetchSalesByDateRange: typeof firebaseProvider.fetchSalesByDateRange = ((...args: Parameters<typeof firebaseProvider.fetchSalesByDateRange>) =>
  resolveImplementation("fetchSalesByDateRange")(...args)) as typeof firebaseProvider.fetchSalesByDateRange

export const fetchSalesByProduct: typeof firebaseProvider.fetchSalesByProduct = ((...args: Parameters<typeof firebaseProvider.fetchSalesByProduct>) =>
  resolveImplementation("fetchSalesByProduct")(...args)) as typeof firebaseProvider.fetchSalesByProduct

export const fetchGroups: typeof firebaseProvider.fetchGroups = ((...args: Parameters<typeof firebaseProvider.fetchGroups>) =>
  resolveImplementation("fetchGroups")(...args)) as typeof firebaseProvider.fetchGroups

export const createGroup: typeof firebaseProvider.createGroup = ((...args: Parameters<typeof firebaseProvider.createGroup>) =>
  resolveImplementation("createGroup")(...args)) as typeof firebaseProvider.createGroup

export const updateGroup: typeof firebaseProvider.updateGroup = ((...args: Parameters<typeof firebaseProvider.updateGroup>) =>
  resolveImplementation("updateGroup")(...args)) as typeof firebaseProvider.updateGroup

export const deleteGroup: typeof firebaseProvider.deleteGroup = ((...args: Parameters<typeof firebaseProvider.deleteGroup>) =>
  resolveImplementation("deleteGroup")(...args)) as typeof firebaseProvider.deleteGroup

export const fetchCourses: typeof firebaseProvider.fetchCourses = ((...args: Parameters<typeof firebaseProvider.fetchCourses>) =>
  resolveImplementation("fetchCourses")(...args)) as typeof firebaseProvider.fetchCourses

export const createCourse: typeof firebaseProvider.createCourse = ((...args: Parameters<typeof firebaseProvider.createCourse>) =>
  resolveImplementation("createCourse")(...args)) as typeof firebaseProvider.createCourse

export const updateCourse: typeof firebaseProvider.updateCourse = ((...args: Parameters<typeof firebaseProvider.updateCourse>) =>
  resolveImplementation("updateCourse")(...args)) as typeof firebaseProvider.updateCourse

export const deleteCourse: typeof firebaseProvider.deleteCourse = ((...args: Parameters<typeof firebaseProvider.deleteCourse>) =>
  resolveImplementation("deleteCourse")(...args)) as typeof firebaseProvider.deleteCourse

export const fetchCards: typeof firebaseProvider.fetchCards = ((...args: Parameters<typeof firebaseProvider.fetchCards>) =>
  resolveImplementation("fetchCards")(...args)) as typeof firebaseProvider.fetchCards

export const createCard: typeof firebaseProvider.createCard = ((...args: Parameters<typeof firebaseProvider.createCard>) =>
  resolveImplementation("createCard")(...args)) as typeof firebaseProvider.createCard

export const updateCard: typeof firebaseProvider.updateCard = ((...args: Parameters<typeof firebaseProvider.updateCard>) =>
  resolveImplementation("updateCard")(...args)) as typeof firebaseProvider.updateCard

export const deleteCard: typeof firebaseProvider.deleteCard = ((...args: Parameters<typeof firebaseProvider.deleteCard>) =>
  resolveImplementation("deleteCard")(...args)) as typeof firebaseProvider.deleteCard
