// Generated by scripts/generate-data-layer.cjs. Do not edit by hand.
import * as firebaseProvider from "../rtdatabase/Product"
import * as supabaseProvider from "../providers/supabase/Product"
import { getModuleProvider } from "./providerRegistry"

type ProviderModule = typeof firebaseProvider
type ProviderFn<T extends keyof ProviderModule> = ProviderModule[T] extends (...args: infer Args) => infer Result
  ? (...args: Args) => Result
  : never

const resolveImplementation = <T extends keyof ProviderModule>(name: T): ProviderFn<T> => {
  const provider = getModuleProvider("Product")
  const source = provider === "supabase" ? (supabaseProvider as ProviderModule) : (firebaseProvider as ProviderModule)
  const implementation = source[name]
  if (typeof implementation !== "function") {
    throw new Error(`[data-provider] ${String(name)} is not implemented for provider "${provider}" in module "Product".`)
  }
  return implementation as ProviderFn<T>
}

export const fetchProducts: typeof firebaseProvider.fetchProducts = ((...args: Parameters<typeof firebaseProvider.fetchProducts>) =>
  resolveImplementation("fetchProducts")(...args)) as typeof firebaseProvider.fetchProducts

export const createProduct: typeof firebaseProvider.createProduct = ((...args: Parameters<typeof firebaseProvider.createProduct>) =>
  resolveImplementation("createProduct")(...args)) as typeof firebaseProvider.createProduct

export const updateProduct: typeof firebaseProvider.updateProduct = ((...args: Parameters<typeof firebaseProvider.updateProduct>) =>
  resolveImplementation("updateProduct")(...args)) as typeof firebaseProvider.updateProduct

export const deleteProduct: typeof firebaseProvider.deleteProduct = ((...args: Parameters<typeof firebaseProvider.deleteProduct>) =>
  resolveImplementation("deleteProduct")(...args)) as typeof firebaseProvider.deleteProduct

export const fetchProductCategories: typeof firebaseProvider.fetchProductCategories = ((...args: Parameters<typeof firebaseProvider.fetchProductCategories>) =>
  resolveImplementation("fetchProductCategories")(...args)) as typeof firebaseProvider.fetchProductCategories

export const createProductCategory: typeof firebaseProvider.createProductCategory = ((...args: Parameters<typeof firebaseProvider.createProductCategory>) =>
  resolveImplementation("createProductCategory")(...args)) as typeof firebaseProvider.createProductCategory

export const updateProductCategory: typeof firebaseProvider.updateProductCategory = ((...args: Parameters<typeof firebaseProvider.updateProductCategory>) =>
  resolveImplementation("updateProductCategory")(...args)) as typeof firebaseProvider.updateProductCategory

export const deleteProductCategory: typeof firebaseProvider.deleteProductCategory = ((...args: Parameters<typeof firebaseProvider.deleteProductCategory>) =>
  resolveImplementation("deleteProductCategory")(...args)) as typeof firebaseProvider.deleteProductCategory

export const searchProducts: typeof firebaseProvider.searchProducts = ((...args: Parameters<typeof firebaseProvider.searchProducts>) =>
  resolveImplementation("searchProducts")(...args)) as typeof firebaseProvider.searchProducts

export const getProductByBarcode: typeof firebaseProvider.getProductByBarcode = ((...args: Parameters<typeof firebaseProvider.getProductByBarcode>) =>
  resolveImplementation("getProductByBarcode")(...args)) as typeof firebaseProvider.getProductByBarcode
