// Generated by scripts/generate-data-layer.cjs. Do not edit by hand.
import * as firebaseProvider from "../rtdatabase/Settings"
import * as supabaseProvider from "../providers/supabase/Settings"
import { getModuleProvider } from "./providerRegistry"

type ProviderModule = typeof firebaseProvider
type ProviderFn<T extends keyof ProviderModule> = ProviderModule[T] extends (...args: infer Args) => infer Result
  ? (...args: Args) => Result
  : never

const resolveImplementation = <T extends keyof ProviderModule>(name: T): ProviderFn<T> => {
  const provider = getModuleProvider("Settings")
  const source = provider === "supabase" ? (supabaseProvider as ProviderModule) : (firebaseProvider as ProviderModule)
  const implementation = source[name]
  if (typeof implementation !== "function") {
    throw new Error(`[data-provider] ${String(name)} is not implemented for provider "${provider}" in module "Settings".`)
  }
  return implementation as ProviderFn<T>
}

export const fetchAllInvites: typeof firebaseProvider.fetchAllInvites = ((...args: Parameters<typeof firebaseProvider.fetchAllInvites>) =>
  resolveImplementation("fetchAllInvites")(...args)) as typeof firebaseProvider.fetchAllInvites

export const updateInviteInDb: typeof firebaseProvider.updateInviteInDb = ((...args: Parameters<typeof firebaseProvider.updateInviteInDb>) =>
  resolveImplementation("updateInviteInDb")(...args)) as typeof firebaseProvider.updateInviteInDb

export const fetchUserCompaniesRaw: typeof firebaseProvider.fetchUserCompaniesRaw = ((...args: Parameters<typeof firebaseProvider.fetchUserCompaniesRaw>) =>
  resolveImplementation("fetchUserCompaniesRaw")(...args)) as typeof firebaseProvider.fetchUserCompaniesRaw

export const fetchUserDataRaw: typeof firebaseProvider.fetchUserDataRaw = ((...args: Parameters<typeof firebaseProvider.fetchUserDataRaw>) =>
  resolveImplementation("fetchUserDataRaw")(...args)) as typeof firebaseProvider.fetchUserDataRaw

export const setUserLastLogin: typeof firebaseProvider.setUserLastLogin = ((...args: Parameters<typeof firebaseProvider.setUserLastLogin>) =>
  resolveImplementation("setUserLastLogin")(...args)) as typeof firebaseProvider.setUserLastLogin

export const subscribeAllUsers: typeof firebaseProvider.subscribeAllUsers = ((...args: Parameters<typeof firebaseProvider.subscribeAllUsers>) =>
  resolveImplementation("subscribeAllUsers")(...args)) as typeof firebaseProvider.subscribeAllUsers

export const fetchIntegrationsFromPath: typeof firebaseProvider.fetchIntegrationsFromPath = ((...args: Parameters<typeof firebaseProvider.fetchIntegrationsFromPath>) =>
  resolveImplementation("fetchIntegrationsFromPath")(...args)) as typeof firebaseProvider.fetchIntegrationsFromPath

export const saveIntegrationToPath: typeof firebaseProvider.saveIntegrationToPath = ((...args: Parameters<typeof firebaseProvider.saveIntegrationToPath>) =>
  resolveImplementation("saveIntegrationToPath")(...args)) as typeof firebaseProvider.saveIntegrationToPath

export const signInWithEmail: typeof firebaseProvider.signInWithEmail = ((...args: Parameters<typeof firebaseProvider.signInWithEmail>) =>
  resolveImplementation("signInWithEmail")(...args)) as typeof firebaseProvider.signInWithEmail

export const signUpWithEmail: typeof firebaseProvider.signUpWithEmail = ((...args: Parameters<typeof firebaseProvider.signUpWithEmail>) =>
  resolveImplementation("signUpWithEmail")(...args)) as typeof firebaseProvider.signUpWithEmail

export const signOutUser: typeof firebaseProvider.signOutUser = ((...args: Parameters<typeof firebaseProvider.signOutUser>) =>
  resolveImplementation("signOutUser")(...args)) as typeof firebaseProvider.signOutUser

export const resendEmailVerification: typeof firebaseProvider.resendEmailVerification = ((...args: Parameters<typeof firebaseProvider.resendEmailVerification>) =>
  resolveImplementation("resendEmailVerification")(...args)) as typeof firebaseProvider.resendEmailVerification

export const sendPasswordReset: typeof firebaseProvider.sendPasswordReset = ((...args: Parameters<typeof firebaseProvider.sendPasswordReset>) =>
  resolveImplementation("sendPasswordReset")(...args)) as typeof firebaseProvider.sendPasswordReset

export const sendCustomVerificationEmail: typeof firebaseProvider.sendCustomVerificationEmail = ((...args: Parameters<typeof firebaseProvider.sendCustomVerificationEmail>) =>
  resolveImplementation("sendCustomVerificationEmail")(...args)) as typeof firebaseProvider.sendCustomVerificationEmail

export const sendCustomVerificationEmailToEmail: typeof firebaseProvider.sendCustomVerificationEmailToEmail = ((...args: Parameters<typeof firebaseProvider.sendCustomVerificationEmailToEmail>) =>
  resolveImplementation("sendCustomVerificationEmailToEmail")(...args)) as typeof firebaseProvider.sendCustomVerificationEmailToEmail

export const updateUserFirebaseProfile: typeof firebaseProvider.updateUserFirebaseProfile = ((...args: Parameters<typeof firebaseProvider.updateUserFirebaseProfile>) =>
  resolveImplementation("updateUserFirebaseProfile")(...args)) as typeof firebaseProvider.updateUserFirebaseProfile

export const getCurrentFirebaseUser: typeof firebaseProvider.getCurrentFirebaseUser = ((...args: Parameters<typeof firebaseProvider.getCurrentFirebaseUser>) =>
  resolveImplementation("getCurrentFirebaseUser")(...args)) as typeof firebaseProvider.getCurrentFirebaseUser

export const loginWithEmailAndPassword: typeof firebaseProvider.loginWithEmailAndPassword = ((...args: Parameters<typeof firebaseProvider.loginWithEmailAndPassword>) =>
  resolveImplementation("loginWithEmailAndPassword")(...args)) as typeof firebaseProvider.loginWithEmailAndPassword

export const registerWithEmailAndPassword: typeof firebaseProvider.registerWithEmailAndPassword = ((...args: Parameters<typeof firebaseProvider.registerWithEmailAndPassword>) =>
  resolveImplementation("registerWithEmailAndPassword")(...args)) as typeof firebaseProvider.registerWithEmailAndPassword

export const createUserProfileInDb: typeof firebaseProvider.createUserProfileInDb = ((...args: Parameters<typeof firebaseProvider.createUserProfileInDb>) =>
  resolveImplementation("createUserProfileInDb")(...args)) as typeof firebaseProvider.createUserProfileInDb

export const updateAvatarInDb: typeof firebaseProvider.updateAvatarInDb = ((...args: Parameters<typeof firebaseProvider.updateAvatarInDb>) =>
  resolveImplementation("updateAvatarInDb")(...args)) as typeof firebaseProvider.updateAvatarInDb

export const updateThemeInDb: typeof firebaseProvider.updateThemeInDb = ((...args: Parameters<typeof firebaseProvider.updateThemeInDb>) =>
  resolveImplementation("updateThemeInDb")(...args)) as typeof firebaseProvider.updateThemeInDb

export const updateBusinessLogoInDb: typeof firebaseProvider.updateBusinessLogoInDb = ((...args: Parameters<typeof firebaseProvider.updateBusinessLogoInDb>) =>
  resolveImplementation("updateBusinessLogoInDb")(...args)) as typeof firebaseProvider.updateBusinessLogoInDb

export const getUserData: typeof firebaseProvider.getUserData = ((...args: Parameters<typeof firebaseProvider.getUserData>) =>
  resolveImplementation("getUserData")(...args)) as typeof firebaseProvider.getUserData

export const updateUserData: typeof firebaseProvider.updateUserData = ((...args: Parameters<typeof firebaseProvider.updateUserData>) =>
  resolveImplementation("updateUserData")(...args)) as typeof firebaseProvider.updateUserData

export const setCurrentCompany: typeof firebaseProvider.setCurrentCompany = ((...args: Parameters<typeof firebaseProvider.setCurrentCompany>) =>
  resolveImplementation("setCurrentCompany")(...args)) as typeof firebaseProvider.setCurrentCompany

export const addCompanyToUser: typeof firebaseProvider.addCompanyToUser = ((...args: Parameters<typeof firebaseProvider.addCompanyToUser>) =>
  resolveImplementation("addCompanyToUser")(...args)) as typeof firebaseProvider.addCompanyToUser

export const removeCompanyFromUser: typeof firebaseProvider.removeCompanyFromUser = ((...args: Parameters<typeof firebaseProvider.removeCompanyFromUser>) =>
  resolveImplementation("removeCompanyFromUser")(...args)) as typeof firebaseProvider.removeCompanyFromUser

export const fetchUserPersonalSettings: typeof firebaseProvider.fetchUserPersonalSettings = ((...args: Parameters<typeof firebaseProvider.fetchUserPersonalSettings>) =>
  resolveImplementation("fetchUserPersonalSettings")(...args)) as typeof firebaseProvider.fetchUserPersonalSettings

export const fetchPersonalSettings: typeof firebaseProvider.fetchPersonalSettings = ((...args: Parameters<typeof firebaseProvider.fetchPersonalSettings>) =>
  resolveImplementation("fetchPersonalSettings")(...args)) as typeof firebaseProvider.fetchPersonalSettings

export const updatePersonalSettings: typeof firebaseProvider.updatePersonalSettings = ((...args: Parameters<typeof firebaseProvider.updatePersonalSettings>) =>
  resolveImplementation("updatePersonalSettings")(...args)) as typeof firebaseProvider.updatePersonalSettings

export const updateAvatar: typeof firebaseProvider.updateAvatar = ((...args: Parameters<typeof firebaseProvider.updateAvatar>) =>
  resolveImplementation("updateAvatar")(...args)) as typeof firebaseProvider.updateAvatar

export const fetchUserPreferencesSettings: typeof firebaseProvider.fetchUserPreferencesSettings = ((...args: Parameters<typeof firebaseProvider.fetchUserPreferencesSettings>) =>
  resolveImplementation("fetchUserPreferencesSettings")(...args)) as typeof firebaseProvider.fetchUserPreferencesSettings

export const fetchPreferencesSettings: typeof firebaseProvider.fetchPreferencesSettings = ((...args: Parameters<typeof firebaseProvider.fetchPreferencesSettings>) =>
  resolveImplementation("fetchPreferencesSettings")(...args)) as typeof firebaseProvider.fetchPreferencesSettings

export const updatePreferencesSettings: typeof firebaseProvider.updatePreferencesSettings = ((...args: Parameters<typeof firebaseProvider.updatePreferencesSettings>) =>
  resolveImplementation("updatePreferencesSettings")(...args)) as typeof firebaseProvider.updatePreferencesSettings

export const updateTheme: typeof firebaseProvider.updateTheme = ((...args: Parameters<typeof firebaseProvider.updateTheme>) =>
  resolveImplementation("updateTheme")(...args)) as typeof firebaseProvider.updateTheme

export const fetchCompanyBusinessSettings: typeof firebaseProvider.fetchCompanyBusinessSettings = ((...args: Parameters<typeof firebaseProvider.fetchCompanyBusinessSettings>) =>
  resolveImplementation("fetchCompanyBusinessSettings")(...args)) as typeof firebaseProvider.fetchCompanyBusinessSettings

export const fetchBusinessSettings: typeof firebaseProvider.fetchBusinessSettings = ((...args: Parameters<typeof firebaseProvider.fetchBusinessSettings>) =>
  resolveImplementation("fetchBusinessSettings")(...args)) as typeof firebaseProvider.fetchBusinessSettings

export const updateBusinessSettings: typeof firebaseProvider.updateBusinessSettings = ((...args: Parameters<typeof firebaseProvider.updateBusinessSettings>) =>
  resolveImplementation("updateBusinessSettings")(...args)) as typeof firebaseProvider.updateBusinessSettings

export const updateBusinessLogo: typeof firebaseProvider.updateBusinessLogo = ((...args: Parameters<typeof firebaseProvider.updateBusinessLogo>) =>
  resolveImplementation("updateBusinessLogo")(...args)) as typeof firebaseProvider.updateBusinessLogo

export const fetchAllSettings: typeof firebaseProvider.fetchAllSettings = ((...args: Parameters<typeof firebaseProvider.fetchAllSettings>) =>
  resolveImplementation("fetchAllSettings")(...args)) as typeof firebaseProvider.fetchAllSettings

export const subscribeToSettings: typeof firebaseProvider.subscribeToSettings = ((...args: Parameters<typeof firebaseProvider.subscribeToSettings>) =>
  resolveImplementation("subscribeToSettings")(...args)) as typeof firebaseProvider.subscribeToSettings

export const fetchUserProfileFromDb: typeof firebaseProvider.fetchUserProfileFromDb = ((...args: Parameters<typeof firebaseProvider.fetchUserProfileFromDb>) =>
  resolveImplementation("fetchUserProfileFromDb")(...args)) as typeof firebaseProvider.fetchUserProfileFromDb

export const updateUserProfileInDb: typeof firebaseProvider.updateUserProfileInDb = ((...args: Parameters<typeof firebaseProvider.updateUserProfileInDb>) =>
  resolveImplementation("updateUserProfileInDb")(...args)) as typeof firebaseProvider.updateUserProfileInDb

export const checkUserExists: typeof firebaseProvider.checkUserExists = ((...args: Parameters<typeof firebaseProvider.checkUserExists>) =>
  resolveImplementation("checkUserExists")(...args)) as typeof firebaseProvider.checkUserExists

export const initializeUserSettingsInDb: typeof firebaseProvider.initializeUserSettingsInDb = ((...args: Parameters<typeof firebaseProvider.initializeUserSettingsInDb>) =>
  resolveImplementation("initializeUserSettingsInDb")(...args)) as typeof firebaseProvider.initializeUserSettingsInDb

export const checkSettingsPermission: typeof firebaseProvider.checkSettingsPermission = ((...args: Parameters<typeof firebaseProvider.checkSettingsPermission>) =>
  resolveImplementation("checkSettingsPermission")(...args)) as typeof firebaseProvider.checkSettingsPermission
