// Generated by scripts/generate-data-layer.cjs. Do not edit by hand.
import * as firebaseProvider from "../rtdatabase/Stock"
import * as supabaseProvider from "../providers/supabase/Stock"
import { getModuleProvider } from "./providerRegistry"

type ProviderModule = typeof firebaseProvider
type ProviderFn<T extends keyof ProviderModule> = ProviderModule[T] extends (...args: infer Args) => infer Result
  ? (...args: Args) => Result
  : never

const resolveImplementation = <T extends keyof ProviderModule>(name: T): ProviderFn<T> => {
  const provider = getModuleProvider("Stock")
  const source = provider === "supabase" ? (supabaseProvider as ProviderModule) : (firebaseProvider as ProviderModule)
  const implementation = source[name]
  if (typeof implementation !== "function") {
    throw new Error(`[data-provider] ${String(name)} is not implemented for provider "${provider}" in module "Stock".`)
  }
  return implementation as ProviderFn<T>
}

export const deleteLocation: typeof firebaseProvider.deleteLocation = ((...args: Parameters<typeof firebaseProvider.deleteLocation>) =>
  resolveImplementation("deleteLocation")(...args)) as typeof firebaseProvider.deleteLocation

export const addSalesDivision: typeof firebaseProvider.addSalesDivision = ((...args: Parameters<typeof firebaseProvider.addSalesDivision>) =>
  resolveImplementation("addSalesDivision")(...args)) as typeof firebaseProvider.addSalesDivision

export const updateSalesDivision: typeof firebaseProvider.updateSalesDivision = ((...args: Parameters<typeof firebaseProvider.updateSalesDivision>) =>
  resolveImplementation("updateSalesDivision")(...args)) as typeof firebaseProvider.updateSalesDivision

export const deleteSalesDivision: typeof firebaseProvider.deleteSalesDivision = ((...args: Parameters<typeof firebaseProvider.deleteSalesDivision>) =>
  resolveImplementation("deleteSalesDivision")(...args)) as typeof firebaseProvider.deleteSalesDivision

export const addSale: typeof firebaseProvider.addSale = ((...args: Parameters<typeof firebaseProvider.addSale>) =>
  resolveImplementation("addSale")(...args)) as typeof firebaseProvider.addSale

export const updateSale: typeof firebaseProvider.updateSale = ((...args: Parameters<typeof firebaseProvider.updateSale>) =>
  resolveImplementation("updateSale")(...args)) as typeof firebaseProvider.updateSale

export const deleteSale: typeof firebaseProvider.deleteSale = ((...args: Parameters<typeof firebaseProvider.deleteSale>) =>
  resolveImplementation("deleteSale")(...args)) as typeof firebaseProvider.deleteSale

export const addTaxRate: typeof firebaseProvider.addTaxRate = ((...args: Parameters<typeof firebaseProvider.addTaxRate>) =>
  resolveImplementation("addTaxRate")(...args)) as typeof firebaseProvider.addTaxRate

export const updateSalesCategory: typeof firebaseProvider.updateSalesCategory = ((...args: Parameters<typeof firebaseProvider.updateSalesCategory>) =>
  resolveImplementation("updateSalesCategory")(...args)) as typeof firebaseProvider.updateSalesCategory

export const deleteSalesCategory: typeof firebaseProvider.deleteSalesCategory = ((...args: Parameters<typeof firebaseProvider.deleteSalesCategory>) =>
  resolveImplementation("deleteSalesCategory")(...args)) as typeof firebaseProvider.deleteSalesCategory

export const recordSale: typeof firebaseProvider.recordSale = ((...args: Parameters<typeof firebaseProvider.recordSale>) =>
  resolveImplementation("recordSale")(...args)) as typeof firebaseProvider.recordSale

export const fetchOpenBills: typeof firebaseProvider.fetchOpenBills = ((...args: Parameters<typeof firebaseProvider.fetchOpenBills>) =>
  resolveImplementation("fetchOpenBills")(...args)) as typeof firebaseProvider.fetchOpenBills

export const fetchClosedBills: typeof firebaseProvider.fetchClosedBills = ((...args: Parameters<typeof firebaseProvider.fetchClosedBills>) =>
  resolveImplementation("fetchClosedBills")(...args)) as typeof firebaseProvider.fetchClosedBills

export const saveBill: typeof firebaseProvider.saveBill = ((...args: Parameters<typeof firebaseProvider.saveBill>) =>
  resolveImplementation("saveBill")(...args)) as typeof firebaseProvider.saveBill

export const fetchProducts: typeof firebaseProvider.fetchProducts = ((...args: Parameters<typeof firebaseProvider.fetchProducts>) =>
  resolveImplementation("fetchProducts")(...args)) as typeof firebaseProvider.fetchProducts

export const fetchProductById: typeof firebaseProvider.fetchProductById = ((...args: Parameters<typeof firebaseProvider.fetchProductById>) =>
  resolveImplementation("fetchProductById")(...args)) as typeof firebaseProvider.fetchProductById

export const addProduct: typeof firebaseProvider.addProduct = ((...args: Parameters<typeof firebaseProvider.addProduct>) =>
  resolveImplementation("addProduct")(...args)) as typeof firebaseProvider.addProduct

export const createProduct: typeof firebaseProvider.createProduct = ((...args: Parameters<typeof firebaseProvider.createProduct>) =>
  resolveImplementation("createProduct")(...args)) as typeof firebaseProvider.createProduct

export const updateProduct: typeof firebaseProvider.updateProduct = ((...args: Parameters<typeof firebaseProvider.updateProduct>) =>
  resolveImplementation("updateProduct")(...args)) as typeof firebaseProvider.updateProduct

export const deleteProduct: typeof firebaseProvider.deleteProduct = ((...args: Parameters<typeof firebaseProvider.deleteProduct>) =>
  resolveImplementation("deleteProduct")(...args)) as typeof firebaseProvider.deleteProduct

export const fetchSales: typeof firebaseProvider.fetchSales = ((...args: Parameters<typeof firebaseProvider.fetchSales>) =>
  resolveImplementation("fetchSales")(...args)) as typeof firebaseProvider.fetchSales

export const fetchProductsLegacy: typeof firebaseProvider.fetchProductsLegacy = ((...args: Parameters<typeof firebaseProvider.fetchProductsLegacy>) =>
  resolveImplementation("fetchProductsLegacy")(...args)) as typeof firebaseProvider.fetchProductsLegacy

export const fetchProductByIdLegacy: typeof firebaseProvider.fetchProductByIdLegacy = ((...args: Parameters<typeof firebaseProvider.fetchProductByIdLegacy>) =>
  resolveImplementation("fetchProductByIdLegacy")(...args)) as typeof firebaseProvider.fetchProductByIdLegacy

export const subscribeToPaymentTypes: typeof firebaseProvider.subscribeToPaymentTypes = ((...args: Parameters<typeof firebaseProvider.subscribeToPaymentTypes>) =>
  resolveImplementation("subscribeToPaymentTypes")(...args)) as typeof firebaseProvider.subscribeToPaymentTypes

export const updatePaymentType: typeof firebaseProvider.updatePaymentType = ((...args: Parameters<typeof firebaseProvider.updatePaymentType>) =>
  resolveImplementation("updatePaymentType")(...args)) as typeof firebaseProvider.updatePaymentType

export const deletePaymentType: typeof firebaseProvider.deletePaymentType = ((...args: Parameters<typeof firebaseProvider.deletePaymentType>) =>
  resolveImplementation("deletePaymentType")(...args)) as typeof firebaseProvider.deletePaymentType

export const addPaymentType: typeof firebaseProvider.addPaymentType = ((...args: Parameters<typeof firebaseProvider.addPaymentType>) =>
  resolveImplementation("addPaymentType")(...args)) as typeof firebaseProvider.addPaymentType

export const subscribeToDevices: typeof firebaseProvider.subscribeToDevices = ((...args: Parameters<typeof firebaseProvider.subscribeToDevices>) =>
  resolveImplementation("subscribeToDevices")(...args)) as typeof firebaseProvider.subscribeToDevices

export const subscribeToLocations: typeof firebaseProvider.subscribeToLocations = ((...args: Parameters<typeof firebaseProvider.subscribeToLocations>) =>
  resolveImplementation("subscribeToLocations")(...args)) as typeof firebaseProvider.subscribeToLocations

export const addDevice: typeof firebaseProvider.addDevice = ((...args: Parameters<typeof firebaseProvider.addDevice>) =>
  resolveImplementation("addDevice")(...args)) as typeof firebaseProvider.addDevice

export const updateDevice: typeof firebaseProvider.updateDevice = ((...args: Parameters<typeof firebaseProvider.updateDevice>) =>
  resolveImplementation("updateDevice")(...args)) as typeof firebaseProvider.updateDevice

export const deleteDevice: typeof firebaseProvider.deleteDevice = ((...args: Parameters<typeof firebaseProvider.deleteDevice>) =>
  resolveImplementation("deleteDevice")(...args)) as typeof firebaseProvider.deleteDevice

export const subscribeToCorrections: typeof firebaseProvider.subscribeToCorrections = ((...args: Parameters<typeof firebaseProvider.subscribeToCorrections>) =>
  resolveImplementation("subscribeToCorrections")(...args)) as typeof firebaseProvider.subscribeToCorrections

export const addCorrection: typeof firebaseProvider.addCorrection = ((...args: Parameters<typeof firebaseProvider.addCorrection>) =>
  resolveImplementation("addCorrection")(...args)) as typeof firebaseProvider.addCorrection

export const updateCorrection: typeof firebaseProvider.updateCorrection = ((...args: Parameters<typeof firebaseProvider.updateCorrection>) =>
  resolveImplementation("updateCorrection")(...args)) as typeof firebaseProvider.updateCorrection

export const deleteCorrection: typeof firebaseProvider.deleteCorrection = ((...args: Parameters<typeof firebaseProvider.deleteCorrection>) =>
  resolveImplementation("deleteCorrection")(...args)) as typeof firebaseProvider.deleteCorrection

export const saveTillScreen: typeof firebaseProvider.saveTillScreen = ((...args: Parameters<typeof firebaseProvider.saveTillScreen>) =>
  resolveImplementation("saveTillScreen")(...args)) as typeof firebaseProvider.saveTillScreen

export const fetchStockHistory: typeof firebaseProvider.fetchStockHistory = ((...args: Parameters<typeof firebaseProvider.fetchStockHistory>) =>
  resolveImplementation("fetchStockHistory")(...args)) as typeof firebaseProvider.fetchStockHistory

export const createBill: typeof firebaseProvider.createBill = ((...args: Parameters<typeof firebaseProvider.createBill>) =>
  resolveImplementation("createBill")(...args)) as typeof firebaseProvider.createBill

export const updateBill: typeof firebaseProvider.updateBill = ((...args: Parameters<typeof firebaseProvider.updateBill>) =>
  resolveImplementation("updateBill")(...args)) as typeof firebaseProvider.updateBill

export const deleteBill: typeof firebaseProvider.deleteBill = ((...args: Parameters<typeof firebaseProvider.deleteBill>) =>
  resolveImplementation("deleteBill")(...args)) as typeof firebaseProvider.deleteBill

export const fetchBill: typeof firebaseProvider.fetchBill = ((...args: Parameters<typeof firebaseProvider.fetchBill>) =>
  resolveImplementation("fetchBill")(...args)) as typeof firebaseProvider.fetchBill

export const fetchPaymentTypes: typeof firebaseProvider.fetchPaymentTypes = ((...args: Parameters<typeof firebaseProvider.fetchPaymentTypes>) =>
  resolveImplementation("fetchPaymentTypes")(...args)) as typeof firebaseProvider.fetchPaymentTypes

export const fetchDevices: typeof firebaseProvider.fetchDevices = ((...args: Parameters<typeof firebaseProvider.fetchDevices>) =>
  resolveImplementation("fetchDevices")(...args)) as typeof firebaseProvider.fetchDevices

export const fetchCorrections: typeof firebaseProvider.fetchCorrections = ((...args: Parameters<typeof firebaseProvider.fetchCorrections>) =>
  resolveImplementation("fetchCorrections")(...args)) as typeof firebaseProvider.fetchCorrections

export const fetchDiscounts: typeof firebaseProvider.fetchDiscounts = ((...args: Parameters<typeof firebaseProvider.fetchDiscounts>) =>
  resolveImplementation("fetchDiscounts")(...args)) as typeof firebaseProvider.fetchDiscounts

export const addDiscount: typeof firebaseProvider.addDiscount = ((...args: Parameters<typeof firebaseProvider.addDiscount>) =>
  resolveImplementation("addDiscount")(...args)) as typeof firebaseProvider.addDiscount

export const updateDiscount: typeof firebaseProvider.updateDiscount = ((...args: Parameters<typeof firebaseProvider.updateDiscount>) =>
  resolveImplementation("updateDiscount")(...args)) as typeof firebaseProvider.updateDiscount

export const deleteDiscount: typeof firebaseProvider.deleteDiscount = ((...args: Parameters<typeof firebaseProvider.deleteDiscount>) =>
  resolveImplementation("deleteDiscount")(...args)) as typeof firebaseProvider.deleteDiscount

export const fetchPromotions: typeof firebaseProvider.fetchPromotions = ((...args: Parameters<typeof firebaseProvider.fetchPromotions>) =>
  resolveImplementation("fetchPromotions")(...args)) as typeof firebaseProvider.fetchPromotions

export const addPromotion: typeof firebaseProvider.addPromotion = ((...args: Parameters<typeof firebaseProvider.addPromotion>) =>
  resolveImplementation("addPromotion")(...args)) as typeof firebaseProvider.addPromotion

export const updatePromotion: typeof firebaseProvider.updatePromotion = ((...args: Parameters<typeof firebaseProvider.updatePromotion>) =>
  resolveImplementation("updatePromotion")(...args)) as typeof firebaseProvider.updatePromotion

export const deletePromotion: typeof firebaseProvider.deletePromotion = ((...args: Parameters<typeof firebaseProvider.deletePromotion>) =>
  resolveImplementation("deletePromotion")(...args)) as typeof firebaseProvider.deletePromotion

export const fetchSalesDivisions: typeof firebaseProvider.fetchSalesDivisions = ((...args: Parameters<typeof firebaseProvider.fetchSalesDivisions>) =>
  resolveImplementation("fetchSalesDivisions")(...args)) as typeof firebaseProvider.fetchSalesDivisions

export const fetchCategories: typeof firebaseProvider.fetchCategories = ((...args: Parameters<typeof firebaseProvider.fetchCategories>) =>
  resolveImplementation("fetchCategories")(...args)) as typeof firebaseProvider.fetchCategories

export const fetchSubcategories: typeof firebaseProvider.fetchSubcategories = ((...args: Parameters<typeof firebaseProvider.fetchSubcategories>) =>
  resolveImplementation("fetchSubcategories")(...args)) as typeof firebaseProvider.fetchSubcategories

export const addProductLegacy: typeof firebaseProvider.addProductLegacy = ((...args: Parameters<typeof firebaseProvider.addProductLegacy>) =>
  resolveImplementation("addProductLegacy")(...args)) as typeof firebaseProvider.addProductLegacy

export const updateProductLegacy: typeof firebaseProvider.updateProductLegacy = ((...args: Parameters<typeof firebaseProvider.updateProductLegacy>) =>
  resolveImplementation("updateProductLegacy")(...args)) as typeof firebaseProvider.updateProductLegacy

export const deleteProductLegacy: typeof firebaseProvider.deleteProductLegacy = ((...args: Parameters<typeof firebaseProvider.deleteProductLegacy>) =>
  resolveImplementation("deleteProductLegacy")(...args)) as typeof firebaseProvider.deleteProductLegacy

export const updatePurchase: typeof firebaseProvider.updatePurchase = ((...args: Parameters<typeof firebaseProvider.updatePurchase>) =>
  resolveImplementation("updatePurchase")(...args)) as typeof firebaseProvider.updatePurchase

export const createPurchase: typeof firebaseProvider.createPurchase = ((...args: Parameters<typeof firebaseProvider.createPurchase>) =>
  resolveImplementation("createPurchase")(...args)) as typeof firebaseProvider.createPurchase

export const savePurchase: typeof firebaseProvider.savePurchase = ((...args: Parameters<typeof firebaseProvider.savePurchase>) =>
  resolveImplementation("savePurchase")(...args)) as typeof firebaseProvider.savePurchase

export const deletePurchase: typeof firebaseProvider.deletePurchase = ((...args: Parameters<typeof firebaseProvider.deletePurchase>) =>
  resolveImplementation("deletePurchase")(...args)) as typeof firebaseProvider.deletePurchase

export const fetchAllPurchases: typeof firebaseProvider.fetchAllPurchases = ((...args: Parameters<typeof firebaseProvider.fetchAllPurchases>) =>
  resolveImplementation("fetchAllPurchases")(...args)) as typeof firebaseProvider.fetchAllPurchases

export const fetchAllStockCounts: typeof firebaseProvider.fetchAllStockCounts = ((...args: Parameters<typeof firebaseProvider.fetchAllStockCounts>) =>
  resolveImplementation("fetchAllStockCounts")(...args)) as typeof firebaseProvider.fetchAllStockCounts

export const saveStockCount: typeof firebaseProvider.saveStockCount = ((...args: Parameters<typeof firebaseProvider.saveStockCount>) =>
  resolveImplementation("saveStockCount")(...args)) as typeof firebaseProvider.saveStockCount

export const fetchLatestCountsForProducts: typeof firebaseProvider.fetchLatestCountsForProducts = ((...args: Parameters<typeof firebaseProvider.fetchLatestCountsForProducts>) =>
  resolveImplementation("fetchLatestCountsForProducts")(...args)) as typeof firebaseProvider.fetchLatestCountsForProducts

export const transferStock: typeof firebaseProvider.transferStock = ((...args: Parameters<typeof firebaseProvider.transferStock>) =>
  resolveImplementation("transferStock")(...args)) as typeof firebaseProvider.transferStock

export const fetchStockLocations: typeof firebaseProvider.fetchStockLocations = ((...args: Parameters<typeof firebaseProvider.fetchStockLocations>) =>
  resolveImplementation("fetchStockLocations")(...args)) as typeof firebaseProvider.fetchStockLocations

export const addStockLocation: typeof firebaseProvider.addStockLocation = ((...args: Parameters<typeof firebaseProvider.addStockLocation>) =>
  resolveImplementation("addStockLocation")(...args)) as typeof firebaseProvider.addStockLocation

export const updateStockLocation: typeof firebaseProvider.updateStockLocation = ((...args: Parameters<typeof firebaseProvider.updateStockLocation>) =>
  resolveImplementation("updateStockLocation")(...args)) as typeof firebaseProvider.updateStockLocation

export const deleteStockLocation: typeof firebaseProvider.deleteStockLocation = ((...args: Parameters<typeof firebaseProvider.deleteStockLocation>) =>
  resolveImplementation("deleteStockLocation")(...args)) as typeof firebaseProvider.deleteStockLocation

export const fetchFloorPlans: typeof firebaseProvider.fetchFloorPlans = ((...args: Parameters<typeof firebaseProvider.fetchFloorPlans>) =>
  resolveImplementation("fetchFloorPlans")(...args)) as typeof firebaseProvider.fetchFloorPlans

export const fetchTillScreens: typeof firebaseProvider.fetchTillScreens = ((...args: Parameters<typeof firebaseProvider.fetchTillScreens>) =>
  resolveImplementation("fetchTillScreens")(...args)) as typeof firebaseProvider.fetchTillScreens

export const addFloorPlan: typeof firebaseProvider.addFloorPlan = ((...args: Parameters<typeof firebaseProvider.addFloorPlan>) =>
  resolveImplementation("addFloorPlan")(...args)) as typeof firebaseProvider.addFloorPlan

export const updateFloorPlan: typeof firebaseProvider.updateFloorPlan = ((...args: Parameters<typeof firebaseProvider.updateFloorPlan>) =>
  resolveImplementation("updateFloorPlan")(...args)) as typeof firebaseProvider.updateFloorPlan

export const addFloorPlanWithBasePath: typeof firebaseProvider.addFloorPlanWithBasePath = ((...args: Parameters<typeof firebaseProvider.addFloorPlanWithBasePath>) =>
  resolveImplementation("addFloorPlanWithBasePath")(...args)) as typeof firebaseProvider.addFloorPlanWithBasePath

export const deleteFloorPlan: typeof firebaseProvider.deleteFloorPlan = ((...args: Parameters<typeof firebaseProvider.deleteFloorPlan>) =>
  resolveImplementation("deleteFloorPlan")(...args)) as typeof firebaseProvider.deleteFloorPlan

export const fetchTables: typeof firebaseProvider.fetchTables = ((...args: Parameters<typeof firebaseProvider.fetchTables>) =>
  resolveImplementation("fetchTables")(...args)) as typeof firebaseProvider.fetchTables

export const addTable: typeof firebaseProvider.addTable = ((...args: Parameters<typeof firebaseProvider.addTable>) =>
  resolveImplementation("addTable")(...args)) as typeof firebaseProvider.addTable

export const updateTable: typeof firebaseProvider.updateTable = ((...args: Parameters<typeof firebaseProvider.updateTable>) =>
  resolveImplementation("updateTable")(...args)) as typeof firebaseProvider.updateTable

export const deleteTable: typeof firebaseProvider.deleteTable = ((...args: Parameters<typeof firebaseProvider.deleteTable>) =>
  resolveImplementation("deleteTable")(...args)) as typeof firebaseProvider.deleteTable

export const updateTillScreen: typeof firebaseProvider.updateTillScreen = ((...args: Parameters<typeof firebaseProvider.updateTillScreen>) =>
  resolveImplementation("updateTillScreen")(...args)) as typeof firebaseProvider.updateTillScreen

export const saveTicket: typeof firebaseProvider.saveTicket = ((...args: Parameters<typeof firebaseProvider.saveTicket>) =>
  resolveImplementation("saveTicket")(...args)) as typeof firebaseProvider.saveTicket

export const updateTicketInDb: typeof firebaseProvider.updateTicketInDb = ((...args: Parameters<typeof firebaseProvider.updateTicketInDb>) =>
  resolveImplementation("updateTicketInDb")(...args)) as typeof firebaseProvider.updateTicketInDb

export const deleteTicketFromDb: typeof firebaseProvider.deleteTicketFromDb = ((...args: Parameters<typeof firebaseProvider.deleteTicketFromDb>) =>
  resolveImplementation("deleteTicketFromDb")(...args)) as typeof firebaseProvider.deleteTicketFromDb

export const fetchTickets: typeof firebaseProvider.fetchTickets = ((...args: Parameters<typeof firebaseProvider.fetchTickets>) =>
  resolveImplementation("fetchTickets")(...args)) as typeof firebaseProvider.fetchTickets

export const saveTicketSale: typeof firebaseProvider.saveTicketSale = ((...args: Parameters<typeof firebaseProvider.saveTicketSale>) =>
  resolveImplementation("saveTicketSale")(...args)) as typeof firebaseProvider.saveTicketSale

export const getTicketSaleByQR: typeof firebaseProvider.getTicketSaleByQR = ((...args: Parameters<typeof firebaseProvider.getTicketSaleByQR>) =>
  resolveImplementation("getTicketSaleByQR")(...args)) as typeof firebaseProvider.getTicketSaleByQR

export const updateTicketSaleInDb: typeof firebaseProvider.updateTicketSaleInDb = ((...args: Parameters<typeof firebaseProvider.updateTicketSaleInDb>) =>
  resolveImplementation("updateTicketSaleInDb")(...args)) as typeof firebaseProvider.updateTicketSaleInDb

export const fetchTicketSales: typeof firebaseProvider.fetchTicketSales = ((...args: Parameters<typeof firebaseProvider.fetchTicketSales>) =>
  resolveImplementation("fetchTicketSales")(...args)) as typeof firebaseProvider.fetchTicketSales

export const saveBagCheckItem: typeof firebaseProvider.saveBagCheckItem = ((...args: Parameters<typeof firebaseProvider.saveBagCheckItem>) =>
  resolveImplementation("saveBagCheckItem")(...args)) as typeof firebaseProvider.saveBagCheckItem

export const updateBagCheckItemInDb: typeof firebaseProvider.updateBagCheckItemInDb = ((...args: Parameters<typeof firebaseProvider.updateBagCheckItemInDb>) =>
  resolveImplementation("updateBagCheckItemInDb")(...args)) as typeof firebaseProvider.updateBagCheckItemInDb

export const getBagCheckItemByQR: typeof firebaseProvider.getBagCheckItemByQR = ((...args: Parameters<typeof firebaseProvider.getBagCheckItemByQR>) =>
  resolveImplementation("getBagCheckItemByQR")(...args)) as typeof firebaseProvider.getBagCheckItemByQR

export const fetchBagCheckItems: typeof firebaseProvider.fetchBagCheckItems = ((...args: Parameters<typeof firebaseProvider.fetchBagCheckItems>) =>
  resolveImplementation("fetchBagCheckItems")(...args)) as typeof firebaseProvider.fetchBagCheckItems

export const fetchBagCheckConfig: typeof firebaseProvider.fetchBagCheckConfig = ((...args: Parameters<typeof firebaseProvider.fetchBagCheckConfig>) =>
  resolveImplementation("fetchBagCheckConfig")(...args)) as typeof firebaseProvider.fetchBagCheckConfig

export const saveBagCheckConfig: typeof firebaseProvider.saveBagCheckConfig = ((...args: Parameters<typeof firebaseProvider.saveBagCheckConfig>) =>
  resolveImplementation("saveBagCheckConfig")(...args)) as typeof firebaseProvider.saveBagCheckConfig

export const updateStockCountStatus: typeof firebaseProvider.updateStockCountStatus = ((...args: Parameters<typeof firebaseProvider.updateStockCountStatus>) =>
  resolveImplementation("updateStockCountStatus")(...args)) as typeof firebaseProvider.updateStockCountStatus

export const updatePurchaseStatus: typeof firebaseProvider.updatePurchaseStatus = ((...args: Parameters<typeof firebaseProvider.updatePurchaseStatus>) =>
  resolveImplementation("updatePurchaseStatus")(...args)) as typeof firebaseProvider.updatePurchaseStatus

export const combineDuplicateStockItems: typeof firebaseProvider.combineDuplicateStockItems = ((...args: Parameters<typeof firebaseProvider.combineDuplicateStockItems>) =>
  resolveImplementation("combineDuplicateStockItems")(...args)) as typeof firebaseProvider.combineDuplicateStockItems

export const combineDuplicatePurchaseItems: typeof firebaseProvider.combineDuplicatePurchaseItems = ((...args: Parameters<typeof firebaseProvider.combineDuplicatePurchaseItems>) =>
  resolveImplementation("combineDuplicatePurchaseItems")(...args)) as typeof firebaseProvider.combineDuplicatePurchaseItems

export const createSaleRecord: typeof firebaseProvider.createSaleRecord = ((...args: Parameters<typeof firebaseProvider.createSaleRecord>) =>
  resolveImplementation("createSaleRecord")(...args)) as typeof firebaseProvider.createSaleRecord

export const updateProductStockLevel: typeof firebaseProvider.updateProductStockLevel = ((...args: Parameters<typeof firebaseProvider.updateProductStockLevel>) =>
  resolveImplementation("updateProductStockLevel")(...args)) as typeof firebaseProvider.updateProductStockLevel

export const saveParLevelProfile: typeof firebaseProvider.saveParLevelProfile = ((...args: Parameters<typeof firebaseProvider.saveParLevelProfile>) =>
  resolveImplementation("saveParLevelProfile")(...args)) as typeof firebaseProvider.saveParLevelProfile

export const fetchParProfiles: typeof firebaseProvider.fetchParProfiles = ((...args: Parameters<typeof firebaseProvider.fetchParProfiles>) =>
  resolveImplementation("fetchParProfiles")(...args)) as typeof firebaseProvider.fetchParProfiles

export const deleteParProfile: typeof firebaseProvider.deleteParProfile = ((...args: Parameters<typeof firebaseProvider.deleteParProfile>) =>
  resolveImplementation("deleteParProfile")(...args)) as typeof firebaseProvider.deleteParProfile

export const fetchCourses: typeof firebaseProvider.fetchCourses = ((...args: Parameters<typeof firebaseProvider.fetchCourses>) =>
  resolveImplementation("fetchCourses")(...args)) as typeof firebaseProvider.fetchCourses

export const saveCourse: typeof firebaseProvider.saveCourse = ((...args: Parameters<typeof firebaseProvider.saveCourse>) =>
  resolveImplementation("saveCourse")(...args)) as typeof firebaseProvider.saveCourse

export const updateCourse: typeof firebaseProvider.updateCourse = ((...args: Parameters<typeof firebaseProvider.updateCourse>) =>
  resolveImplementation("updateCourse")(...args)) as typeof firebaseProvider.updateCourse

export const deleteCourse: typeof firebaseProvider.deleteCourse = ((...args: Parameters<typeof firebaseProvider.deleteCourse>) =>
  resolveImplementation("deleteCourse")(...args)) as typeof firebaseProvider.deleteCourse

export const saveMeasureToBasePath: typeof firebaseProvider.saveMeasureToBasePath = ((...args: Parameters<typeof firebaseProvider.saveMeasureToBasePath>) =>
  resolveImplementation("saveMeasureToBasePath")(...args)) as typeof firebaseProvider.saveMeasureToBasePath

export const updateMeasureInBasePath: typeof firebaseProvider.updateMeasureInBasePath = ((...args: Parameters<typeof firebaseProvider.updateMeasureInBasePath>) =>
  resolveImplementation("updateMeasureInBasePath")(...args)) as typeof firebaseProvider.updateMeasureInBasePath

export const deleteMeasureFromBasePath: typeof firebaseProvider.deleteMeasureFromBasePath = ((...args: Parameters<typeof firebaseProvider.deleteMeasureFromBasePath>) =>
  resolveImplementation("deleteMeasureFromBasePath")(...args)) as typeof firebaseProvider.deleteMeasureFromBasePath

export const subscribeStockEmailMessages: typeof firebaseProvider.subscribeStockEmailMessages = ((...args: Parameters<typeof firebaseProvider.subscribeStockEmailMessages>) =>
  resolveImplementation("subscribeStockEmailMessages")(...args)) as typeof firebaseProvider.subscribeStockEmailMessages

export const fetchStockEmailConfig: typeof firebaseProvider.fetchStockEmailConfig = ((...args: Parameters<typeof firebaseProvider.fetchStockEmailConfig>) =>
  resolveImplementation("fetchStockEmailConfig")(...args)) as typeof firebaseProvider.fetchStockEmailConfig

export const saveStockEmailConfig: typeof firebaseProvider.saveStockEmailConfig = ((...args: Parameters<typeof firebaseProvider.saveStockEmailConfig>) =>
  resolveImplementation("saveStockEmailConfig")(...args)) as typeof firebaseProvider.saveStockEmailConfig

export const subscribeFavoriteProductIds: typeof firebaseProvider.subscribeFavoriteProductIds = ((...args: Parameters<typeof firebaseProvider.subscribeFavoriteProductIds>) =>
  resolveImplementation("subscribeFavoriteProductIds")(...args)) as typeof firebaseProvider.subscribeFavoriteProductIds

export const addFavoriteProduct: typeof firebaseProvider.addFavoriteProduct = ((...args: Parameters<typeof firebaseProvider.addFavoriteProduct>) =>
  resolveImplementation("addFavoriteProduct")(...args)) as typeof firebaseProvider.addFavoriteProduct

export const removeFavoriteProduct: typeof firebaseProvider.removeFavoriteProduct = ((...args: Parameters<typeof firebaseProvider.removeFavoriteProduct>) =>
  resolveImplementation("removeFavoriteProduct")(...args)) as typeof firebaseProvider.removeFavoriteProduct

export const fetchStockSettings: typeof firebaseProvider.fetchStockSettings = ((...args: Parameters<typeof firebaseProvider.fetchStockSettings>) =>
  resolveImplementation("fetchStockSettings")(...args)) as typeof firebaseProvider.fetchStockSettings

export const saveStockSettings: typeof firebaseProvider.saveStockSettings = ((...args: Parameters<typeof firebaseProvider.saveStockSettings>) =>
  resolveImplementation("saveStockSettings")(...args)) as typeof firebaseProvider.saveStockSettings

export const fetchStockTargets: typeof firebaseProvider.fetchStockTargets = ((...args: Parameters<typeof firebaseProvider.fetchStockTargets>) =>
  resolveImplementation("fetchStockTargets")(...args)) as typeof firebaseProvider.fetchStockTargets

export const saveStockTarget: typeof firebaseProvider.saveStockTarget = ((...args: Parameters<typeof firebaseProvider.saveStockTarget>) =>
  resolveImplementation("saveStockTarget")(...args)) as typeof firebaseProvider.saveStockTarget

export const deleteStockTarget: typeof firebaseProvider.deleteStockTarget = ((...args: Parameters<typeof firebaseProvider.deleteStockTarget>) =>
  resolveImplementation("deleteStockTarget")(...args)) as typeof firebaseProvider.deleteStockTarget

export const fetchStockIntegrations: typeof firebaseProvider.fetchStockIntegrations = ((...args: Parameters<typeof firebaseProvider.fetchStockIntegrations>) =>
  resolveImplementation("fetchStockIntegrations")(...args)) as typeof firebaseProvider.fetchStockIntegrations

export const saveStockIntegration: typeof firebaseProvider.saveStockIntegration = ((...args: Parameters<typeof firebaseProvider.saveStockIntegration>) =>
  resolveImplementation("saveStockIntegration")(...args)) as typeof firebaseProvider.saveStockIntegration

export const getStockCount: typeof firebaseProvider.getStockCount = ((...args: Parameters<typeof firebaseProvider.getStockCount>) =>
  resolveImplementation("getStockCount")(...args)) as typeof firebaseProvider.getStockCount

export const subscribeTillScreens: typeof firebaseProvider.subscribeTillScreens = ((...args: Parameters<typeof firebaseProvider.subscribeTillScreens>) =>
  resolveImplementation("subscribeTillScreens")(...args)) as typeof firebaseProvider.subscribeTillScreens

export const deleteTillScreen: typeof firebaseProvider.deleteTillScreen = ((...args: Parameters<typeof firebaseProvider.deleteTillScreen>) =>
  resolveImplementation("deleteTillScreen")(...args)) as typeof firebaseProvider.deleteTillScreen

export const setDefaultTillScreen: typeof firebaseProvider.setDefaultTillScreen = ((...args: Parameters<typeof firebaseProvider.setDefaultTillScreen>) =>
  resolveImplementation("setDefaultTillScreen")(...args)) as typeof firebaseProvider.setDefaultTillScreen

export const fetchGroups: typeof firebaseProvider.fetchGroups = ((...args: Parameters<typeof firebaseProvider.fetchGroups>) =>
  resolveImplementation("fetchGroups")(...args)) as typeof firebaseProvider.fetchGroups

export const saveGroup: typeof firebaseProvider.saveGroup = ((...args: Parameters<typeof firebaseProvider.saveGroup>) =>
  resolveImplementation("saveGroup")(...args)) as typeof firebaseProvider.saveGroup

export const getStockCountHistory: typeof firebaseProvider.getStockCountHistory = ((...args: Parameters<typeof firebaseProvider.getStockCountHistory>) =>
  resolveImplementation("getStockCountHistory")(...args)) as typeof firebaseProvider.getStockCountHistory

export const getPurchasesHistory: typeof firebaseProvider.getPurchasesHistory = ((...args: Parameters<typeof firebaseProvider.getPurchasesHistory>) =>
  resolveImplementation("getPurchasesHistory")(...args)) as typeof firebaseProvider.getPurchasesHistory

export const getSalesHistory: typeof firebaseProvider.getSalesHistory = ((...args: Parameters<typeof firebaseProvider.getSalesHistory>) =>
  resolveImplementation("getSalesHistory")(...args)) as typeof firebaseProvider.getSalesHistory

export const fetchPurchases: typeof firebaseProvider.fetchPurchases = ((...args: Parameters<typeof firebaseProvider.fetchPurchases>) =>
  resolveImplementation("fetchPurchases")(...args)) as typeof firebaseProvider.fetchPurchases

export const fetchPurchasesHistory: typeof firebaseProvider.fetchPurchasesHistory = ((...args: Parameters<typeof firebaseProvider.fetchPurchasesHistory>) =>
  resolveImplementation("fetchPurchasesHistory")(...args)) as typeof firebaseProvider.fetchPurchasesHistory

export const fetchSalesHistory: typeof firebaseProvider.fetchSalesHistory = ((...args: Parameters<typeof firebaseProvider.fetchSalesHistory>) =>
  resolveImplementation("fetchSalesHistory")(...args)) as typeof firebaseProvider.fetchSalesHistory

export const saveProduct: typeof firebaseProvider.saveProduct = ((...args: Parameters<typeof firebaseProvider.saveProduct>) =>
  resolveImplementation("saveProduct")(...args)) as typeof firebaseProvider.saveProduct

export const createMeasure: typeof firebaseProvider.createMeasure = ((...args: Parameters<typeof firebaseProvider.createMeasure>) =>
  resolveImplementation("createMeasure")(...args)) as typeof firebaseProvider.createMeasure

export const fetchMeasureData: typeof firebaseProvider.fetchMeasureData = ((...args: Parameters<typeof firebaseProvider.fetchMeasureData>) =>
  resolveImplementation("fetchMeasureData")(...args)) as typeof firebaseProvider.fetchMeasureData

export const createSupplier: typeof firebaseProvider.createSupplier = ((...args: Parameters<typeof firebaseProvider.createSupplier>) =>
  resolveImplementation("createSupplier")(...args)) as typeof firebaseProvider.createSupplier

export const updateSupplier: typeof firebaseProvider.updateSupplier = ((...args: Parameters<typeof firebaseProvider.updateSupplier>) =>
  resolveImplementation("updateSupplier")(...args)) as typeof firebaseProvider.updateSupplier

export const deleteSupplier: typeof firebaseProvider.deleteSupplier = ((...args: Parameters<typeof firebaseProvider.deleteSupplier>) =>
  resolveImplementation("deleteSupplier")(...args)) as typeof firebaseProvider.deleteSupplier

export const createCategory: typeof firebaseProvider.createCategory = ((...args: Parameters<typeof firebaseProvider.createCategory>) =>
  resolveImplementation("createCategory")(...args)) as typeof firebaseProvider.createCategory

export const updateCategory: typeof firebaseProvider.updateCategory = ((...args: Parameters<typeof firebaseProvider.updateCategory>) =>
  resolveImplementation("updateCategory")(...args)) as typeof firebaseProvider.updateCategory

export const deleteCategory: typeof firebaseProvider.deleteCategory = ((...args: Parameters<typeof firebaseProvider.deleteCategory>) =>
  resolveImplementation("deleteCategory")(...args)) as typeof firebaseProvider.deleteCategory

export const getItemMeasures: typeof firebaseProvider.getItemMeasures = ((...args: Parameters<typeof firebaseProvider.getItemMeasures>) =>
  resolveImplementation("getItemMeasures")(...args)) as typeof firebaseProvider.getItemMeasures

export const calculateCostPerUnit: typeof firebaseProvider.calculateCostPerUnit = ((...args: Parameters<typeof firebaseProvider.calculateCostPerUnit>) =>
  resolveImplementation("calculateCostPerUnit")(...args)) as typeof firebaseProvider.calculateCostPerUnit

export const calculateIngredientCost: typeof firebaseProvider.calculateIngredientCost = ((...args: Parameters<typeof firebaseProvider.calculateIngredientCost>) =>
  resolveImplementation("calculateIngredientCost")(...args)) as typeof firebaseProvider.calculateIngredientCost

export const getConversionGroup: typeof firebaseProvider.getConversionGroup = ((...args: Parameters<typeof firebaseProvider.getConversionGroup>) =>
  resolveImplementation("getConversionGroup")(...args)) as typeof firebaseProvider.getConversionGroup

export const getCompatibleMeasures: typeof firebaseProvider.getCompatibleMeasures = ((...args: Parameters<typeof firebaseProvider.getCompatibleMeasures>) =>
  resolveImplementation("getCompatibleMeasures")(...args)) as typeof firebaseProvider.getCompatibleMeasures

export const savePreset: typeof firebaseProvider.savePreset = ((...args: Parameters<typeof firebaseProvider.savePreset>) =>
  resolveImplementation("savePreset")(...args)) as typeof firebaseProvider.savePreset

export const getPresets: typeof firebaseProvider.getPresets = ((...args: Parameters<typeof firebaseProvider.getPresets>) =>
  resolveImplementation("getPresets")(...args)) as typeof firebaseProvider.getPresets

export const addPurchase: typeof firebaseProvider.addPurchase = ((...args: Parameters<typeof firebaseProvider.addPurchase>) =>
  resolveImplementation("addPurchase")(...args)) as typeof firebaseProvider.addPurchase

export const fetchPresetsFromDB: typeof firebaseProvider.fetchPresetsFromDB = ((...args: Parameters<typeof firebaseProvider.fetchPresetsFromDB>) =>
  resolveImplementation("fetchPresetsFromDB")(...args)) as typeof firebaseProvider.fetchPresetsFromDB

export const savePresetToDB: typeof firebaseProvider.savePresetToDB = ((...args: Parameters<typeof firebaseProvider.savePresetToDB>) =>
  resolveImplementation("savePresetToDB")(...args)) as typeof firebaseProvider.savePresetToDB

export const convertToBase: typeof firebaseProvider.convertToBase = ((...args: Parameters<typeof firebaseProvider.convertToBase>) =>
  resolveImplementation("convertToBase")(...args)) as typeof firebaseProvider.convertToBase

export const fetchParLevels: typeof firebaseProvider.fetchParLevels = ((...args: Parameters<typeof firebaseProvider.fetchParLevels>) =>
  resolveImplementation("fetchParLevels")(...args)) as typeof firebaseProvider.fetchParLevels

export const saveParLevel: typeof firebaseProvider.saveParLevel = ((...args: Parameters<typeof firebaseProvider.saveParLevel>) =>
  resolveImplementation("saveParLevel")(...args)) as typeof firebaseProvider.saveParLevel

export const deleteParLevel: typeof firebaseProvider.deleteParLevel = ((...args: Parameters<typeof firebaseProvider.deleteParLevel>) =>
  resolveImplementation("deleteParLevel")(...args)) as typeof firebaseProvider.deleteParLevel

export const fetchMeasures: typeof firebaseProvider.fetchMeasures = ((...args: Parameters<typeof firebaseProvider.fetchMeasures>) =>
  resolveImplementation("fetchMeasures")(...args)) as typeof firebaseProvider.fetchMeasures

export const fetchMeasuresFromBasePath: typeof firebaseProvider.fetchMeasuresFromBasePath = ((...args: Parameters<typeof firebaseProvider.fetchMeasuresFromBasePath>) =>
  resolveImplementation("fetchMeasuresFromBasePath")(...args)) as typeof firebaseProvider.fetchMeasuresFromBasePath

export const fetchSuppliers: typeof firebaseProvider.fetchSuppliers = ((...args: Parameters<typeof firebaseProvider.fetchSuppliers>) =>
  resolveImplementation("fetchSuppliers")(...args)) as typeof firebaseProvider.fetchSuppliers

export const fetchStockItems: typeof firebaseProvider.fetchStockItems = ((...args: Parameters<typeof firebaseProvider.fetchStockItems>) =>
  resolveImplementation("fetchStockItems")(...args)) as typeof firebaseProvider.fetchStockItems

export const addStockItem: typeof firebaseProvider.addStockItem = ((...args: Parameters<typeof firebaseProvider.addStockItem>) =>
  resolveImplementation("addStockItem")(...args)) as typeof firebaseProvider.addStockItem

export const updateStockItem: typeof firebaseProvider.updateStockItem = ((...args: Parameters<typeof firebaseProvider.updateStockItem>) =>
  resolveImplementation("updateStockItem")(...args)) as typeof firebaseProvider.updateStockItem

export const deleteStockItem: typeof firebaseProvider.deleteStockItem = ((...args: Parameters<typeof firebaseProvider.deleteStockItem>) =>
  resolveImplementation("deleteStockItem")(...args)) as typeof firebaseProvider.deleteStockItem

export const fetchSuppliersData: typeof firebaseProvider.fetchSuppliersData = ((...args: Parameters<typeof firebaseProvider.fetchSuppliersData>) =>
  resolveImplementation("fetchSuppliersData")(...args)) as typeof firebaseProvider.fetchSuppliersData

export const fetchSuppliersFromBasePath: typeof firebaseProvider.fetchSuppliersFromBasePath = ((...args: Parameters<typeof firebaseProvider.fetchSuppliersFromBasePath>) =>
  resolveImplementation("fetchSuppliersFromBasePath")(...args)) as typeof firebaseProvider.fetchSuppliersFromBasePath

export const addSupplier: typeof firebaseProvider.addSupplier = ((...args: Parameters<typeof firebaseProvider.addSupplier>) =>
  resolveImplementation("addSupplier")(...args)) as typeof firebaseProvider.addSupplier

export const fetchPurchaseOrders: typeof firebaseProvider.fetchPurchaseOrders = ((...args: Parameters<typeof firebaseProvider.fetchPurchaseOrders>) =>
  resolveImplementation("fetchPurchaseOrders")(...args)) as typeof firebaseProvider.fetchPurchaseOrders

export const addPurchaseOrder: typeof firebaseProvider.addPurchaseOrder = ((...args: Parameters<typeof firebaseProvider.addPurchaseOrder>) =>
  resolveImplementation("addPurchaseOrder")(...args)) as typeof firebaseProvider.addPurchaseOrder

export const updatePurchaseOrder: typeof firebaseProvider.updatePurchaseOrder = ((...args: Parameters<typeof firebaseProvider.updatePurchaseOrder>) =>
  resolveImplementation("updatePurchaseOrder")(...args)) as typeof firebaseProvider.updatePurchaseOrder

export const fetchLocations: typeof firebaseProvider.fetchLocations = ((...args: Parameters<typeof firebaseProvider.fetchLocations>) =>
  resolveImplementation("fetchLocations")(...args)) as typeof firebaseProvider.fetchLocations

export const fetchCurrentStock: typeof firebaseProvider.fetchCurrentStock = ((...args: Parameters<typeof firebaseProvider.fetchCurrentStock>) =>
  resolveImplementation("fetchCurrentStock")(...args)) as typeof firebaseProvider.fetchCurrentStock

export const createTable: typeof firebaseProvider.createTable = ((...args: Parameters<typeof firebaseProvider.createTable>) =>
  resolveImplementation("createTable")(...args)) as typeof firebaseProvider.createTable

export const saveFloorPlan: typeof firebaseProvider.saveFloorPlan = ((...args: Parameters<typeof firebaseProvider.saveFloorPlan>) =>
  resolveImplementation("saveFloorPlan")(...args)) as typeof firebaseProvider.saveFloorPlan

export const fetchMeasureUnits: typeof firebaseProvider.fetchMeasureUnits = ((...args: Parameters<typeof firebaseProvider.fetchMeasureUnits>) =>
  resolveImplementation("fetchMeasureUnits")(...args)) as typeof firebaseProvider.fetchMeasureUnits

export const deletePurchaseOrder: typeof firebaseProvider.deletePurchaseOrder = ((...args: Parameters<typeof firebaseProvider.deletePurchaseOrder>) =>
  resolveImplementation("deletePurchaseOrder")(...args)) as typeof firebaseProvider.deletePurchaseOrder

export const fetchTillScreen: typeof firebaseProvider.fetchTillScreen = ((...args: Parameters<typeof firebaseProvider.fetchTillScreen>) =>
  resolveImplementation("fetchTillScreen")(...args)) as typeof firebaseProvider.fetchTillScreen

export const saveTillScreenWithId: typeof firebaseProvider.saveTillScreenWithId = ((...args: Parameters<typeof firebaseProvider.saveTillScreenWithId>) =>
  resolveImplementation("saveTillScreenWithId")(...args)) as typeof firebaseProvider.saveTillScreenWithId

export const fetchStockItems2: typeof firebaseProvider.fetchStockItems2 = ((...args: Parameters<typeof firebaseProvider.fetchStockItems2>) =>
  resolveImplementation("fetchStockItems2")(...args)) as typeof firebaseProvider.fetchStockItems2

export const createStockItem2: typeof firebaseProvider.createStockItem2 = ((...args: Parameters<typeof firebaseProvider.createStockItem2>) =>
  resolveImplementation("createStockItem2")(...args)) as typeof firebaseProvider.createStockItem2

export const updateStockItem2: typeof firebaseProvider.updateStockItem2 = ((...args: Parameters<typeof firebaseProvider.updateStockItem2>) =>
  resolveImplementation("updateStockItem2")(...args)) as typeof firebaseProvider.updateStockItem2

export const deleteStockItem2: typeof firebaseProvider.deleteStockItem2 = ((...args: Parameters<typeof firebaseProvider.deleteStockItem2>) =>
  resolveImplementation("deleteStockItem2")(...args)) as typeof firebaseProvider.deleteStockItem2

export const fetchSuppliers2: typeof firebaseProvider.fetchSuppliers2 = ((...args: Parameters<typeof firebaseProvider.fetchSuppliers2>) =>
  resolveImplementation("fetchSuppliers2")(...args)) as typeof firebaseProvider.fetchSuppliers2

export const createSupplier2: typeof firebaseProvider.createSupplier2 = ((...args: Parameters<typeof firebaseProvider.createSupplier2>) =>
  resolveImplementation("createSupplier2")(...args)) as typeof firebaseProvider.createSupplier2

export const fetchPurchaseOrders2: typeof firebaseProvider.fetchPurchaseOrders2 = ((...args: Parameters<typeof firebaseProvider.fetchPurchaseOrders2>) =>
  resolveImplementation("fetchPurchaseOrders2")(...args)) as typeof firebaseProvider.fetchPurchaseOrders2

export const createPurchaseOrder2: typeof firebaseProvider.createPurchaseOrder2 = ((...args: Parameters<typeof firebaseProvider.createPurchaseOrder2>) =>
  resolveImplementation("createPurchaseOrder2")(...args)) as typeof firebaseProvider.createPurchaseOrder2

export const fetchStockCounts2: typeof firebaseProvider.fetchStockCounts2 = ((...args: Parameters<typeof firebaseProvider.fetchStockCounts2>) =>
  resolveImplementation("fetchStockCounts2")(...args)) as typeof firebaseProvider.fetchStockCounts2

export const createStockCount2: typeof firebaseProvider.createStockCount2 = ((...args: Parameters<typeof firebaseProvider.createStockCount2>) =>
  resolveImplementation("createStockCount2")(...args)) as typeof firebaseProvider.createStockCount2

export const updateStockCount2: typeof firebaseProvider.updateStockCount2 = ((...args: Parameters<typeof firebaseProvider.updateStockCount2>) =>
  resolveImplementation("updateStockCount2")(...args)) as typeof firebaseProvider.updateStockCount2

export const deleteStockCount2: typeof firebaseProvider.deleteStockCount2 = ((...args: Parameters<typeof firebaseProvider.deleteStockCount2>) =>
  resolveImplementation("deleteStockCount2")(...args)) as typeof firebaseProvider.deleteStockCount2

export const adjustStockLevel2: typeof firebaseProvider.adjustStockLevel2 = ((...args: Parameters<typeof firebaseProvider.adjustStockLevel2>) =>
  resolveImplementation("adjustStockLevel2")(...args)) as typeof firebaseProvider.adjustStockLevel2

export const getLowStockItems2: typeof firebaseProvider.getLowStockItems2 = ((...args: Parameters<typeof firebaseProvider.getLowStockItems2>) =>
  resolveImplementation("getLowStockItems2")(...args)) as typeof firebaseProvider.getLowStockItems2

export const calculateStockValuation2: typeof firebaseProvider.calculateStockValuation2 = ((...args: Parameters<typeof firebaseProvider.calculateStockValuation2>) =>
  resolveImplementation("calculateStockValuation2")(...args)) as typeof firebaseProvider.calculateStockValuation2

export const addLocation: typeof firebaseProvider.addLocation = ((...args: Parameters<typeof firebaseProvider.addLocation>) =>
  resolveImplementation("addLocation")(...args)) as typeof firebaseProvider.addLocation

export const updateLocation: typeof firebaseProvider.updateLocation = ((...args: Parameters<typeof firebaseProvider.updateLocation>) =>
  resolveImplementation("updateLocation")(...args)) as typeof firebaseProvider.updateLocation

export const getPurchaseDetails: typeof firebaseProvider.getPurchaseDetails = ((...args: Parameters<typeof firebaseProvider.getPurchaseDetails>) =>
  resolveImplementation("getPurchaseDetails")(...args)) as typeof firebaseProvider.getPurchaseDetails

export const fetchSalesDivisionsFromBasePath: typeof firebaseProvider.fetchSalesDivisionsFromBasePath = ((...args: Parameters<typeof firebaseProvider.fetchSalesDivisionsFromBasePath>) =>
  resolveImplementation("fetchSalesDivisionsFromBasePath")(...args)) as typeof firebaseProvider.fetchSalesDivisionsFromBasePath

export const fetchCategoriesFromBasePath: typeof firebaseProvider.fetchCategoriesFromBasePath = ((...args: Parameters<typeof firebaseProvider.fetchCategoriesFromBasePath>) =>
  resolveImplementation("fetchCategoriesFromBasePath")(...args)) as typeof firebaseProvider.fetchCategoriesFromBasePath

export const fetchSubcategoriesFromBasePath: typeof firebaseProvider.fetchSubcategoriesFromBasePath = ((...args: Parameters<typeof firebaseProvider.fetchSubcategoriesFromBasePath>) =>
  resolveImplementation("fetchSubcategoriesFromBasePath")(...args)) as typeof firebaseProvider.fetchSubcategoriesFromBasePath

export const fetchAllPurchasesFromBasePath: typeof firebaseProvider.fetchAllPurchasesFromBasePath = ((...args: Parameters<typeof firebaseProvider.fetchAllPurchasesFromBasePath>) =>
  resolveImplementation("fetchAllPurchasesFromBasePath")(...args)) as typeof firebaseProvider.fetchAllPurchasesFromBasePath

export const fetchAllStockCountsFromBasePath: typeof firebaseProvider.fetchAllStockCountsFromBasePath = ((...args: Parameters<typeof firebaseProvider.fetchAllStockCountsFromBasePath>) =>
  resolveImplementation("fetchAllStockCountsFromBasePath")(...args)) as typeof firebaseProvider.fetchAllStockCountsFromBasePath

export const deleteStockCountFromBasePath: typeof firebaseProvider.deleteStockCountFromBasePath = ((...args: Parameters<typeof firebaseProvider.deleteStockCountFromBasePath>) =>
  resolveImplementation("deleteStockCountFromBasePath")(...args)) as typeof firebaseProvider.deleteStockCountFromBasePath

export const fetchAllStockTransfersFromBasePath: typeof firebaseProvider.fetchAllStockTransfersFromBasePath = ((...args: Parameters<typeof firebaseProvider.fetchAllStockTransfersFromBasePath>) =>
  resolveImplementation("fetchAllStockTransfersFromBasePath")(...args)) as typeof firebaseProvider.fetchAllStockTransfersFromBasePath

export const fetchStockTransferByIdFromBasePath: typeof firebaseProvider.fetchStockTransferByIdFromBasePath = ((...args: Parameters<typeof firebaseProvider.fetchStockTransferByIdFromBasePath>) =>
  resolveImplementation("fetchStockTransferByIdFromBasePath")(...args)) as typeof firebaseProvider.fetchStockTransferByIdFromBasePath

export const saveStockTransfer: typeof firebaseProvider.saveStockTransfer = ((...args: Parameters<typeof firebaseProvider.saveStockTransfer>) =>
  resolveImplementation("saveStockTransfer")(...args)) as typeof firebaseProvider.saveStockTransfer

export const deleteStockTransferFromBasePath: typeof firebaseProvider.deleteStockTransferFromBasePath = ((...args: Parameters<typeof firebaseProvider.deleteStockTransferFromBasePath>) =>
  resolveImplementation("deleteStockTransferFromBasePath")(...args)) as typeof firebaseProvider.deleteStockTransferFromBasePath

export const fetchStockItemsFromBasePath: typeof firebaseProvider.fetchStockItemsFromBasePath = ((...args: Parameters<typeof firebaseProvider.fetchStockItemsFromBasePath>) =>
  resolveImplementation("fetchStockItemsFromBasePath")(...args)) as typeof firebaseProvider.fetchStockItemsFromBasePath

export const fetchPurchaseOrdersFromBasePath: typeof firebaseProvider.fetchPurchaseOrdersFromBasePath = ((...args: Parameters<typeof firebaseProvider.fetchPurchaseOrdersFromBasePath>) =>
  resolveImplementation("fetchPurchaseOrdersFromBasePath")(...args)) as typeof firebaseProvider.fetchPurchaseOrdersFromBasePath

export const fetchLatestCountsForProductsFromBasePath: typeof firebaseProvider.fetchLatestCountsForProductsFromBasePath = ((...args: Parameters<typeof firebaseProvider.fetchLatestCountsForProductsFromBasePath>) =>
  resolveImplementation("fetchLatestCountsForProductsFromBasePath")(...args)) as typeof firebaseProvider.fetchLatestCountsForProductsFromBasePath

export const fetchPurchasesHistoryFromBasePath: typeof firebaseProvider.fetchPurchasesHistoryFromBasePath = ((...args: Parameters<typeof firebaseProvider.fetchPurchasesHistoryFromBasePath>) =>
  resolveImplementation("fetchPurchasesHistoryFromBasePath")(...args)) as typeof firebaseProvider.fetchPurchasesHistoryFromBasePath

export const fetchSalesHistoryFromBasePath: typeof firebaseProvider.fetchSalesHistoryFromBasePath = ((...args: Parameters<typeof firebaseProvider.fetchSalesHistoryFromBasePath>) =>
  resolveImplementation("fetchSalesHistoryFromBasePath")(...args)) as typeof firebaseProvider.fetchSalesHistoryFromBasePath
