// Generated by scripts/generate-data-layer.cjs. Do not edit by hand.
import * as firebaseProvider from "../rtdatabase/Supply"
import * as supabaseProvider from "../providers/supabase/Supply"
import { getModuleProvider } from "./providerRegistry"

type ProviderModule = typeof firebaseProvider
type ProviderFn<T extends keyof ProviderModule> = ProviderModule[T] extends (...args: infer Args) => infer Result
  ? (...args: Args) => Result
  : never

const resolveImplementation = <T extends keyof ProviderModule>(name: T): ProviderFn<T> => {
  const provider = getModuleProvider("Supply")
  const source = provider === "supabase" ? (supabaseProvider as ProviderModule) : (firebaseProvider as ProviderModule)
  const implementation = source[name]
  if (typeof implementation !== "function") {
    throw new Error(`[data-provider] ${String(name)} is not implemented for provider "${provider}" in module "Supply".`)
  }
  return implementation as ProviderFn<T>
}

export const subscribeClients: typeof firebaseProvider.subscribeClients = ((...args: Parameters<typeof firebaseProvider.subscribeClients>) =>
  resolveImplementation("subscribeClients")(...args)) as typeof firebaseProvider.subscribeClients

export const subscribeOrders: typeof firebaseProvider.subscribeOrders = ((...args: Parameters<typeof firebaseProvider.subscribeOrders>) =>
  resolveImplementation("subscribeOrders")(...args)) as typeof firebaseProvider.subscribeOrders

export const subscribeDeliveries: typeof firebaseProvider.subscribeDeliveries = ((...args: Parameters<typeof firebaseProvider.subscribeDeliveries>) =>
  resolveImplementation("subscribeDeliveries")(...args)) as typeof firebaseProvider.subscribeDeliveries

export const fetchClients: typeof firebaseProvider.fetchClients = ((...args: Parameters<typeof firebaseProvider.fetchClients>) =>
  resolveImplementation("fetchClients")(...args)) as typeof firebaseProvider.fetchClients

export const fetchOrders: typeof firebaseProvider.fetchOrders = ((...args: Parameters<typeof firebaseProvider.fetchOrders>) =>
  resolveImplementation("fetchOrders")(...args)) as typeof firebaseProvider.fetchOrders

export const fetchDeliveries: typeof firebaseProvider.fetchDeliveries = ((...args: Parameters<typeof firebaseProvider.fetchDeliveries>) =>
  resolveImplementation("fetchDeliveries")(...args)) as typeof firebaseProvider.fetchDeliveries

export const createClient: typeof firebaseProvider.createClient = ((...args: Parameters<typeof firebaseProvider.createClient>) =>
  resolveImplementation("createClient")(...args)) as typeof firebaseProvider.createClient

export const updateClient: typeof firebaseProvider.updateClient = ((...args: Parameters<typeof firebaseProvider.updateClient>) =>
  resolveImplementation("updateClient")(...args)) as typeof firebaseProvider.updateClient

export const deleteClient: typeof firebaseProvider.deleteClient = ((...args: Parameters<typeof firebaseProvider.deleteClient>) =>
  resolveImplementation("deleteClient")(...args)) as typeof firebaseProvider.deleteClient

export const createOrder: typeof firebaseProvider.createOrder = ((...args: Parameters<typeof firebaseProvider.createOrder>) =>
  resolveImplementation("createOrder")(...args)) as typeof firebaseProvider.createOrder

export const updateOrder: typeof firebaseProvider.updateOrder = ((...args: Parameters<typeof firebaseProvider.updateOrder>) =>
  resolveImplementation("updateOrder")(...args)) as typeof firebaseProvider.updateOrder

export const deleteOrder: typeof firebaseProvider.deleteOrder = ((...args: Parameters<typeof firebaseProvider.deleteOrder>) =>
  resolveImplementation("deleteOrder")(...args)) as typeof firebaseProvider.deleteOrder

export const createDelivery: typeof firebaseProvider.createDelivery = ((...args: Parameters<typeof firebaseProvider.createDelivery>) =>
  resolveImplementation("createDelivery")(...args)) as typeof firebaseProvider.createDelivery

export const updateDelivery: typeof firebaseProvider.updateDelivery = ((...args: Parameters<typeof firebaseProvider.updateDelivery>) =>
  resolveImplementation("updateDelivery")(...args)) as typeof firebaseProvider.updateDelivery

export const deleteDelivery: typeof firebaseProvider.deleteDelivery = ((...args: Parameters<typeof firebaseProvider.deleteDelivery>) =>
  resolveImplementation("deleteDelivery")(...args)) as typeof firebaseProvider.deleteDelivery

export const createClientInvite: typeof firebaseProvider.createClientInvite = ((...args: Parameters<typeof firebaseProvider.createClientInvite>) =>
  resolveImplementation("createClientInvite")(...args)) as typeof firebaseProvider.createClientInvite

export const getClientInviteByCode: typeof firebaseProvider.getClientInviteByCode = ((...args: Parameters<typeof firebaseProvider.getClientInviteByCode>) =>
  resolveImplementation("getClientInviteByCode")(...args)) as typeof firebaseProvider.getClientInviteByCode

export const updateClientInvite: typeof firebaseProvider.updateClientInvite = ((...args: Parameters<typeof firebaseProvider.updateClientInvite>) =>
  resolveImplementation("updateClientInvite")(...args)) as typeof firebaseProvider.updateClientInvite

export const revokeClientInvite: typeof firebaseProvider.revokeClientInvite = ((...args: Parameters<typeof firebaseProvider.revokeClientInvite>) =>
  resolveImplementation("revokeClientInvite")(...args)) as typeof firebaseProvider.revokeClientInvite

export const getGlobalClientInviteByCode: typeof firebaseProvider.getGlobalClientInviteByCode = ((...args: Parameters<typeof firebaseProvider.getGlobalClientInviteByCode>) =>
  resolveImplementation("getGlobalClientInviteByCode")(...args)) as typeof firebaseProvider.getGlobalClientInviteByCode

export const updateGlobalClientInvite: typeof firebaseProvider.updateGlobalClientInvite = ((...args: Parameters<typeof firebaseProvider.updateGlobalClientInvite>) =>
  resolveImplementation("updateGlobalClientInvite")(...args)) as typeof firebaseProvider.updateGlobalClientInvite

export const getSupplierConnection: typeof firebaseProvider.getSupplierConnection = ((...args: Parameters<typeof firebaseProvider.getSupplierConnection>) =>
  resolveImplementation("getSupplierConnection")(...args)) as typeof firebaseProvider.getSupplierConnection

export const saveSupplierConnection: typeof firebaseProvider.saveSupplierConnection = ((...args: Parameters<typeof firebaseProvider.saveSupplierConnection>) =>
  resolveImplementation("saveSupplierConnection")(...args)) as typeof firebaseProvider.saveSupplierConnection

export const fetchSupplySettingsSection: typeof firebaseProvider.fetchSupplySettingsSection = ((...args: Parameters<typeof firebaseProvider.fetchSupplySettingsSection>) =>
  resolveImplementation("fetchSupplySettingsSection")(...args)) as typeof firebaseProvider.fetchSupplySettingsSection

export const saveSupplySettingsSection: typeof firebaseProvider.saveSupplySettingsSection = ((...args: Parameters<typeof firebaseProvider.saveSupplySettingsSection>) =>
  resolveImplementation("saveSupplySettingsSection")(...args)) as typeof firebaseProvider.saveSupplySettingsSection
