"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.adminIntegrationsListSites = exports.adminIntegrationsListCompanies = exports.lightspeedKScheduledSync = exports.lightspeedKRunSync = exports.lightspeedKGetBusinesses = exports.lightspeedKDisconnect = exports.lightspeedKRefreshToken = exports.oauthCallbackLightspeedK = exports.lightspeedKConnect = exports.oauthLightspeedK = exports.onBugReportCreated = exports.sendAuthEmail = exports.opsProcessActions = exports.opsSyncAll = exports.opsRouter = exports.assistantGateway = exports.apiVersion = exports.bootstrapAdmin = exports.createSuperAdminUser = exports.claimAdminInvite = exports.createAdminInvite = exports.hmrcSubmitRtiXml = exports.testHMRCEPSSubmission = exports.testHMRCAPIConnection = exports.exchangeHMRCToken = exports.getCalendarTaskLinks = exports.deleteEvent = exports.upsertEvent = exports.listEvents = exports.listCalendars = exports.onSocialPostCreated = exports.processScheduledSocialPosts = exports.processEmailOutboxUser = exports.processEmailOutbox = exports.syncEmailInbox = exports.sendCompanyInviteEmail = exports.sendHREmployeeStarterEmail = exports.sendStockOrderEmail = exports.sendEmailWithGmail = exports.sendTestEmail = exports.disconnectOAuth = exports.checkOAuthStatus = exports.oauthCallbackOutlookCalendar = exports.oauthOutlookCalendar = exports.oauthCallbackGoogleCalendar = exports.oauthGoogleCalendar = exports.oauthCallbackOutlook = exports.oauthOutlook = exports.oauthCallbackGmail = exports.oauthGoogle = void 0;
exports.getMailboxSecretSettingsStatus = exports.saveMailboxSecretSettings = exports.hmrcRefreshAccessToken = exports.hmrcExchangeCodeAndStoreTokens = exports.hmrcGetConnectionStatus = exports.hmrcSaveClientSecret = exports.hrMigrateEncryptAtRestV2 = exports.hrSavePayroll = exports.hrGetPayroll = exports.hrListPayrolls = exports.hrDeleteEmployee = exports.hrUpsertEmployee = exports.hrGetEmployee = exports.hrListEmployees = exports.adminIntegrationsKSeriesSyncFinancials = exports.adminIntegrationsKSeriesSyncItems = exports.adminIntegrationsKSeriesSaveBusinessLocation = exports.adminIntegrationsKSeriesSaveCredentials = exports.adminIntegrationsKSeriesPreview = exports.adminIntegrationsKSeriesStatus = exports.adminIntegrationsListSubsites = void 0;
// Initialize admin first (lazy initialization)
require("./admin");
// Export all OAuth functions
var oauthGoogle_1 = require("./oauthGoogle");
Object.defineProperty(exports, "oauthGoogle", { enumerable: true, get: function () { return oauthGoogle_1.oauthGoogle; } });
Object.defineProperty(exports, "oauthCallbackGmail", { enumerable: true, get: function () { return oauthGoogle_1.oauthCallbackGmail; } });
var oauthOutlook_1 = require("./oauthOutlook");
Object.defineProperty(exports, "oauthOutlook", { enumerable: true, get: function () { return oauthOutlook_1.oauthOutlook; } });
Object.defineProperty(exports, "oauthCallbackOutlook", { enumerable: true, get: function () { return oauthOutlook_1.oauthCallbackOutlook; } });
var oauthGoogleCalendar_1 = require("./oauthGoogleCalendar");
Object.defineProperty(exports, "oauthGoogleCalendar", { enumerable: true, get: function () { return oauthGoogleCalendar_1.oauthGoogleCalendar; } });
Object.defineProperty(exports, "oauthCallbackGoogleCalendar", { enumerable: true, get: function () { return oauthGoogleCalendar_1.oauthCallbackGoogleCalendar; } });
var oauthOutlookCalendar_1 = require("./oauthOutlookCalendar");
Object.defineProperty(exports, "oauthOutlookCalendar", { enumerable: true, get: function () { return oauthOutlookCalendar_1.oauthOutlookCalendar; } });
Object.defineProperty(exports, "oauthCallbackOutlookCalendar", { enumerable: true, get: function () { return oauthOutlookCalendar_1.oauthCallbackOutlookCalendar; } });
var checkOAuthStatus_1 = require("./checkOAuthStatus");
Object.defineProperty(exports, "checkOAuthStatus", { enumerable: true, get: function () { return checkOAuthStatus_1.checkOAuthStatus; } });
Object.defineProperty(exports, "disconnectOAuth", { enumerable: true, get: function () { return checkOAuthStatus_1.disconnectOAuth; } });
var sendTestEmail_1 = require("./sendTestEmail");
Object.defineProperty(exports, "sendTestEmail", { enumerable: true, get: function () { return sendTestEmail_1.sendTestEmail; } });
var sendEmailWithGmail_1 = require("./sendEmailWithGmail");
Object.defineProperty(exports, "sendEmailWithGmail", { enumerable: true, get: function () { return sendEmailWithGmail_1.sendEmailWithGmail; } });
var sendStockOrderEmail_1 = require("./sendStockOrderEmail");
Object.defineProperty(exports, "sendStockOrderEmail", { enumerable: true, get: function () { return sendStockOrderEmail_1.sendStockOrderEmail; } });
var sendHREmployeeStarterEmail_1 = require("./sendHREmployeeStarterEmail");
Object.defineProperty(exports, "sendHREmployeeStarterEmail", { enumerable: true, get: function () { return sendHREmployeeStarterEmail_1.sendHREmployeeStarterEmail; } });
var sendCompanyInviteEmail_1 = require("./sendCompanyInviteEmail");
Object.defineProperty(exports, "sendCompanyInviteEmail", { enumerable: true, get: function () { return sendCompanyInviteEmail_1.sendCompanyInviteEmail; } });
var adminEmail_1 = require("./adminEmail");
Object.defineProperty(exports, "syncEmailInbox", { enumerable: true, get: function () { return adminEmail_1.syncEmailInbox; } });
Object.defineProperty(exports, "processEmailOutbox", { enumerable: true, get: function () { return adminEmail_1.processEmailOutbox; } });
Object.defineProperty(exports, "processEmailOutboxUser", { enumerable: true, get: function () { return adminEmail_1.processEmailOutboxUser; } });
var socialPoster_1 = require("./socialPoster");
Object.defineProperty(exports, "processScheduledSocialPosts", { enumerable: true, get: function () { return socialPoster_1.processScheduledSocialPosts; } });
Object.defineProperty(exports, "onSocialPostCreated", { enumerable: true, get: function () { return socialPoster_1.onSocialPostCreated; } });
var adminCalendar_1 = require("./adminCalendar");
Object.defineProperty(exports, "listCalendars", { enumerable: true, get: function () { return adminCalendar_1.listCalendars; } });
Object.defineProperty(exports, "listEvents", { enumerable: true, get: function () { return adminCalendar_1.listEvents; } });
Object.defineProperty(exports, "upsertEvent", { enumerable: true, get: function () { return adminCalendar_1.upsertEvent; } });
Object.defineProperty(exports, "deleteEvent", { enumerable: true, get: function () { return adminCalendar_1.deleteEvent; } });
Object.defineProperty(exports, "getCalendarTaskLinks", { enumerable: true, get: function () { return adminCalendar_1.getCalendarTaskLinks; } });
var hmrcOAuth_1 = require("./hmrcOAuth");
Object.defineProperty(exports, "exchangeHMRCToken", { enumerable: true, get: function () { return hmrcOAuth_1.exchangeHMRCToken; } });
var hmrcTestAPI_1 = require("./hmrcTestAPI");
Object.defineProperty(exports, "testHMRCAPIConnection", { enumerable: true, get: function () { return hmrcTestAPI_1.testHMRCAPIConnection; } });
var hmrcTestEPS_1 = require("./hmrcTestEPS");
Object.defineProperty(exports, "testHMRCEPSSubmission", { enumerable: true, get: function () { return hmrcTestEPS_1.testHMRCEPSSubmission; } });
var hmrcRtiSubmit_1 = require("./hmrcRtiSubmit");
Object.defineProperty(exports, "hmrcSubmitRtiXml", { enumerable: true, get: function () { return hmrcRtiSubmit_1.hmrcSubmitRtiXml; } });
var adminStaffInvites_1 = require("./adminStaffInvites");
Object.defineProperty(exports, "createAdminInvite", { enumerable: true, get: function () { return adminStaffInvites_1.createAdminInvite; } });
Object.defineProperty(exports, "claimAdminInvite", { enumerable: true, get: function () { return adminStaffInvites_1.claimAdminInvite; } });
var createSuperAdminUser_1 = require("./createSuperAdminUser");
Object.defineProperty(exports, "createSuperAdminUser", { enumerable: true, get: function () { return createSuperAdminUser_1.createSuperAdminUser; } });
var bootstrapAdmin_1 = require("./bootstrapAdmin");
Object.defineProperty(exports, "bootstrapAdmin", { enumerable: true, get: function () { return bootstrapAdmin_1.bootstrapAdmin; } });
var apiVersion_1 = require("./apiVersion");
Object.defineProperty(exports, "apiVersion", { enumerable: true, get: function () { return apiVersion_1.apiVersion; } });
var assistantGateway_1 = require("./assistantGateway");
Object.defineProperty(exports, "assistantGateway", { enumerable: true, get: function () { return assistantGateway_1.assistantGateway; } });
var opsRouter_1 = require("./opsRouter");
Object.defineProperty(exports, "opsRouter", { enumerable: true, get: function () { return opsRouter_1.opsRouter; } });
var opsScheduler_1 = require("./opsScheduler");
Object.defineProperty(exports, "opsSyncAll", { enumerable: true, get: function () { return opsScheduler_1.opsSyncAll; } });
var opsActionProcessor_1 = require("./opsActionProcessor");
Object.defineProperty(exports, "opsProcessActions", { enumerable: true, get: function () { return opsActionProcessor_1.opsProcessActions; } });
var sendAuthEmail_1 = require("./sendAuthEmail");
Object.defineProperty(exports, "sendAuthEmail", { enumerable: true, get: function () { return sendAuthEmail_1.sendAuthEmail; } });
var bugReportAutoReply_1 = require("./bugReportAutoReply");
Object.defineProperty(exports, "onBugReportCreated", { enumerable: true, get: function () { return bugReportAutoReply_1.onBugReportCreated; } });
var oauthLightspeedK_1 = require("./oauthLightspeedK");
Object.defineProperty(exports, "oauthLightspeedK", { enumerable: true, get: function () { return oauthLightspeedK_1.oauthLightspeedK; } });
Object.defineProperty(exports, "lightspeedKConnect", { enumerable: true, get: function () { return oauthLightspeedK_1.lightspeedKConnect; } });
Object.defineProperty(exports, "oauthCallbackLightspeedK", { enumerable: true, get: function () { return oauthLightspeedK_1.oauthCallbackLightspeedK; } });
Object.defineProperty(exports, "lightspeedKRefreshToken", { enumerable: true, get: function () { return oauthLightspeedK_1.lightspeedKRefreshToken; } });
Object.defineProperty(exports, "lightspeedKDisconnect", { enumerable: true, get: function () { return oauthLightspeedK_1.lightspeedKDisconnect; } });
var lightspeedKSync_1 = require("./lightspeedKSync");
Object.defineProperty(exports, "lightspeedKGetBusinesses", { enumerable: true, get: function () { return lightspeedKSync_1.lightspeedKGetBusinesses; } });
Object.defineProperty(exports, "lightspeedKRunSync", { enumerable: true, get: function () { return lightspeedKSync_1.lightspeedKRunSync; } });
Object.defineProperty(exports, "lightspeedKScheduledSync", { enumerable: true, get: function () { return lightspeedKSync_1.lightspeedKScheduledSync; } });
var adminIntegrationsKSeries_1 = require("./adminIntegrationsKSeries");
Object.defineProperty(exports, "adminIntegrationsListCompanies", { enumerable: true, get: function () { return adminIntegrationsKSeries_1.adminIntegrationsListCompanies; } });
Object.defineProperty(exports, "adminIntegrationsListSites", { enumerable: true, get: function () { return adminIntegrationsKSeries_1.adminIntegrationsListSites; } });
Object.defineProperty(exports, "adminIntegrationsListSubsites", { enumerable: true, get: function () { return adminIntegrationsKSeries_1.adminIntegrationsListSubsites; } });
Object.defineProperty(exports, "adminIntegrationsKSeriesStatus", { enumerable: true, get: function () { return adminIntegrationsKSeries_1.adminIntegrationsKSeriesStatus; } });
Object.defineProperty(exports, "adminIntegrationsKSeriesPreview", { enumerable: true, get: function () { return adminIntegrationsKSeries_1.adminIntegrationsKSeriesPreview; } });
Object.defineProperty(exports, "adminIntegrationsKSeriesSaveCredentials", { enumerable: true, get: function () { return adminIntegrationsKSeries_1.adminIntegrationsKSeriesSaveCredentials; } });
Object.defineProperty(exports, "adminIntegrationsKSeriesSaveBusinessLocation", { enumerable: true, get: function () { return adminIntegrationsKSeries_1.adminIntegrationsKSeriesSaveBusinessLocation; } });
Object.defineProperty(exports, "adminIntegrationsKSeriesSyncItems", { enumerable: true, get: function () { return adminIntegrationsKSeries_1.adminIntegrationsKSeriesSyncItems; } });
Object.defineProperty(exports, "adminIntegrationsKSeriesSyncFinancials", { enumerable: true, get: function () { return adminIntegrationsKSeries_1.adminIntegrationsKSeriesSyncFinancials; } });
// HR secure data (server-side encryption/decryption)
var hrSecureData_1 = require("./hrSecureData");
Object.defineProperty(exports, "hrListEmployees", { enumerable: true, get: function () { return hrSecureData_1.hrListEmployees; } });
Object.defineProperty(exports, "hrGetEmployee", { enumerable: true, get: function () { return hrSecureData_1.hrGetEmployee; } });
Object.defineProperty(exports, "hrUpsertEmployee", { enumerable: true, get: function () { return hrSecureData_1.hrUpsertEmployee; } });
Object.defineProperty(exports, "hrDeleteEmployee", { enumerable: true, get: function () { return hrSecureData_1.hrDeleteEmployee; } });
Object.defineProperty(exports, "hrListPayrolls", { enumerable: true, get: function () { return hrSecureData_1.hrListPayrolls; } });
Object.defineProperty(exports, "hrGetPayroll", { enumerable: true, get: function () { return hrSecureData_1.hrGetPayroll; } });
Object.defineProperty(exports, "hrSavePayroll", { enumerable: true, get: function () { return hrSecureData_1.hrSavePayroll; } });
// One-time HR encryption migration
var hrMigrateEncryptAtRest_1 = require("./hrMigrateEncryptAtRest");
Object.defineProperty(exports, "hrMigrateEncryptAtRestV2", { enumerable: true, get: function () { return hrMigrateEncryptAtRest_1.hrMigrateEncryptAtRestV2; } });
// HMRC secure token storage (server-side secrets)
var hmrcSecureTokens_1 = require("./hmrcSecureTokens");
Object.defineProperty(exports, "hmrcSaveClientSecret", { enumerable: true, get: function () { return hmrcSecureTokens_1.hmrcSaveClientSecret; } });
Object.defineProperty(exports, "hmrcGetConnectionStatus", { enumerable: true, get: function () { return hmrcSecureTokens_1.hmrcGetConnectionStatus; } });
Object.defineProperty(exports, "hmrcExchangeCodeAndStoreTokens", { enumerable: true, get: function () { return hmrcSecureTokens_1.hmrcExchangeCodeAndStoreTokens; } });
Object.defineProperty(exports, "hmrcRefreshAccessToken", { enumerable: true, get: function () { return hmrcSecureTokens_1.hmrcRefreshAccessToken; } });
var mailboxSecretSettings_1 = require("./mailboxSecretSettings");
Object.defineProperty(exports, "saveMailboxSecretSettings", { enumerable: true, get: function () { return mailboxSecretSettings_1.saveMailboxSecretSettings; } });
Object.defineProperty(exports, "getMailboxSecretSettingsStatus", { enumerable: true, get: function () { return mailboxSecretSettings_1.getMailboxSecretSettingsStatus; } });
//# sourceMappingURL=index.js.map