"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.bootstrapAdmin = exports.createSuperAdminUser = exports.claimAdminInvite = exports.createAdminInvite = exports.testHMRCEPSSubmission = exports.testHMRCAPIConnection = exports.exchangeHMRCToken = exports.getCalendarTaskLinks = exports.deleteEvent = exports.upsertEvent = exports.listEvents = exports.listCalendars = exports.onSocialPostCreated = exports.processScheduledSocialPosts = exports.processEmailOutboxUser = exports.processEmailOutbox = exports.syncEmailInbox = exports.sendCompanyInviteEmail = exports.sendEmailWithGmail = exports.sendTestEmail = exports.disconnectOAuth = exports.checkOAuthStatus = exports.oauthCallbackOutlookCalendar = exports.oauthOutlookCalendar = exports.oauthCallbackGoogleCalendar = exports.oauthGoogleCalendar = exports.oauthCallbackOutlook = exports.oauthOutlook = exports.oauthCallbackGmail = exports.oauthGoogle = void 0;
// Initialize admin first (lazy initialization)
require("./admin");
// Export all OAuth functions
var oauthGoogle_1 = require("./oauthGoogle");
Object.defineProperty(exports, "oauthGoogle", { enumerable: true, get: function () { return oauthGoogle_1.oauthGoogle; } });
Object.defineProperty(exports, "oauthCallbackGmail", { enumerable: true, get: function () { return oauthGoogle_1.oauthCallbackGmail; } });
var oauthOutlook_1 = require("./oauthOutlook");
Object.defineProperty(exports, "oauthOutlook", { enumerable: true, get: function () { return oauthOutlook_1.oauthOutlook; } });
Object.defineProperty(exports, "oauthCallbackOutlook", { enumerable: true, get: function () { return oauthOutlook_1.oauthCallbackOutlook; } });
var oauthGoogleCalendar_1 = require("./oauthGoogleCalendar");
Object.defineProperty(exports, "oauthGoogleCalendar", { enumerable: true, get: function () { return oauthGoogleCalendar_1.oauthGoogleCalendar; } });
Object.defineProperty(exports, "oauthCallbackGoogleCalendar", { enumerable: true, get: function () { return oauthGoogleCalendar_1.oauthCallbackGoogleCalendar; } });
var oauthOutlookCalendar_1 = require("./oauthOutlookCalendar");
Object.defineProperty(exports, "oauthOutlookCalendar", { enumerable: true, get: function () { return oauthOutlookCalendar_1.oauthOutlookCalendar; } });
Object.defineProperty(exports, "oauthCallbackOutlookCalendar", { enumerable: true, get: function () { return oauthOutlookCalendar_1.oauthCallbackOutlookCalendar; } });
var checkOAuthStatus_1 = require("./checkOAuthStatus");
Object.defineProperty(exports, "checkOAuthStatus", { enumerable: true, get: function () { return checkOAuthStatus_1.checkOAuthStatus; } });
Object.defineProperty(exports, "disconnectOAuth", { enumerable: true, get: function () { return checkOAuthStatus_1.disconnectOAuth; } });
var sendTestEmail_1 = require("./sendTestEmail");
Object.defineProperty(exports, "sendTestEmail", { enumerable: true, get: function () { return sendTestEmail_1.sendTestEmail; } });
var sendEmailWithGmail_1 = require("./sendEmailWithGmail");
Object.defineProperty(exports, "sendEmailWithGmail", { enumerable: true, get: function () { return sendEmailWithGmail_1.sendEmailWithGmail; } });
var sendCompanyInviteEmail_1 = require("./sendCompanyInviteEmail");
Object.defineProperty(exports, "sendCompanyInviteEmail", { enumerable: true, get: function () { return sendCompanyInviteEmail_1.sendCompanyInviteEmail; } });
var adminEmail_1 = require("./adminEmail");
Object.defineProperty(exports, "syncEmailInbox", { enumerable: true, get: function () { return adminEmail_1.syncEmailInbox; } });
Object.defineProperty(exports, "processEmailOutbox", { enumerable: true, get: function () { return adminEmail_1.processEmailOutbox; } });
Object.defineProperty(exports, "processEmailOutboxUser", { enumerable: true, get: function () { return adminEmail_1.processEmailOutboxUser; } });
var socialPoster_1 = require("./socialPoster");
Object.defineProperty(exports, "processScheduledSocialPosts", { enumerable: true, get: function () { return socialPoster_1.processScheduledSocialPosts; } });
Object.defineProperty(exports, "onSocialPostCreated", { enumerable: true, get: function () { return socialPoster_1.onSocialPostCreated; } });
var adminCalendar_1 = require("./adminCalendar");
Object.defineProperty(exports, "listCalendars", { enumerable: true, get: function () { return adminCalendar_1.listCalendars; } });
Object.defineProperty(exports, "listEvents", { enumerable: true, get: function () { return adminCalendar_1.listEvents; } });
Object.defineProperty(exports, "upsertEvent", { enumerable: true, get: function () { return adminCalendar_1.upsertEvent; } });
Object.defineProperty(exports, "deleteEvent", { enumerable: true, get: function () { return adminCalendar_1.deleteEvent; } });
Object.defineProperty(exports, "getCalendarTaskLinks", { enumerable: true, get: function () { return adminCalendar_1.getCalendarTaskLinks; } });
var hmrcOAuth_1 = require("./hmrcOAuth");
Object.defineProperty(exports, "exchangeHMRCToken", { enumerable: true, get: function () { return hmrcOAuth_1.exchangeHMRCToken; } });
var hmrcTestAPI_1 = require("./hmrcTestAPI");
Object.defineProperty(exports, "testHMRCAPIConnection", { enumerable: true, get: function () { return hmrcTestAPI_1.testHMRCAPIConnection; } });
var hmrcTestEPS_1 = require("./hmrcTestEPS");
Object.defineProperty(exports, "testHMRCEPSSubmission", { enumerable: true, get: function () { return hmrcTestEPS_1.testHMRCEPSSubmission; } });
var adminStaffInvites_1 = require("./adminStaffInvites");
Object.defineProperty(exports, "createAdminInvite", { enumerable: true, get: function () { return adminStaffInvites_1.createAdminInvite; } });
Object.defineProperty(exports, "claimAdminInvite", { enumerable: true, get: function () { return adminStaffInvites_1.claimAdminInvite; } });
var createSuperAdminUser_1 = require("./createSuperAdminUser");
Object.defineProperty(exports, "createSuperAdminUser", { enumerable: true, get: function () { return createSuperAdminUser_1.createSuperAdminUser; } });
var bootstrapAdmin_1 = require("./bootstrapAdmin");
Object.defineProperty(exports, "bootstrapAdmin", { enumerable: true, get: function () { return bootstrapAdmin_1.bootstrapAdmin; } });
//# sourceMappingURL=index.js.map